/* =========================================================================
   SUJET NEUF — content2.js — Biome 2 : LA SERRE (palier -2). Un cran au-dessus d'ADMISSION.
   Variantes d'ennemis plus rapides et plus résistantes, salves, élites, boss ÉTALON 12 « la Serriste ».
   ========================================================================= */

'use strict';
CONTENT.biomes.push({
  id: 'biome_2',
  name: 'LA SERRE',
  order: 2,
  tagline: 'Une serre envahie : végétation agressive, gaz, ennemis qui se multiplient. Un cran au-dessus.',
  desc: "Palier -2. L'ancienne unité de culture des greffons : cuves éclatées, végétation qui a pris le contrôle des cellules d'essai, sol humide qui conduit tout. Le Bureau y a laissé pousser ce qu'il ne comprenait pas. Taux de perte : 84 %.",
  palette: {
    tint: 'rgba(40,120,70,.30)',
    neon: ['#7ed957', '#ffd166'],
    wall: 'rgba(30,90,60,.4)',
    terrain: { water: { fill: '#1e5a4a', edge: '#6ae0b0' }, bridge: { fill: '#4a5a2e', edge: '#8fbf6a' } },
  },
  levelPassives: [
    {
      bonus: { name: 'Photosynthèse', desc: 'Régénération +1,5 PV/s.', mods: [{ stat: 'regen', add: 1.5 }], hooks: {} },
      malus: { name: 'Air lourd', desc: '-15 % vitesse de déplacement.', mods: [{ stat: 'speed', mul: 0.85 }], hooks: {} },
    },
    {
      bonus: { name: 'Greffon sauvage', desc: '+1 projectile par tir.', mods: [{ stat: 'projectiles', add: 1 }], hooks: {} },
      malus: {
        name: 'Sève corrosive',
        desc: 'Les pièges infligent +50 % de dégâts, armure -1.',
        mods: [
          { stat: 'trapDamageMul', mul: 1.5 },
          { stat: 'armor', add: -1 },
        ],
        hooks: {},
      },
    },
    {
      bonus: {
        name: 'Récolte',
        desc: '+40 % pièces, +20 % XP.',
        mods: [
          { stat: 'coinGain', mul: 1.4 },
          { stat: 'xpGain', mul: 1.2 },
        ],
        hooks: {},
      },
      malus: {
        name: 'Serre chaude',
        desc: '-20 % PV max, invulnérabilité après un coup -0,15 s.',
        mods: [
          { stat: 'maxHp', mul: 0.8 },
          { stat: 'invulnTime', add: -0.15 },
        ],
        hooks: {},
      },
    },
  ],
  enemyPool: ['enemy_ronce', 'enemy_pollinisateur', 'enemy_racine', 'enemy_spore', 'enemy_bourgeon', 'enemy_moucherons', 'enemy_liane'],
  trapPool: [
    'trap_lianes',
    'trap_epines',
    'trap_spores',
    'trap_seve',
    'trap_arroseur',
    'trap_treillis',
    'trap_cracheuse',
    'trap_brumisateur',
    'trap_lampe_uv',
    'trap_tondeuse',
  ],
  miniboss: 'boss_serriste',
  difficulty: { hpMul: 1.3, damageMul: 1.2, speedMul: 1.08 },
  unlockAfter: 'biome_1',
});

CONTENT.enemies.push(
  {
    id: 'enemy_ronce',
    name: 'Ronce',
    archetype: 'rusher',
    desc: "Rôdeur envahi par les lianes : sa ruée est un bond, qui passe par-dessus les obstacles. On l'esquive de côté, pas derrière un bloc.",
    hp: 46,
    speed: 215,
    damage: 11,
    radius: 14,
    xp: 6,
    coins: 2,
    color: '#7ed957',
    sprite: 'enemy_rusher2',
    behavior: { variant: 'saut', lungeRange: 115, lungeWindup: 0.32, lungeSpeed: 600, lungeDuration: 0.3, lungeCooldown: 1.3 },
    telegraph: { time: 0.3, color: '#b7ff7a' },
  },
  {
    id: 'enemy_pollinisateur',
    name: 'Pollinisateur',
    archetype: 'shooter',
    desc: 'Tire une salve de 3 spores en éventail, qui rebondissent une fois sur les murs. Reste à distance.',
    hp: 36,
    speed: 140,
    damage: 8,
    radius: 14,
    xp: 8,
    coins: 3,
    color: '#c9a3ff',
    projColor: '#e2c6ff',
    sprite: 'enemy_shooter2',
    behavior: {
      variant: 'rebond',
      fireRate: 0.8,
      projSpeed: 340,
      projDamage: 9,
      projSize: 7,
      keepDistance: 320,
      aimTime: 0.45,
      burst: 3,
      spread: 0.4,
    },
    telegraph: { time: 0.45, color: '#e2c6ff' },
  },
  {
    id: 'enemy_racine',
    name: 'Racine',
    archetype: 'tank',
    desc: "Bloc végétal : charge vite, et au bout de sa charge s'enracine — trois ronces poussent autour de lui, qui blessent et ralentissent 3 s.",
    hp: 240,
    speed: 95,
    damage: 16,
    radius: 26,
    xp: 18,
    coins: 5,
    color: '#5aa06a',
    sprite: 'enemy_tank2',
    behavior: {
      variant: 'enracine',
      chargeWindup: 0.7,
      chargeSpeed: 620,
      chargeDuration: 0.8,
      chargeCooldown: 2.6,
      stunOnWallHit: 1.0,
      chargeDamageMul: 1.5,
    },
    telegraph: { time: 0.7, color: '#ffd166' },
  },
  {
    id: 'enemy_spore',
    name: 'Spore',
    archetype: 'kamikaze',
    desc: 'Explose dans un rayon plus large et laisse un nuage 3 s : dedans on souffre et on ralentit.',
    hp: 24,
    speed: 260,
    damage: 6,
    radius: 12,
    xp: 6,
    coins: 2,
    color: '#b7ff7a',
    sprite: 'enemy_kamikaze2',
    behavior: { variant: 'nuage', fuse: 0.8, radius: 100, explosionDamage: 26, triggerRange: 70, explodeOnDeath: true },
    telegraph: { time: 0.8, color: '#eaffb0' },
  },
  {
    id: 'enemy_bourgeon',
    name: 'Bourgeon',
    archetype: 'summoner',
    desc: "Libère des moucherons par paquets de 3, jusqu'à 6, et les soigne d'une pulsation toutes les 3 s. À abattre en premier.",
    hp: 110,
    speed: 65,
    damage: 8,
    radius: 20,
    xp: 24,
    coins: 6,
    color: '#ff9adb',
    sprite: 'enemy_summoner2',
    behavior: { variant: 'soigne', summon: 'enemy_moucherons', every: 3.5, max: 6, count: 3, keepDistance: 360, summonWindup: 0.6 },
    telegraph: { time: 0.6, color: '#ffc4ea' },
  },
  {
    id: 'enemy_moucherons',
    name: 'Moucherons',
    archetype: 'swarm',
    desc: 'Nuée de 5, plus rapide, qui vole : les obstacles ne les arrêtent pas.',
    hp: 10,
    speed: 300,
    damage: 5,
    radius: 8,
    xp: 3,
    coins: 1,
    color: '#9cff57',
    sprite: 'enemy_swarm2',
    behavior: { variant: 'vol', groupSize: 5, jitter: 45, biteWindup: 0.2, biteCooldown: 0.7 },
    telegraph: { time: 0.2, color: '#d0ff9a' },
  },
  {
    id: 'enemy_liane',
    name: 'Liane',
    archetype: 'dasher',
    desc: 'Fonce plus loin, plus souvent, et sa course laisse un fouet au sol pendant une seconde.',
    hp: 55,
    speed: 190,
    damage: 13,
    radius: 14,
    xp: 12,
    coins: 4,
    color: '#66e0c8',
    sprite: 'enemy_dasher2',
    behavior: {
      variant: 'fouet',
      blinkRange: 300,
      blinkWindup: 0.4,
      blinkCooldown: 1.7,
      dashSpeed: 780,
      dashDuration: 0.32,
      postDashPause: 0.5,
    },
    telegraph: { time: 0.4, color: '#a8fff0' },
  }
);

CONTENT.bosses.push({
  id: 'boss_serriste',
  name: 'Étalon 12, dite « la Serriste »',
  subtitle: 'Elle a fait pousser ce que tu portes.',
  desc: "La gardienne de LA SERRE, greffée jusqu'à l'os de matériel végétal. Vaporise, enracine, et charge quand on la croit lente : après une charge, ses racines mettent 1,2 s à se rétracter.",
  hp: 2600,
  speed: 130,
  radius: 36,
  damage: 20,
  xp: 180,
  coins: 60,
  color: '#7ed957',
  sprite: 'boss2',
  crest: 'crown',
  phases: [
    {
      hpBelow: 1,
      patterns: [
        {
          kind: 'spiral',
          telegraph: 0.7,
          duration: 2.6,
          cooldown: 4.5,
          arms: 3,
          rate: 14,
          angularSpeed: 2.4,
          projSpeed: 230,
          projDamage: 12,
          projSize: 7,
          color: '#b7ff7a',
        },
        { kind: 'summon', telegraph: 0.8, duration: 0.5, cooldown: 8, enemy: 'enemy_spore', count: 2 },
        { kind: 'charge', telegraph: 0.8, duration: 0.8, cooldown: 4.5, speed: 680, damage: 24, stunTime: 1.2 },
        { kind: 'roots', telegraph: 0.9, duration: 0.6, cooldown: 6, count: 3, radius: 62, dps: 10, color: '#7ed957', label: 'RONCES' },
      ],
    },
    {
      hpBelow: 0.55,
      patterns: [
        {
          kind: 'fan',
          telegraph: 0.5,
          duration: 0.6,
          cooldown: 2.2,
          count: 9,
          spread: 1.4,
          projSpeed: 320,
          projDamage: 13,
          projSize: 8,
          color: '#e2c6ff',
        },
        { kind: 'laser_sweep', telegraph: 1.0, duration: 2.2, cooldown: 7, length: 700, damage: 22, color: '#b7ff7a' },
        { kind: 'charge', telegraph: 0.6, duration: 0.8, cooldown: 4, speed: 760, damage: 26, stunTime: 1.2 },
        {
          kind: 'ring',
          telegraph: 0.6,
          duration: 0.3,
          cooldown: 3,
          count: 16,
          projSpeed: 280,
          projDamage: 13,
          projSize: 8,
          color: '#b7ff7a',
        },
        { kind: 'summon', telegraph: 0.8, duration: 0.5, cooldown: 9, enemy: 'enemy_moucherons', count: 1 },
        { kind: 'roots', telegraph: 0.7, duration: 0.6, cooldown: 5, count: 4, radius: 66, dps: 12, color: '#b7ff7a', label: 'RONCES' },
      ],
    },
  ],
  weakness: {
    desc: "Après chaque charge, ses racines restent plantées 1,2 s : dégâts ×1,8 pendant qu'elle se rétracte.",
    rule: 'after_charge',
    damageMul: 1.8,
    window: 1.2,
  },
  revenge: {
    hpMul: 1.35,
    window: 0.8,
    name: 'Étalon 12 / rév. B',
    phaseText: 'DONNÉES CHARGÉES',
    mimic: true,
    /* chantier 9 : ses propres phases — ronces et spores d'abord, le laser et la charge ensuite */
    phases: [
      {
        hpBelow: 1,
        patterns: [
          { kind: 'roots', telegraph: 0.8, duration: 0.6, cooldown: 4.5, count: 4, radius: 66, dps: 12, color: '#7ed957', label: 'RONCES' },
          {
            kind: 'spiral',
            telegraph: 0.7,
            duration: 2.4,
            cooldown: 4.5,
            arms: 2,
            rate: 12,
            angularSpeed: -2.2,
            projSpeed: 240,
            projDamage: 14,
            projSize: 7,
            color: '#b7ff7a',
          },
          {
            kind: 'mines',
            telegraph: 0.9,
            duration: 0.5,
            cooldown: 5.5,
            count: 4,
            spread: 160,
            radius: 64,
            fuse: 1.6,
            damage: 22,
            color: '#b7ff7a',
            label: 'SPORES',
          },
        ],
      },
      {
        hpBelow: 0.55,
        patterns: [
          { kind: 'laser_sweep', telegraph: 1.0, duration: 2.4, cooldown: 6.5, angularSpeed: 1.5, length: 700, damage: 16 },
          {
            kind: 'fan',
            telegraph: 0.5,
            duration: 0.6,
            cooldown: 2.2,
            count: 9,
            spread: 1.5,
            projSpeed: 300,
            projDamage: 16,
            projSize: 8,
            color: '#b7ff7a',
          },
          { kind: 'summon', telegraph: 0.8, duration: 0.5, cooldown: 7, enemy: 'enemy_moucherons', count: 1 },
          { kind: 'slam', telegraph: 1.0, duration: 0.4, cooldown: 5.0, radius: 150, damage: 26, knockback: 3.0 },
        ],
      },
    ],
    extraPhases: [
      {
        hpBelow: 0.3,
        patterns: [
          {
            kind: 'ring',
            telegraph: 0.5,
            duration: 1.2,
            cooldown: 2.5,
            count: 14,
            rate: 3,
            rotate: 0.35,
            projSpeed: 300,
            projDamage: 15,
            projSize: 8,
            color: '#b7ff7a',
          },
          {
            kind: 'spiral',
            telegraph: 0.6,
            duration: 3,
            cooldown: 5,
            arms: 4,
            rate: 16,
            angularSpeed: 3,
            projSpeed: 250,
            projDamage: 13,
            projSize: 7,
            color: '#e2c6ff',
          },
          { kind: 'charge', telegraph: 0.45, duration: 0.7, cooldown: 3, speed: 860, damage: 30, stunTime: 0.8 },
        ],
      },
    ],
    desc: 'Salle 9 : rév. B, PV ×1,35, rétraction plus courte (0,8 s), phase 3 sous 30 %.',
  },
});

/* Salles du biome 2 : mêmes types que le biome 1, plus d'ennemis, des élites, pièges plus serrés. */
/* Les pièges de la Serre (chantier 12, séance A) : les mêmes mécaniques que ceux de l'hôpital, mais des plantes — un nom,
   une couleur et un mot à elles. La salle du tempo les annonce par leur nom. */
CONTENT.traps.push(
  {
    id: 'trap_lianes',
    name: 'Lianes',
    kind: 'laser_rotate',
    color: '#7ed957',
    desc: 'Trois lianes tournent autour de la souche ; elles marquent une pause toutes les 6 s.',
    damage: 13,
    telegraph: 1,
    period: 6,
    active: 5,
    params: { arms: 3, lengthTiles: 5, angularSpeed: 1.1, startAngle: 0, thickness: 0.4 },
  },
  {
    id: 'trap_epines',
    name: 'Épines',
    kind: 'spike_tiles',
    color: '#b7ff7a',
    desc: "Des dalles d'où sortent des épines, une case sur deux, en rythme.",
    damage: 11,
    telegraph: 0.5,
    period: 2.6,
    active: 0.8,
    params: { pattern: 'checker', groups: 2, hitOnce: true },
  },
  {
    id: 'trap_spores',
    name: 'Spores',
    kind: 'gas_zone',
    color: '#c9a3ff',
    desc: "Un nuage de spores qui ralentit et ronge tant qu'on reste dedans.",
    damage: 9,
    telegraph: 1.2,
    period: 7,
    active: 3,
    params: { radiusTiles: 2.5, tickRate: 4, slow: 0.3, dps: true },
  },
  {
    id: 'trap_seve',
    name: 'Sève brûlante',
    kind: 'wall_fireball',
    color: '#ffd166',
    desc: 'Une plante murale crache une goutte de sève brûlante.',
    damage: 13,
    telegraph: 0.6,
    period: 2.5,
    active: 0.2,
    params: { dir: 'down', projSpeed: 320, size: 12, count: 1, lifetime: 3 },
  },
  {
    id: 'trap_arroseur',
    name: 'Arroseur',
    kind: 'laser_sweep',
    color: '#9fd8ff',
    desc: "Un jet d'eau glacée balaie les rangs de gauche à droite, puis revient.",
    damage: 14,
    telegraph: 0.8,
    period: 5,
    active: 1.6,
    params: { orientation: 'vertical', pingpong: true, thickness: 0.5, hitOnce: true },
  },
  {
    id: 'trap_treillis',
    name: 'Treillis',
    kind: 'laser_grid',
    color: '#5fb870',
    desc: "Un treillis de tiges coupantes s'allume une ligne sur deux.",
    damage: 11,
    telegraph: 0.5,
    period: 3,
    active: 1,
    params: { spacingTiles: 4, alternate: true, thickness: 0.3 },
  },
  {
    id: 'trap_cracheuse',
    name: 'Plante cracheuse',
    kind: 'turret_fixed',
    color: '#7ed957',
    desc: 'Une plante murale qui te vise et crache un noyau.',
    damage: 10,
    telegraph: 0.7,
    period: 2.4,
    active: 0.3,
    params: { mode: 'aim', angle: 0, projSpeed: 380, count: 1, spread: 0, projSize: 6 },
  },
  {
    id: 'trap_brumisateur',
    name: 'Brumisateur',
    kind: 'emitter',
    color: '#8fd8d0',
    desc: 'Un brumisateur qui lâche une couronne de gouttes glacées.',
    damage: 11,
    telegraph: 0.7,
    period: 3,
    active: 0.3,
    params: { pattern: 'ring', count: 8, arc: 6.2832, speed: 210, size: 7, lifetime: 4 },
  },
  {
    id: 'trap_lampe_uv',
    name: 'Lampe de culture',
    kind: 'laser_beam',
    color: '#c9a3ff',
    desc: 'Une lampe de culture qui grille tout ce qui passe sous son rayon.',
    damage: 16,
    telegraph: 0.6,
    period: 3,
    active: 1,
    params: { angle: 0, length: 26, thickness: 0.4 },
  },
  {
    id: 'trap_tondeuse',
    name: 'Tondeuse',
    kind: 'saw_rail',
    color: '#b7ff7a',
    desc: 'Une tondeuse folle fait des allers-retours sur son rail.',
    damage: 20,
    telegraph: 0.4,
    period: 3.2,
    active: 3.2,
    params: { axis: 'x', lengthTiles: 8, speedTiles: 6, pingpong: true, radiusTiles: 0.6, hitOnce: true },
  }
);

CONTENT.rooms.push(
  /* Plan « la rivière » : deux bras d'eau, trois passages secs. Rien n'est interdit, tout est taxé —
     le pont est sûr mais prévisible, le gué est libre mais coûte 28 % de vitesse. */
  {
    id: 'room_b2_1',
    biome: 'biome_2',
    index: 1,
    type: 'PREP_COMBAT',
    refTime: 62,
    terrain: [
      '........~~~....~~.......',
      '........~~~....~~.......',
      '........~~~....~~.......',
      '........===....~~.......',
      '........~~~....~~.......',
      '........~~~....~~.......',
      '........~~~....==.......',
      '........~~~....~~.......',
      '........~~~....~~.......',
      '........===....~~.......',
      '........~~~....~~.......',
      '........~~~....~~.......',
      '........~~~....~~.......',
    ],
    obstacles: [
      { x: 5, y: 2, w: 1, h: 2, kind: 'tree' },
      { x: 18, y: 2, w: 1, h: 2, kind: 'treep' },
      { x: 5, y: 9, w: 1, h: 2, kind: 'treep' },
      { x: 18, y: 9, w: 1, h: 2, kind: 'tree' },
      { x: 11, y: 6, w: 2, h: 1, kind: 'fountain' },
    ],
    anims: [
      {
        kind: 'mover',
        x: 9,
        y: 3,
        params: {
          sprite: 'butterfly',
          scale: 0.7,
          path: [
            [6, 2],
            [9, 1],
            [12, 3],
            [9, 5],
            [6, 4],
            [9, 3],
          ],
        },
        beats: { bars: 1, hits: [0], active: 1.6 },
      },
      {
        kind: 'light',
        x: 1,
        y: 1,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#7ed957' },
        beats: { bars: 1, hits: [0], active: 2 },
      },
      {
        kind: 'light',
        x: 21,
        y: 10,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#ffd166' },
        beats: { bars: 1, hits: [2], active: 2 },
      },
    ],
    deco: [
      { x: 3, y: 3, kind: 'flowers' },
      { x: 20, y: 10, kind: 'flowers' },
      { x: 12, y: 9, kind: 'shrooms' },
      { x: 4, y: 11, kind: 'smallrock' },
      { x: 20, y: 0, kind: 'leaf', big: true },
      { x: 14, y: 8, kind: 'mushroom' },
      { x: 6, y: 0, kind: 'flowers' },
      { x: 13, y: 3, kind: 'sprout' },
      { x: 19, y: 7, kind: 'flowers' },
      { x: 17, y: 4, kind: 'flowers' },
      { x: 17, y: 11, kind: 'sprout' },
      { x: 14, y: 1, kind: 'smallrock' },
      { x: 18, y: 8, kind: 'flowers' },
      { x: 7, y: 7, kind: 'shrooms' },
      { x: 3, y: 1, kind: 'mossypot' },
      { x: 11, y: 10, kind: 'flowers' },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_ronce', count: 2, x: 20, y: 3 },
          { enemy: 'enemy_ronce', count: 2, x: 20, y: 9 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_ronce', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_pollinisateur', count: 1, x: 21, y: 6 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_spore', count: 2, x: 21, y: 2 },
          { enemy: 'enemy_pollinisateur', count: 2, x: 21, y: 10 },
          { enemy: 'enemy_ronce', count: 2, x: 2, y: 1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_ronce', count: 1, x: -1, y: -1, elite: true },
          { enemy: 'enemy_liane', count: 1, x: 12, y: 1 },
          { enemy: 'enemy_ronce', count: 2, x: 2, y: 11 },
          { enemy: 'enemy_pollinisateur', count: 1, x: 21, y: 6 },
        ],
      },
    ],
    traps: [],
    fragments: [],
    modular: [],
  },
  {
    id: 'room_b2_3',
    biome: 'biome_2',
    index: 3,
    type: 'COMBAT_CHALLENGE',
    chest: true, // coffre offert en fin de salle (chantier 9)
    refTime: 75,
    obstacles: [
      { x: 6, y: 4, w: 1, h: 1, kind: 'flask' },
      { x: 17, y: 4, w: 1, h: 1, kind: 'flask' },
      { x: 6, y: 8, w: 1, h: 1, kind: 'flask' },
      { x: 17, y: 8, w: 1, h: 1, kind: 'flask' },
    ],
    deco: [
      { x: 4, y: 2, kind: 'flowers' },
      { x: 17, y: 2, kind: 'flowers' },
      { x: 4, y: 10, kind: 'shrooms' },
      { x: 17, y: 10, kind: 'flowers' },
      { x: 12, y: 6, kind: 'mushroom' },
      { x: 11, y: 11, kind: 'sprout', big: true },
      { x: 19, y: 2, kind: 'sprout', big: true },
      { x: 3, y: 5, kind: 'flowers' },
      { x: 18, y: 6, kind: 'leaf' },
      { x: 14, y: 1, kind: 'smallrock' },
      { x: 12, y: 8, kind: 'smallrock' },
      { x: 13, y: 12, kind: 'pot' },
      { x: 16, y: 1, kind: 'sprout' },
      { x: 4, y: 8, kind: 'sprout' },
      { x: 11, y: 7, kind: 'seedling' },
      { x: 7, y: 6, kind: 'sprout' },
      { x: 6, y: 11, kind: 'flowers' },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_ronce', count: 3, x: 20, y: 4 },
          { enemy: 'enemy_pollinisateur', count: 1, x: 21, y: 8 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_spore', count: 2, x: 21, y: 2 },
          { enemy: 'enemy_ronce', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_liane', count: 1, x: 2, y: 11 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_pollinisateur', count: 2, x: 21, y: 6 },
          { enemy: 'enemy_ronce', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_moucherons', count: 1, x: 12, y: 1 },
        ],
      },
    ],
    traps: [],
    fragments: [],
    modular: [],
  },
  {
    id: 'room_b2_2',
    biome: 'biome_2',
    index: 2,
    type: 'COMBAT_TRAP',
    refTime: 85,
    obstacles: [
      { x: 5, y: 3, w: 1, h: 1, kind: 'roundbush' },
      { x: 5, y: 9, w: 1, h: 1, kind: 'roundbush' },
      { x: 8, y: 3, w: 1, h: 1, kind: 'roundbush' },
      { x: 8, y: 9, w: 1, h: 1, kind: 'roundbush' },
      { x: 11, y: 3, w: 1, h: 1, kind: 'roundbush' },
      { x: 11, y: 9, w: 1, h: 1, kind: 'roundbush' },
      { x: 14, y: 3, w: 1, h: 1, kind: 'roundbush' },
      { x: 14, y: 9, w: 1, h: 1, kind: 'roundbush' },
      { x: 17, y: 3, w: 1, h: 1, kind: 'roundbush' },
      { x: 17, y: 9, w: 1, h: 1, kind: 'roundbush' },
    ],
    deco: [
      { x: 2, y: 6, kind: 'leaf' },
      { x: 21, y: 11, kind: 'pot' },
      { x: 12, y: 6, kind: 'sprout' },
      { x: 10, y: 7, kind: 'mushroom' },
      { x: 5, y: 0, kind: 'mossypot', big: true },
      { x: 19, y: 0, kind: 'seedling' },
      { x: 7, y: 12, kind: 'pot' },
      { x: 16, y: 6, kind: 'flowers' },
      { x: 11, y: 4, kind: 'flowers' },
      { x: 17, y: 7, kind: 'shrooms' },
      { x: 8, y: 7, kind: 'seedling', big: true },
      { x: 3, y: 4, kind: 'flowers' },
      { x: 20, y: 2, kind: 'flowers' },
      { x: 15, y: 8, kind: 'flowers' },
      { x: 12, y: 1, kind: 'shrooms' },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_ronce', count: 4, x: 20, y: 6 },
          { enemy: 'enemy_pollinisateur', count: 2, x: 21, y: 2 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_racine', count: 1, x: 21, y: 6 },
          { enemy: 'enemy_ronce', count: 4, x: -1, y: -1 },
          { enemy: 'enemy_spore', count: 2, x: 2, y: 11 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_spore', count: 3, x: 2, y: 1 },
          { enemy: 'enemy_pollinisateur', count: 3, x: 21, y: 10 },
          { enemy: 'enemy_moucherons', count: 1, x: 21, y: 2 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_liane', count: 2, x: 21, y: 6 },
          { enemy: 'enemy_ronce', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_racine', count: 1, x: 12, y: 10, elite: true },
        ],
      },
    ],
    traps: [
      { trap: 'trap_arroseur', x: 4, y: 0, w: 16, h: 13, phase: 0 },
      { trap: 'trap_cracheuse', x: 7, y: 0, phase: 0 },
      { trap: 'trap_cracheuse', x: 16, y: 12, phase: 1.2 },
    ],
    fragments: [],
    modular: [],
  },
  {
    id: 'room_b2_5',
    biome: 'biome_2',
    index: 5,
    type: 'MINIBOSS',
    refTime: 130,
    obstacles: [
      { x: 5, y: 3, w: 2, h: 2, kind: 'stump' },
      { x: 17, y: 3, w: 2, h: 2, kind: 'stump' },
      { x: 5, y: 8, w: 2, h: 2, kind: 'stump' },
      { x: 17, y: 8, w: 2, h: 2, kind: 'stump' },
      { x: 11, y: 6, w: 2, h: 1, kind: 'trap_plant' },
    ],
    deco: [
      { x: 3, y: 1, kind: 'flowers' },
      { x: 20, y: 11, kind: 'shrooms' },
      { x: 12, y: 2, kind: 'smallrock' },
      { x: 14, y: 5, kind: 'smallrock' },
      { x: 11, y: 10, kind: 'pot' },
      { x: 6, y: 6, kind: 'mushroom' },
      { x: 9, y: 3, kind: 'sprout' },
      { x: 20, y: 1, kind: 'flowers' },
      { x: 14, y: 2, kind: 'seedling' },
      { x: 3, y: 12, kind: 'mossypot' },
      { x: 17, y: 5, kind: 'pot' },
      { x: 8, y: 8, kind: 'mossypot' },
      { x: 9, y: 9, kind: 'leaf' },
      { x: 4, y: 9, kind: 'mossypot' },
      { x: 5, y: 7, kind: 'seedling' },
    ],
    waves: [{ at: 'start', spawns: [{ enemy: 'boss_serriste', count: 1, x: 18, y: 6 }] }],
    traps: [
      { trap: 'trap_spores', x: 3, y: 6, phase: 3 },
      { trap: 'trap_spores', x: 20, y: 6, phase: 7 },
    ],
    fragments: [],
    modular: [],
  },
  {
    id: 'room_b2_4',
    biome: 'biome_2',
    index: 4,
    type: 'COMBAT_MODULAR',
    refTime: 90,
    obstacles: [{ x: 11, y: 5, w: 2, h: 3, kind: 'fountain' }],
    anims: [
      { kind: 'bouncer', x: 3, y: 2, params: { sprite: 'bubbling-flask', amp: 10 }, beats: { bars: 1, hits: [0, 2], active: 0.8 } },
      { kind: 'bouncer', x: 20, y: 10, params: { sprite: 'bubbling-flask', amp: 10 }, beats: { bars: 1, hits: [1, 3], active: 0.8 } },
    ],
    deco: [
      { x: 2, y: 2, kind: 'smallrock' },
      { x: 21, y: 11, kind: 'mossypot' },
      { x: 12, y: 1, kind: 'flowers' },
      { x: 20, y: 2, kind: 'seedling' },
      { x: 5, y: 1, kind: 'flowers' },
      { x: 17, y: 11, kind: 'flowers' },
      { x: 15, y: 11, kind: 'flowers' },
      { x: 9, y: 1, kind: 'pot' },
      { x: 13, y: 12, kind: 'leaf' },
      { x: 8, y: 10, kind: 'flowers' },
      { x: 17, y: 2, kind: 'mushroom' },
      { x: 12, y: 4, kind: 'flowers', big: true },
      { x: 10, y: 12, kind: 'flowers', big: true },
      { x: 4, y: 11, kind: 'seedling', big: true },
      { x: 16, y: 1, kind: 'mushroom', big: true },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_liane', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_pollinisateur', count: 3, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_bourgeon', count: 1, x: 21, y: 6 },
          { enemy: 'enemy_ronce', count: 5, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_racine', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_spore', count: 4, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_liane', count: 2, x: -1, y: -1, elite: true },
          { enemy: 'enemy_pollinisateur', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_moucherons', count: 2, x: -1, y: -1 },
        ],
      },
    ],
    traps: [
      { trap: 'trap_cracheuse', x: 0, y: 3, phase: 0 },
      { trap: 'trap_cracheuse', x: 23, y: 9, phase: 1 },
    ],
    fragments: [],
    modular: [
      /* la Serre : deux rotors de lianes qui tournent en sens inverse, et un sol de racines qui change de dessin */
      { kind: 'rotor', cx: 7, cy: 6.5, arms: 2, length: 3, angularSpeed: 0.6 },
      { kind: 'rotor', cx: 17, cy: 6.5, arms: 2, length: 3, angularSpeed: -0.6 },
      {
        kind: 'floor_cycle',
        period: 9,
        telegraph: 1.5,
        configs: [
          [
            { x: 11, y: 2, w: 2, h: 1 },
            { x: 11, y: 10, w: 2, h: 1 },
          ],
          [{ x: 11, y: 5, w: 2, h: 3 }],
        ],
      },
    ],
  },
  {
    id: 'room_b2_6',
    biome: 'biome_2',
    index: 6,
    type: 'COMBAT_TEMPO',
    refTime: 105,
    obstacles: [
      { x: 5, y: 3, w: 1, h: 1, kind: 'planter' },
      { x: 18, y: 3, w: 1, h: 1, kind: 'planter' },
      { x: 5, y: 9, w: 1, h: 1, kind: 'planter' },
      { x: 18, y: 9, w: 1, h: 1, kind: 'planter' },
    ],
    deco: [
      { x: 15, y: 9, kind: 'leaf' },
      { x: 8, y: 10, kind: 'mossypot' },
      { x: 9, y: 7, kind: 'flowers' },
      { x: 14, y: 6, kind: 'flowers' },
      { x: 10, y: 2, kind: 'pot' },
      { x: 16, y: 6, kind: 'pot', big: true },
      { x: 15, y: 12, kind: 'mossypot' },
      { x: 11, y: 9, kind: 'shrooms', big: true },
      { x: 16, y: 4, kind: 'shrooms', big: true },
      { x: 10, y: 11, kind: 'mossypot', big: true },
      { x: 17, y: 0, kind: 'flowers', big: true },
      { x: 18, y: 12, kind: 'seedling', big: true },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_ronce', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_pollinisateur', count: 2, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_spore', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_liane', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_pollinisateur', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_moucherons', count: 1, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_pollinisateur', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_ronce', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_spore', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_liane', count: 1, x: -1, y: -1 },
          { enemy: 'enemy_racine', count: 1, x: 21, y: 6 },
        ],
      },
    ],
    traps: [
      { trap: 'trap_epines', x: 2, y: 2, w: 4, h: 3, params: { beats: { period: 4, active: 0.5, telegraph: 1, on: 0 } } },
      { trap: 'trap_epines', x: 18, y: 8, w: 4, h: 3, params: { beats: { period: 4, active: 0.5, telegraph: 1, on: 0 } } },
      { trap: 'trap_epines', x: 18, y: 2, w: 4, h: 3, params: { beats: { period: 4, active: 0.5, telegraph: 1, on: 2 } } },
      { trap: 'trap_epines', x: 2, y: 8, w: 4, h: 3, params: { beats: { period: 4, active: 0.5, telegraph: 1, on: 2 } } },
      { trap: 'trap_brumisateur', x: 11, y: 6, params: { beats: { every: 4, telegraph: 1, on: 2 } } },
      { trap: 'trap_seve', x: 11, y: 0, params: { dir: 'down', pattern: 'fan', count: 3, beats: { every: 8, telegraph: 1, on: 1 } } },
      { trap: 'trap_seve', x: 12, y: 12, params: { dir: 'up', pattern: 'fan', count: 3, beats: { every: 8, telegraph: 1, on: 5 } } },
      { trap: 'trap_lianes', x: 4, y: 6, params: { beats: { turn: 8, period: 8, active: 6, telegraph: 2, on: 0 } } },
      { trap: 'trap_spores', x: 19, y: 6, params: { beats: { period: 8, active: 2, telegraph: 2, on: 0 } } },
      { trap: 'trap_cracheuse', x: 0, y: 10, params: { beats: { every: 8, telegraph: 1, on: 3 } } },
      { trap: 'trap_cracheuse', x: 23, y: 2, params: { beats: { every: 8, telegraph: 1, on: 7 } } },
    ],
    fragments: [],
    modular: [],
  },
  {
    id: 'room_b2_9',
    biome: 'biome_2',
    index: 9,
    type: 'BOSS_REVENGE',
    refTime: 160,
    obstacles: [
      { x: 5, y: 3, w: 2, h: 2, kind: 'bigrock' },
      { x: 17, y: 3, w: 2, h: 2, kind: 'stump' },
      { x: 5, y: 8, w: 2, h: 2, kind: 'stump' },
      { x: 17, y: 8, w: 2, h: 2, kind: 'bigrock' },
    ],
    anims: [
      {
        kind: 'light',
        x: 1,
        y: 1,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#ffd166' },
        beats: { bars: 2, hits: [0], active: 4 },
      },
      {
        kind: 'light',
        x: 21,
        y: 1,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#ffd166' },
        beats: { bars: 2, hits: [0], active: 4 },
      },
      {
        kind: 'light',
        x: 1,
        y: 10,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#ffd166' },
        beats: { bars: 2, hits: [2], active: 4 },
      },
      {
        kind: 'light',
        x: 21,
        y: 10,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#ffd166' },
        beats: { bars: 2, hits: [2], active: 4 },
      },
    ],
    deco: [
      { x: 2, y: 1, kind: 'flowers' },
      { x: 21, y: 11, kind: 'mossypot' },
      { x: 12, y: 1, kind: 'shrooms' },
      { x: 12, y: 11, kind: 'smallrock' },
      { x: 3, y: 10, kind: 'mossypot' },
      { x: 12, y: 7, kind: 'flowers' },
      { x: 14, y: 1, kind: 'seedling' },
      { x: 15, y: 9, kind: 'mossypot' },
      { x: 7, y: 0, kind: 'flowers' },
      { x: 19, y: 4, kind: 'leaf' },
      { x: 18, y: 0, kind: 'pot', big: true },
      { x: 4, y: 4, kind: 'mossypot' },
      { x: 15, y: 2, kind: 'mossypot', big: true },
      { x: 20, y: 12, kind: 'seedling' },
      { x: 17, y: 5, kind: 'leaf' },
      { x: 9, y: 10, kind: 'pot' },
    ],
    waves: [{ at: 'start', spawns: [{ enemy: 'boss_serriste', count: 1, x: 18, y: 6 }] }],
    traps: [
      { trap: 'trap_cracheuse', x: 11, y: 0, phase: 0 },
      { trap: 'trap_cracheuse', x: 12, y: 12, phase: 1.2 },
      { trap: 'trap_spores', x: 3, y: 6, phase: 4 },
      { trap: 'trap_spores', x: 20, y: 6, phase: 8 },
    ],
    fragments: [],
    modular: [],
  },
  // ---------- SALLE 7 : COMBAT + PIÈGES + MODULAIRE ----------
  {
    id: 'room_b2_7',
    biome: 'biome_2',
    index: 7,
    type: 'COMBAT_TRAP_MODULAR',
    chest: true, // coffre offert en fin de salle (chantier 9)
    refTime: 90,
    obstacles: [
      { x: 2, y: 2, w: 1, h: 1, kind: 'roundbush' },
      { x: 21, y: 2, w: 1, h: 1, kind: 'roundbush' },
      { x: 2, y: 10, w: 1, h: 1, kind: 'roundbush' },
      { x: 21, y: 10, w: 1, h: 1, kind: 'roundbush' },
    ],
    deco: [
      { x: 6, y: 6, kind: 'shrooms' },
      { x: 17, y: 6, kind: 'mossypot' },
      { x: 12, y: 1, kind: 'flowers' },
      { x: 18, y: 8, kind: 'smallrock', big: true },
      { x: 4, y: 2, kind: 'leaf' },
      { x: 6, y: 12, kind: 'leaf' },
      { x: 5, y: 0, kind: 'mushroom' },
      { x: 19, y: 12, kind: 'leaf' },
      { x: 17, y: 10, kind: 'flowers', big: true },
      { x: 4, y: 12, kind: 'pot' },
      { x: 10, y: 3, kind: 'mushroom' },
      { x: 12, y: 12, kind: 'leaf', big: true },
      { x: 18, y: 2, kind: 'shrooms' },
      { x: 18, y: 4, kind: 'shrooms' },
      { x: 9, y: 12, kind: 'pot' },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_ronce', count: 3, x: 20, y: 6 },
          { enemy: 'enemy_pollinisateur', count: 1, x: 20, y: 3 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_spore', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_liane', count: 1, x: 20, y: 9 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_bourgeon', count: 1, x: 21, y: 6 },
          { enemy: 'enemy_ronce', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_pollinisateur', count: 2, x: 3, y: 10 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_liane', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_moucherons', count: 1, x: 20, y: 3 },
          { enemy: 'enemy_racine', count: 1, x: 21, y: 6 },
        ],
      },
    ],
    traps: [
      { trap: 'trap_cracheuse', x: 8, y: 0, phase: 0 },
      { trap: 'trap_cracheuse', x: 15, y: 12, phase: 1.2 },
      { trap: 'trap_spores', x: 12, y: 3, phase: 0 },
      { trap: 'trap_spores', x: 12, y: 9, phase: 1 },
    ],
    fragments: [],
    modular: [{ kind: 'slide_wall', x: 3, y: 6, w: 3, h: 1, dx: 15, dy: 0, period: 10, phase: 0, look: 'vines' }],
  },
  // ---------- SALLE 8 : LE PONT (unique à la Serre) — une passerelle de trois tuiles entre deux bassins, pris des deux côtés ----------
  {
    id: 'room_b2_8',
    biome: 'biome_2',
    index: 8,
    type: 'PONT',
    refTime: 85,
    /* deux bassins et une passerelle de trois tuiles : l'eau se traverse, mais à 72 % de la vitesse — on y est une cible */
    obstacles: [{ x: 11, y: 6, w: 1, h: 1, kind: 'fountain' }],
    deco: [],
    anims: [
      { kind: 'bouncer', x: 4, y: 2, params: { sprite: 'frog', amp: 14, scale: 0.8 }, beats: { bars: 1, hits: [0], active: 0.6 } },
      { kind: 'bouncer', x: 19, y: 10, params: { sprite: 'frog', amp: 14, scale: 0.8 }, beats: { bars: 1, hits: [2], active: 0.6 } },
      { kind: 'bouncer', x: 4, y: 10, params: { sprite: 'frog', amp: 14, scale: 0.8 }, beats: { bars: 2, hits: [1], active: 0.6 } },
    ],
    terrain: [
      '...~~~~~~~~~~~~~~~~~~...',
      '...~~~~~~~~~~~~~~~~~~...',
      '...~~~~~~~~~~~~~~~~~~...',
      '...~~~~~~~~~~~~~~~~~~...',
      '...~~~~~~~~~~~~~~~~~~...',
      '...==================...',
      '...==================...',
      '...==================...',
      '...~~~~~~~~~~~~~~~~~~...',
      '...~~~~~~~~~~~~~~~~~~...',
      '...~~~~~~~~~~~~~~~~~~...',
      '...~~~~~~~~~~~~~~~~~~...',
      '...~~~~~~~~~~~~~~~~~~...',
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_ronce', count: 3, x: 20, y: 6 },
          { enemy: 'enemy_pollinisateur', count: 2, x: 21, y: 5 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_racine', count: 1, x: 21, y: 6 },
          { enemy: 'enemy_spore', count: 3, x: 2, y: 7 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_liane', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_moucherons', count: 2, x: 21, y: 7 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_bourgeon', count: 1, x: 21, y: 6 },
          { enemy: 'enemy_ronce', count: 4, x: -1, y: -1 },
          { enemy: 'enemy_pollinisateur', count: 2, x: 2, y: 5 },
        ],
      },
    ],
    traps: [
      { trap: 'trap_cracheuse', x: 11, y: 0, phase: 0 },
      { trap: 'trap_cracheuse', x: 12, y: 12, phase: 1.2 },
    ],
    fragments: [],
    modular: [],
  }
);
