/* =========================================================================
   WAY — content4.js — Biome 4 : LE SÉRAIL (niveau 4, oriental). Un palais-bazar enseveli sous les dunes.
   Derviches, archers, colosses d'argile, jarres de naphte, charmeurs, cobras, djinns ; boss « le Vizir ».
   Décor : colonnes, jarres, fontaines, palmiers, braseros, tentures (icônes game-icons.net rastérisées, voir Sprites.props).
   ========================================================================= */

'use strict';
CONTENT.biomes.push({
  id: 'biome_4',
  name: 'LE SÉRAIL',
  order: 4,
  tagline: 'Un palais enseveli sous les dunes : derviches, djinns, naphte et sable qui traverse les salles. Le niveau des tenaces.',
  desc: "Niveau 4. Le sérail au bout de la piste : cour aux fontaines taries, bazar figé, colonnes cassées. Le sable est entré par les fenêtres et n'est jamais ressorti. Taux de perte : 96 %.",
  palette: {
    tint: 'rgba(72,50,140,.30)',
    neon: ['#ffd166', '#8f6ad8'],
    wall: 'rgba(84,58,145,.42)',
    terrain: { ledge: { fill: '#3a2f52', edge: '#e2d3ae' }, screen: { fill: '#241d38', edge: '#c9a05a' } },
  },
  levelPassives: [
    {
      bonus: {
        name: 'Pas du derviche',
        desc: '+12 % vitesse, +10 % de réduction de recharge.',
        mods: [
          { stat: 'speed', mul: 1.12 },
          { stat: 'cooldownReduction', add: 0.1 },
        ],
        hooks: {},
      },
      malus: {
        name: 'Sable dans les yeux',
        desc: '-30 % rayon de ramassage, -10 % portée.',
        mods: [
          { stat: 'pickupRadius', mul: 0.7 },
          { stat: 'range', mul: 0.9 },
        ],
        hooks: {},
      },
    },
    {
      bonus: { name: 'Trésor du bazar', desc: '+70 % pièces.', mods: [{ stat: 'coinGain', mul: 1.7 }], hooks: {} },
      malus: { name: 'Dette du marchand', desc: '-20 % PV max.', mods: [{ stat: 'maxHp', mul: 0.8 }], hooks: {} },
    },
    {
      bonus: { name: 'Vœu du djinn', desc: '+20 % dégâts.', mods: [{ stat: 'damage', mul: 1.2 }], hooks: {} },
      malus: { name: 'Prix du vœu', desc: '-30 % de puissance de compétence.', mods: [{ stat: 'skillPower', mul: 0.7 }], hooks: {} },
    },
  ],
  enemyPool: ['enemy_derviche', 'enemy_archer', 'enemy_colosse', 'enemy_jarre', 'enemy_charmeur', 'enemy_cobras', 'enemy_djinn'],
  trapPool: [
    'trap_sabres',
    'trap_brasero',
    'trap_meurtriere',
    'trap_encens',
    'trap_pieux',
    'trap_naphte',
    'trap_moucharabieh',
    'trap_braises',
    'trap_derviche',
    'trap_rai',
  ],
  miniboss: 'boss_vizir',
  difficulty: { hpMul: 1.62, damageMul: 1.34, speedMul: 1.12 },
  unlockAfter: 'biome_3',
});

CONTENT.enemies.push(
  {
    id: 'enemy_derviche',
    name: 'Derviche',
    archetype: 'rusher',
    desc: 'Tourne sur lui-même puis fond sur toi, lames tendues. À la moitié de ses PV il se dédouble, une fois.',
    hp: 62,
    speed: 250,
    damage: 14,
    radius: 14,
    xp: 8,
    coins: 3,
    color: '#ffd166',
    sprite: 'enemy_rusher4',
    behavior: { variant: 'dedouble', lungeRange: 140, lungeWindup: 0.26, lungeSpeed: 680, lungeDuration: 0.3, lungeCooldown: 1.15 },
    telegraph: { time: 0.26, color: '#ffe8a8' },
  },
  {
    id: 'enemy_archer',
    name: 'Archer du sérail',
    archetype: 'shooter',
    desc: 'Tire en cloche : la flèche passe par-dessus les colonnes et retombe là où tu étais, dans le cercle annoncé. Bouge.',
    hp: 52,
    speed: 155,
    damage: 10,
    radius: 14,
    xp: 11,
    coins: 4,
    color: '#5ad6cc',
    projColor: '#a8f0e8',
    sprite: 'enemy_shooter4',
    behavior: {
      variant: 'cloche',
      fireRate: 1.35,
      projSpeed: 430,
      projDamage: 10,
      projSize: 6,
      keepDistance: 350,
      aimTime: 0.45,
      burst: 1,
      count: 2,
      spread: 0.3,
    },
    telegraph: { time: 0.45, color: '#a8f0e8' },
  },
  {
    id: 'enemy_colosse',
    name: "Colosse d'argile",
    archetype: 'tank',
    desc: 'Statue de terre cuite : de face, sa pierre encaisse moitié moins. Frappe-le de dos, ou quand il est sonné contre un mur.',
    hp: 360,
    speed: 92,
    damage: 20,
    radius: 28,
    xp: 26,
    coins: 7,
    color: '#c67440',
    sprite: 'enemy_tank4',
    behavior: {
      variant: 'bouclier',
      chargeRange: 400,
      chargeWindup: 0.65,
      chargeSpeed: 700,
      chargeDuration: 0.95,
      chargeCooldown: 2.5,
      stunOnWallHit: 1.1,
      chargeDamageMul: 1.6,
    },
    telegraph: { time: 0.65, color: '#ffb347' },
  },
  {
    id: 'enemy_jarre',
    name: 'Jarre de naphte',
    archetype: 'kamikaze',
    desc: "Roule vers toi et s'ouvre en nappe de feu, qui brûle 3 s au sol. Éclate aussi quand on la brise.",
    hp: 30,
    speed: 260,
    damage: 7,
    radius: 13,
    xp: 8,
    coins: 2,
    color: '#ff8c42',
    sprite: 'enemy_kamikaze4',
    behavior: { variant: 'nappe', fuse: 0.7, radius: 110, explosionDamage: 34, triggerRange: 74, explodeOnDeath: true },
    telegraph: { time: 0.7, color: '#ffb347' },
  },
  {
    id: 'enemy_charmeur',
    name: 'Charmeur',
    archetype: 'summoner',
    desc: "Reste au loin, joue de la flûte : les cobras sortent par paquets de 3, et toutes les 6 s sa musique t'attire vers lui d'un coup.",
    hp: 140,
    speed: 72,
    damage: 9,
    radius: 20,
    xp: 30,
    coins: 8,
    color: '#9a7aff',
    sprite: 'enemy_summoner4',
    behavior: { variant: 'charme', summon: 'enemy_cobras', every: 3.0, max: 6, count: 3, keepDistance: 390, summonWindup: 0.6 },
    telegraph: { time: 0.6, color: '#c9a3ff' },
  },
  {
    id: 'enemy_cobras',
    name: 'Cobras',
    archetype: 'swarm',
    desc: 'Nuée de 5 : ils crachent de loin, puis mordent.',
    hp: 13,
    speed: 320,
    damage: 7,
    radius: 8,
    xp: 4,
    coins: 1,
    color: '#3aa06a',
    sprite: 'enemy_swarm4',
    behavior: { variant: 'crachat', groupSize: 5, jitter: 55, biteWindup: 0.17, biteCooldown: 0.6 },
    telegraph: { time: 0.17, color: '#7ed957' },
  },
  {
    id: 'enemy_djinn',
    name: 'Djinn de poussière',
    archetype: 'dasher',
    desc: 'Se dissout, réapparaît dans ton dos et te traverse. Longue pause après.',
    hp: 70,
    speed: 190,
    damage: 17,
    radius: 15,
    xp: 15,
    coins: 5,
    color: '#9a7aff',
    sprite: 'enemy_dasher4',
    behavior: {
      variant: 'dos',
      blinkRange: 340,
      blinkWindup: 0.42,
      blinkCooldown: 1.5,
      dashSpeed: 860,
      dashDuration: 0.3,
      postDashPause: 0.6,
    },
    telegraph: { time: 0.42, color: '#c9a3ff' },
  }
);

CONTENT.traps.push(
  {
    id: 'trap_sabres',
    name: 'Roue à sabres',
    kind: 'laser_rotate',
    desc: '4 lames de 5 tuiles tournent (1,28 rad/s). Pause de 1 s toutes les 6 s.',
    damage: 15,
    telegraph: 1.0,
    period: 6.0,
    active: 5.0,
    color: '#d8dce8',
    params: { arms: 4, lengthTiles: 5, angularSpeed: 1.28, startAngle: 0.4, thickness: 0.42 },
  },
  {
    id: 'trap_brasero',
    name: 'Braséro roulant',
    kind: 'saw_rail',
    desc: 'Brasier sur rail qui fait des allers-retours sur 8 tuiles à 6 tuiles/s.',
    damage: 23,
    telegraph: 0.4,
    period: 3.2,
    active: 3.2,
    color: '#ff9a3c',
    params: { axis: 'x', lengthTiles: 8, speedTiles: 6, pingpong: true, radiusTiles: 0.65, hitOnce: true },
  },
  {
    id: 'trap_meurtriere',
    name: 'Meurtrière',
    kind: 'turret_fixed',
    desc: 'Depuis le mur : 0,7 s de visée puis une flèche vers toi toutes les 2 s.',
    damage: 12,
    telegraph: 0.7,
    period: 2.0,
    active: 0.3,
    color: '#a8f0e8',
    params: { mode: 'aim', angle: 0, projSpeed: 430, count: 1, spread: 0, projSize: 6 },
  },
  {
    id: 'trap_encens',
    name: 'Encens narcotique',
    kind: 'gas_zone',
    desc: 'Un brûle-parfum siffle 1,2 s puis lâche une fumée épaisse 3 s : 11 dégâts/s et -35 % vitesse.',
    damage: 11,
    telegraph: 1.2,
    period: 7.0,
    active: 3.0,
    color: '#c9a3ff',
    params: { radiusTiles: 2.5, tickRate: 4, slow: 0.35, dps: true },
  },
  {
    id: 'trap_pieux',
    name: 'Dalles à pieux',
    kind: 'spike_tiles',
    desc: 'Mosaïque piégée : les dalles paires sortent 0,8 s, puis les impaires.',
    damage: 13,
    telegraph: 0.5,
    period: 2.5,
    active: 0.8,
    color: '#e2d3ae',
    params: { pattern: 'checker', groups: 2, hitOnce: true },
  },
  {
    id: 'trap_naphte',
    name: 'Jarre de naphte',
    kind: 'wall_fireball',
    desc: 'Une jarre enflammée est lancée tout droit toutes les 2,4 s.',
    damage: 16,
    telegraph: 0.6,
    period: 2.4,
    active: 0.2,
    color: '#ff8c42',
    params: { dir: 'down', projSpeed: 340, size: 12, count: 1, lifetime: 3.0 },
  },
  {
    id: 'trap_braises',
    name: 'Lanterne à braises',
    kind: 'emitter',
    desc: "Une lanterne suspendue crache une couronne de braises tout autour d'elle.",
    damage: 12,
    telegraph: 0.7,
    period: 3.0,
    active: 0.3,
    color: '#ff9a3c',
    params: { pattern: 'ring', count: 8, arc: 6.2832, speed: 200, size: 7, lifetime: 4 },
  },
  {
    id: 'trap_derviche',
    name: 'Derviche de lames',
    kind: 'emitter',
    desc: "Quatre lames lancées en croix, qui pivotent d'un seizième de tour à chaque salve.",
    damage: 11,
    telegraph: 0.6,
    period: 2.0,
    active: 0.3,
    color: '#d8dce8',
    params: { pattern: 'spiral', count: 4, arc: 6.2832, spin: 0.3927, speed: 240, size: 6, lifetime: 5 },
  },
  {
    id: 'trap_rai',
    name: 'Rai de soleil',
    kind: 'laser_beam',
    desc: 'Un rai brûlant traverse la salle depuis la meurtrière, allumé en mesure.',
    damage: 16,
    telegraph: 0.6,
    period: 3.0,
    active: 1.0,
    color: '#ffd166',
    params: { angle: 0, length: 26, thickness: 0.4 },
  },
  {
    id: 'trap_moucharabieh',
    name: 'Moucharabieh',
    kind: 'laser_grid',
    desc: 'Le soleil passe par les claustras : rais brûlants tous les 4 tuiles, alternés. 1 s allumés, 2 s éteints.',
    damage: 13,
    telegraph: 0.5,
    period: 3.0,
    active: 1.0,
    color: '#ffd166',
    params: { spacingTiles: 4, alternate: true, thickness: 0.3 },
  }
);

CONTENT.bosses.push({
  id: 'boss_vizir',
  name: 'Étalon 27, dit « le Vizir »',
  subtitle: "Il t'a vu entrer. Les trois autres aussi.",
  desc: "Le maître du sérail. Il ne court pas : il se déplace en laissant des doubles, appelle le sable et regarde. Quand le mirage retombe, il n'en reste qu'un — c'est là qu'il faut frapper.",
  hp: 3200,
  speed: 128,
  radius: 34,
  damage: 24,
  xp: 260,
  coins: 95,
  color: '#c9a3ff',
  projColor: '#ffd166',
  sprite: 'boss4',
  crest: 'lamp',
  crestOver: true,
  crestDy: -22,
  phases: [
    {
      hpBelow: 1,
      patterns: [
        {
          kind: 'fan',
          telegraph: 0.55,
          duration: 0.5,
          cooldown: 2.3,
          count: 7,
          spread: 1.0,
          projSpeed: 390,
          projDamage: 16,
          projSize: 7,
          color: '#ffd166',
          label: 'CIMETERRES',
        },
        {
          kind: 'sandstorm',
          telegraph: 1.5,
          duration: 4,
          cooldown: 6.5,
          speed: 420,
          thickness: 46,
          gap: 140,
          damage: 26,
          label: 'TEMPÊTE',
        },
        {
          kind: 'mirage',
          telegraph: 0.7,
          duration: 1.4,
          cooldown: 6,
          count: 3,
          spread: 230,
          hold: 0.85,
          bullets: 3,
          arc: 0.5,
          projSpeed: 340,
          projDamage: 15,
          projSize: 7,
          color: '#ffd166',
          label: 'MIRAGE',
        },
      ],
    },
    {
      hpBelow: 0.55,
      patterns: [
        {
          kind: 'ring',
          telegraph: 0.55,
          duration: 0.3,
          cooldown: 2.8,
          count: 14,
          projSpeed: 310,
          projDamage: 15,
          projSize: 8,
          color: '#ffd166',
          label: 'ANNEAU',
        },
        {
          kind: 'sandstorm',
          telegraph: 1.2,
          duration: 4,
          cooldown: 5.5,
          speed: 500,
          thickness: 52,
          gap: 120,
          damage: 28,
          label: 'TEMPÊTE',
        },
        {
          kind: 'mirage',
          telegraph: 0.6,
          duration: 1.4,
          cooldown: 5,
          count: 4,
          spread: 250,
          hold: 0.75,
          bullets: 3,
          arc: 0.6,
          projSpeed: 370,
          projDamage: 16,
          projSize: 7,
          color: '#ffd166',
          label: 'MIRAGE',
        },
        {
          kind: 'spiral',
          telegraph: 0.5,
          duration: 2.2,
          cooldown: 4,
          arms: 2,
          rate: 13,
          angularSpeed: 2.4,
          projSpeed: 270,
          projDamage: 14,
          projSize: 7,
          color: '#c9a3ff',
          label: 'SABLIER',
        },
        {
          kind: 'fan',
          telegraph: 0.45,
          duration: 0.5,
          cooldown: 2.1,
          count: 9,
          spread: 1.4,
          projSpeed: 410,
          projDamage: 15,
          projSize: 7,
          color: '#ffd166',
          label: 'CIMETERRES',
        },
      ],
    },
  ],
  weakness: {
    desc: 'Quand le mirage retombe, le vrai reste seul et à découvert : dégâts ×1,8 pendant 2,2 s.',
    rule: 'after_mirage',
    damageMul: 1.8,
    window: 2.2,
  },
  revenge: {
    hpMul: 1.4,
    window: 1.6,
    name: 'Étalon 27 / rév. B',
    phaseText: 'DONNÉES CHARGÉES',
    mimic: true,
    /* chantier 9 : ses propres phases — les mirages d'abord, la tempête et la spirale ensuite */
    phases: [
      {
        hpBelow: 1,
        patterns: [
          {
            kind: 'mirage',
            telegraph: 0.7,
            duration: 1.4,
            cooldown: 5.5,
            count: 4,
            spread: 240,
            hold: 0.85,
            bullets: 3,
            arc: 0.5,
            projSpeed: 340,
            projDamage: 16,
            projSize: 7,
          },
          { kind: 'ring', telegraph: 0.6, duration: 0.3, cooldown: 3.0, count: 14, projSpeed: 300, projDamage: 16, projSize: 8 },
          { kind: 'slam', telegraph: 1.0, duration: 0.4, cooldown: 5.0, radius: 150, damage: 26, knockback: 3.0 },
        ],
      },
      {
        hpBelow: 0.55,
        patterns: [
          {
            kind: 'sandstorm',
            telegraph: 1.2,
            duration: 4,
            cooldown: 6.0,
            speed: 480,
            thickness: 50,
            gap: 130,
            damage: 26,
            label: 'TEMPÊTE',
          },
          {
            kind: 'spiral',
            telegraph: 0.6,
            duration: 2.6,
            cooldown: 4.5,
            arms: 3,
            rate: 13,
            angularSpeed: 2.3,
            projSpeed: 240,
            projDamage: 15,
            projSize: 7,
          },
          { kind: 'charge', telegraph: 0.8, duration: 0.8, cooldown: 4.5, speed: 700, damage: 28, stopOnWall: true, stunTime: 1.2 },
          { kind: 'summon', telegraph: 0.8, duration: 0.5, cooldown: 7, enemy: 'enemy_cobras', count: 1 },
        ],
      },
    ],
    extraPhases: [
      {
        hpBelow: 0.3,
        patterns: [
          {
            kind: 'sandstorm',
            telegraph: 0.9,
            duration: 4,
            cooldown: 4.5,
            speed: 620,
            thickness: 58,
            gap: 105,
            damage: 32,
            label: 'TEMPÊTE',
          },
          {
            kind: 'mirage',
            telegraph: 0.5,
            duration: 1.3,
            cooldown: 4,
            count: 5,
            spread: 260,
            hold: 0.65,
            bullets: 4,
            arc: 0.8,
            projSpeed: 400,
            projDamage: 17,
            projSize: 7,
            color: '#ffd166',
            label: 'MIRAGE',
          },
          {
            kind: 'spiral',
            telegraph: 0.5,
            duration: 3,
            cooldown: 4.5,
            arms: 3,
            rate: 15,
            angularSpeed: 2.8,
            projSpeed: 290,
            projDamage: 15,
            projSize: 7,
            color: '#c9a3ff',
            label: 'SABLIER',
          },
          {
            kind: 'ring',
            telegraph: 0.45,
            duration: 1.2,
            cooldown: 2.4,
            count: 16,
            rate: 3,
            rotate: 0.3,
            projSpeed: 330,
            projDamage: 17,
            projSize: 8,
            color: '#ffd166',
          },
        ],
      },
    ],
    desc: 'Salle 9 : rév. B, PV ×1,4, fenêtre de faiblesse plus courte (1,6 s), phase 3 sous 30 %.',
  },
});

/* Salles du biome 4. Obstacles avec `kind` : column, jar, vase, basin, palm, basket, brazier, drapes, archway (Sprites.drawBlock). */
CONTENT.rooms.push(
  {
    id: 'room_b4_1',
    biome: 'biome_4',
    index: 1,
    type: 'PREP_COMBAT',
    refTime: 65,
    obstacles: [
      { x: 5, y: 2, w: 1, h: 2, kind: 'column' },
      { x: 18, y: 2, w: 1, h: 2, kind: 'column' },
      { x: 5, y: 9, w: 1, h: 2, kind: 'column' },
      { x: 18, y: 9, w: 1, h: 2, kind: 'column' },
      { x: 11, y: 6, w: 2, h: 1, kind: 'basin' },
    ],
    anims: [
      {
        kind: 'light',
        x: 1,
        y: 1,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#ffd166' },
        beats: { bars: 1, hits: [0], active: 2 },
      },
      {
        kind: 'light',
        x: 21,
        y: 1,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#8f6ad8' },
        beats: { bars: 1, hits: [2], active: 2 },
      },
      {
        kind: 'light',
        x: 1,
        y: 10,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#8f6ad8' },
        beats: { bars: 1, hits: [2], active: 2 },
      },
      {
        kind: 'light',
        x: 21,
        y: 10,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#ffd166' },
        beats: { bars: 1, hits: [0], active: 2 },
      },
    ],
    deco: [
      { x: 3, y: 6, kind: 'carpet' },
      { x: 7, y: 6, kind: 'carpet' },
      { x: 15, y: 6, kind: 'carpet' },
      { x: 19, y: 6, kind: 'carpet' },
      { x: 5, y: 1, kind: 'lantern' },
      { x: 18, y: 11, kind: 'lantern' },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_derviche', count: 2, x: 20, y: 3 },
          { enemy: 'enemy_derviche', count: 2, x: 20, y: 9 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_derviche', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_archer', count: 1, x: 21, y: 6 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_jarre', count: 2, x: 21, y: 2 },
          { enemy: 'enemy_archer', count: 2, x: 21, y: 10 },
          { enemy: 'enemy_derviche', count: 2, x: 2, y: 1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_derviche', count: 1, x: -1, y: -1, elite: true },
          { enemy: 'enemy_djinn', count: 1, x: 12, y: 1 },
          { enemy: 'enemy_derviche', count: 2, x: 2, y: 11 },
          { enemy: 'enemy_archer', count: 1, x: 21, y: 6 },
        ],
      },
    ],
    traps: [],
    fragments: [],
    modular: [],
  },
  {
    id: 'room_b4_2',
    biome: 'biome_4',
    index: 2,
    type: 'COMBAT_CHALLENGE',
    refTime: 85,
    obstacles: [
      { x: 6, y: 4, w: 1, h: 1, kind: 'jar' },
      { x: 17, y: 4, w: 1, h: 1, kind: 'jar' },
      { x: 6, y: 8, w: 1, h: 1, kind: 'vase' },
      { x: 17, y: 8, w: 1, h: 1, kind: 'vase' },
    ],
    deco: [
      { x: 3, y: 2, kind: 'lantern' },
      { x: 20, y: 10, kind: 'lantern' },
      { x: 12, y: 10, kind: 'spices' },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_derviche', count: 3, x: 20, y: 4 },
          { enemy: 'enemy_archer', count: 1, x: 21, y: 8 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_jarre', count: 2, x: 21, y: 2 },
          { enemy: 'enemy_derviche', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_djinn', count: 1, x: 2, y: 11 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_archer', count: 2, x: 21, y: 6 },
          { enemy: 'enemy_derviche', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_cobras', count: 1, x: 12, y: 1 },
        ],
      },
    ],
    traps: [{ trap: 'trap_braises', x: 11, y: 6, phase: 0 }],
    fragments: [],
    modular: [],
  },
  /* Plan « les terrasses » : deux murets à brèches décalées (les balles passent, pas toi) et deux moucharabiehs
     (la vue ne passe pas, tout le reste si). Le combat ne s'interrompt jamais, mais chaque déplacement demande
     un détour — ou un dash, qui franchit les murets. */
  {
    id: 'room_b4_4',
    biome: 'biome_4',
    index: 4,
    type: 'COMBAT_TRAP',
    refTime: 108,
    terrain: [
      '........................',
      '.......n...::...n.......',
      '.......n...::...n.......',
      '...........::...n.......',
      '.......n................',
      '.......n........n.......',
      '.......n........n.......',
      '.......n........n.......',
      '.......n................',
      '...........::...n.......',
      '.......n...::...n.......',
      '.......n...::...n.......',
      '........................',
    ],
    obstacles: [
      { x: 4, y: 3, w: 2, h: 1, kind: 'basket' },
      { x: 4, y: 9, w: 2, h: 1, kind: 'basket' },
      { x: 18, y: 3, w: 1, h: 2, kind: 'palm' },
      { x: 18, y: 8, w: 1, h: 2, kind: 'palm' },
    ],
    deco: [],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_derviche', count: 4, x: 20, y: 6 },
          { enemy: 'enemy_archer', count: 2, x: 21, y: 2 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_colosse', count: 1, x: 21, y: 6 },
          { enemy: 'enemy_derviche', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_jarre', count: 2, x: 2, y: 11 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_jarre', count: 3, x: 2, y: 1 },
          { enemy: 'enemy_archer', count: 3, x: 21, y: 10 },
          { enemy: 'enemy_cobras', count: 1, x: 21, y: 2 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_djinn', count: 2, x: 21, y: 6 },
          { enemy: 'enemy_derviche', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_colosse', count: 1, x: 12, y: 11 },
        ],
      },
    ],
    traps: [
      { trap: 'trap_sabres', x: 11, y: 6, params: { beats: { turn: 4, period: 8, active: 6, telegraph: 2, on: 0 } } },
      { trap: 'trap_pieux', x: 1, y: 1, w: 3, h: 3, phase: 0 },
      { trap: 'trap_pieux', x: 20, y: 9, w: 3, h: 3, phase: 1 },
      { trap: 'trap_meurtriere', x: 7, y: 0, phase: 0 },
      { trap: 'trap_meurtriere', x: 16, y: 12, phase: 1.2 },
      { trap: 'trap_rai', x: 11, y: 0, phase: 0, params: { angle: 1.5708 } },
    ],
    fragments: [],
    modular: [],
  },
  {
    id: 'room_b4_5',
    biome: 'biome_4',
    index: 5,
    type: 'MINIBOSS',
    refTime: 150,
    obstacles: [
      { x: 5, y: 3, w: 1, h: 2, kind: 'brazier' },
      { x: 18, y: 3, w: 1, h: 2, kind: 'brazier' },
      { x: 5, y: 8, w: 1, h: 2, kind: 'brazier' },
      { x: 18, y: 8, w: 1, h: 2, kind: 'brazier' },
    ],
    anims: [
      {
        kind: 'light',
        x: 4,
        y: 2,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#ff9a3c' },
        beats: { bars: 1, hits: [0], active: 2 },
      },
      {
        kind: 'light',
        x: 19,
        y: 2,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#ff9a3c' },
        beats: { bars: 1, hits: [0], active: 2 },
      },
      {
        kind: 'light',
        x: 4,
        y: 9,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#ff9a3c' },
        beats: { bars: 1, hits: [0], active: 2 },
      },
      {
        kind: 'light',
        x: 19,
        y: 9,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#ff9a3c' },
        beats: { bars: 1, hits: [0], active: 2 },
      },
    ],
    deco: [
      { x: 2, y: 1, kind: 'mosque' },
      { x: 21, y: 11, kind: 'lamp' },
      { x: 12, y: 11, kind: 'carpet' },
    ],
    waves: [{ at: 'start', spawns: [{ enemy: 'boss_vizir', count: 1, x: 18, y: 6 }] }],
    traps: [
      { trap: 'trap_encens', x: 3, y: 6, phase: 3 },
      { trap: 'trap_encens', x: 20, y: 6, phase: 7 },
    ],
    fragments: [],
    modular: [],
  },
  {
    id: 'room_b4_3',
    biome: 'biome_4',
    index: 3,
    type: 'COMBAT_MODULAR',
    chest: true, // coffre offert en fin de salle (chantier 9)
    refTime: 100,
    obstacles: [{ x: 11, y: 5, w: 2, h: 3, kind: 'basin' }],
    deco: [
      { x: 2, y: 2, kind: 'teapot' },
      { x: 21, y: 10, kind: 'chalice' },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_djinn', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_archer', count: 3, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_charmeur', count: 1, x: 21, y: 6 },
          { enemy: 'enemy_derviche', count: 5, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_colosse', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_jarre', count: 4, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_djinn', count: 2, x: -1, y: -1, elite: true },
          { enemy: 'enemy_archer', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_cobras', count: 2, x: -1, y: -1 },
        ],
      },
    ],
    traps: [
      { trap: 'trap_meurtriere', x: 0, y: 3, phase: 0 },
      { trap: 'trap_meurtriere', x: 23, y: 9, phase: 1 },
    ],
    fragments: [],
    modular: [
      /* le Sérail : deux tentures qui coulissent en travers et un grand rotor à trois pales au centre */
      { kind: 'slide_wall', x: 3, y: 2, w: 4, h: 1, dx: 14, dy: 0, period: 9, phase: 0 },
      { kind: 'slide_wall', x: 17, y: 10, w: 4, h: 1, dx: -14, dy: 0, period: 9, phase: 4.5 },
      { kind: 'rotor', cx: 12, cy: 6.5, arms: 3, length: 4, angularSpeed: 0.5 },
    ],
  },
  {
    id: 'room_b4_7',
    biome: 'biome_4',
    index: 7,
    type: 'COMBAT_TEMPO',
    refTime: 115,
    obstacles: [
      { x: 5, y: 3, w: 1, h: 1, kind: 'brazier' },
      { x: 18, y: 3, w: 1, h: 1, kind: 'brazier' },
      { x: 5, y: 9, w: 1, h: 1, kind: 'brazier' },
      { x: 18, y: 9, w: 1, h: 1, kind: 'brazier' },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_derviche', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_archer', count: 2, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_jarre', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_djinn', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_archer', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_cobras', count: 1, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_archer', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_derviche', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_jarre', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_djinn', count: 1, x: -1, y: -1 },
          { enemy: 'enemy_colosse', count: 1, x: 21, y: 6 },
        ],
      },
    ],
    traps: [
      { trap: 'trap_pieux', x: 2, y: 2, w: 4, h: 3, params: { beats: { period: 4, active: 0.5, telegraph: 1, on: 0 } } },
      { trap: 'trap_pieux', x: 18, y: 8, w: 4, h: 3, params: { beats: { period: 4, active: 0.5, telegraph: 1, on: 0 } } },
      { trap: 'trap_pieux', x: 18, y: 2, w: 4, h: 3, params: { beats: { period: 4, active: 0.5, telegraph: 1, on: 2 } } },
      { trap: 'trap_pieux', x: 2, y: 8, w: 4, h: 3, params: { beats: { period: 4, active: 0.5, telegraph: 1, on: 2 } } },
      { trap: 'trap_derviche', x: 11, y: 6, params: { beats: { every: 4, telegraph: 1, on: 0 } } },
      { trap: 'trap_naphte', x: 11, y: 0, params: { dir: 'down', pattern: 'fan', count: 3, beats: { every: 8, telegraph: 1, on: 1 } } },
      { trap: 'trap_naphte', x: 12, y: 12, params: { dir: 'up', pattern: 'fan', count: 3, beats: { every: 8, telegraph: 1, on: 5 } } },
      { trap: 'trap_encens', x: 4, y: 6, params: { beats: { period: 8, active: 2, telegraph: 2, on: 4 } } },
      { trap: 'trap_encens', x: 19, y: 6, params: { beats: { period: 8, active: 2, telegraph: 2, on: 0 } } },
      { trap: 'trap_meurtriere', x: 0, y: 10, params: { beats: { every: 8, telegraph: 1, on: 3 } } },
      { trap: 'trap_meurtriere', x: 23, y: 2, params: { beats: { every: 8, telegraph: 1, on: 7 } } },
    ],
    fragments: [],
    modular: [],
  },
  {
    id: 'room_b4_9',
    biome: 'biome_4',
    index: 9,
    type: 'BOSS_REVENGE',
    refTime: 180,
    obstacles: [
      { x: 5, y: 3, w: 1, h: 2, kind: 'column' },
      { x: 18, y: 3, w: 1, h: 2, kind: 'column' },
      { x: 5, y: 8, w: 1, h: 2, kind: 'column' },
      { x: 18, y: 8, w: 1, h: 2, kind: 'column' },
    ],
    anims: [
      {
        kind: 'light',
        x: 1,
        y: 1,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#8f6ad8' },
        beats: { bars: 1, hits: [0], active: 2 },
      },
      {
        kind: 'light',
        x: 21,
        y: 1,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#8f6ad8' },
        beats: { bars: 1, hits: [2], active: 2 },
      },
      {
        kind: 'light',
        x: 1,
        y: 10,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#8f6ad8' },
        beats: { bars: 1, hits: [2], active: 2 },
      },
      {
        kind: 'light',
        x: 21,
        y: 10,
        w: 2,
        h: 2,
        params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#8f6ad8' },
        beats: { bars: 1, hits: [0], active: 2 },
      },
    ],
    deco: [
      { x: 2, y: 1, kind: 'mosque' },
      { x: 21, y: 11, kind: 'hourglass' },
      { x: 12, y: 1, kind: 'lantern' },
    ],
    waves: [{ at: 'start', spawns: [{ enemy: 'boss_vizir', count: 1, x: 18, y: 6 }] }],
    traps: [
      { trap: 'trap_meurtriere', x: 11, y: 0, phase: 0 },
      { trap: 'trap_meurtriere', x: 12, y: 12, phase: 1.2 },
      { trap: 'trap_rai', x: 0, y: 3, phase: 0 },
      { trap: 'trap_rai', x: 0, y: 9, phase: 1.5 },
    ],
    fragments: [],
    modular: [],
  },
  // ---------- SALLE 6 : LE BAZAR (unique au Sérail) — un damier d'étals, et le coffre caché derrière l'un d'eux ----------
  {
    id: 'room_b4_6',
    biome: 'biome_4',
    index: 6,
    type: 'BAZAR',
    chest: true, // coffre offert en fin de salle (chantier 9)
    chestHidden: true, // caché entre les étals
    refTime: 90,
    obstacles: [
      { x: 4, y: 2, w: 1, h: 1, kind: 'drapes' },
      { x: 7, y: 2, w: 1, h: 1, kind: 'drapes' },
      { x: 10, y: 2, w: 2, h: 1, kind: 'drapes' },
      { x: 13, y: 2, w: 1, h: 1, kind: 'drapes' },
      { x: 16, y: 2, w: 1, h: 1, kind: 'drapes' },
      { x: 19, y: 2, w: 1, h: 1, kind: 'drapes' },
      { x: 4, y: 4, w: 1, h: 1, kind: 'basket' },
      { x: 7, y: 4, w: 1, h: 1, kind: 'basket' },
      { x: 13, y: 4, w: 1, h: 1, kind: 'basket' },
      { x: 16, y: 4, w: 2, h: 1, kind: 'basket' },
      { x: 19, y: 4, w: 1, h: 1, kind: 'basket' },
      { x: 4, y: 8, w: 1, h: 1, kind: 'jar' },
      { x: 7, y: 8, w: 2, h: 1, kind: 'jar' },
      { x: 10, y: 8, w: 1, h: 1, kind: 'jar' },
      { x: 13, y: 8, w: 1, h: 1, kind: 'jar' },
      { x: 16, y: 8, w: 1, h: 1, kind: 'jar' },
      { x: 19, y: 8, w: 1, h: 1, kind: 'jar' },
      { x: 4, y: 10, w: 1, h: 1, kind: 'vase' },
      { x: 7, y: 10, w: 1, h: 1, kind: 'vase' },
      { x: 10, y: 10, w: 1, h: 1, kind: 'vase' },
      { x: 13, y: 10, w: 2, h: 1, kind: 'vase' },
      { x: 16, y: 10, w: 1, h: 1, kind: 'vase' },
      { x: 19, y: 10, w: 1, h: 1, kind: 'vase' },
    ],
    deco: [
      { x: 5, y: 3, kind: 'spices' },
      { x: 11, y: 3, kind: 'teapot' },
      { x: 17, y: 3, kind: 'gems' },
      { x: 6, y: 6, kind: 'lamp' },
      { x: 14, y: 6, kind: 'chalice' },
      { x: 9, y: 9, kind: 'incense' },
      { x: 18, y: 9, kind: 'gems' },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_cobras', count: 2, x: 20, y: 6 },
          { enemy: 'enemy_derviche', count: 2, x: 21, y: 3 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_charmeur', count: 1, x: 21, y: 9 },
          { enemy: 'enemy_derviche', count: 3, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_djinn', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_archer', count: 2, x: 21, y: 3 },
          { enemy: 'enemy_cobras', count: 1, x: 2, y: 9 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_jarre', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_derviche', count: 3, x: 21, y: 9 },
          { enemy: 'enemy_charmeur', count: 1, x: 21, y: 3 },
        ],
      },
    ],
    traps: [],
    fragments: [],
    modular: [],
  },
  // ---------- SALLE 8 : COMBAT + PIÈGES + MODULAIRE — la zone sûre du Site et un rotor ----------
  {
    id: 'room_b4_8',
    biome: 'biome_4',
    index: 8,
    type: 'COMBAT_TRAP_MODULAR',
    refTime: 95,
    obstacles: [
      { x: 2, y: 2, w: 1, h: 1, kind: 'brazier' },
      { x: 21, y: 2, w: 1, h: 1, kind: 'brazier' },
      { x: 2, y: 10, w: 1, h: 1, kind: 'brazier' },
      { x: 21, y: 10, w: 1, h: 1, kind: 'brazier' },
    ],
    deco: [
      { x: 12, y: 2, kind: 'lamp' },
      { x: 12, y: 10, kind: 'carpet' },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_colosse', count: 1, x: 21, y: 6 },
          { enemy: 'enemy_archer', count: 2, x: 20, y: 3 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_jarre', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_derviche', count: 3, x: 20, y: 9 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_charmeur', count: 1, x: 21, y: 6 },
          { enemy: 'enemy_djinn', count: 2, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_archer', count: 2, x: 3, y: 2 },
          { enemy: 'enemy_derviche', count: 4, x: -1, y: -1 },
          { enemy: 'enemy_cobras', count: 1, x: 20, y: 9 },
        ],
      },
    ],
    traps: [
      { trap: 'trap_meurtriere', x: 7, y: 0, phase: 0 },
      { trap: 'trap_meurtriere', x: 16, y: 12, phase: 1.2 },
      { trap: 'trap_brasero', x: 3, y: 1, w: 8, phase: 0 },
      { trap: 'trap_brasero', x: 13, y: 11, w: 8, phase: 1.6 },
    ],
    fragments: [],
    modular: [
      {
        kind: 'safe_zone',
        path: [
          { x: 6, y: 6 },
          { x: 18, y: 6 },
          { x: 12, y: 2 },
          { x: 12, y: 10 },
        ],
        radius: 3,
        period: 8,
        telegraph: 1.5,
        speed: 120,
        damage: 15,
      },
      { kind: 'rotor', cx: 12, cy: 6.5, arms: 2, length: 3, angularSpeed: 0.9 },
    ],
  }
);
