/* =========================================================================
   WAY — content3.js — Biome 3 : LA CONCESSION (niveau 3, western). Une mine abandonnée en plein désert.
   Coyotes, bandits, bisons, barils de poudre, croque-morts, scorpions, crotales ; boss « le Marshal ».
   Décor : cactus, rochers, tonneaux, caisses, chariots (icônes game-icons.net rastérisées en pixels, voir Sprites.props).
   ========================================================================= */

'use strict';
CONTENT.biomes.push({
  id: 'biome_3',
  name: 'LA CONCESSION',
  order: 3,
  tagline: 'Une mine abandonnée en plein désert : bandits, bêtes, dynamite et wagonnets fous. Le niveau des durs.',
  desc: 'Niveau 3. La concession minière au bout de la piste : rails rouillés, poudrière éventrée, saloon vide. Ce qui vit ici a appris à survivre au soleil et aux hommes. Taux de perte : 91 %.',
  palette: {
    tint: 'rgba(210,150,60,.30)',
    neon: ['#ffb347', '#ff6b3c'],
    wall: 'rgba(120,70,30,.42)',
    sand: true,
    terrain: { wall: { fill: '#2e2016', edge: '#9a8768' }, mud: { fill: '#c9a76a', edge: '#e8d4a0' } },
  },
  levelPassives: [
    {
      bonus: { name: 'Gâchette rapide', desc: '+15 % cadence de tir.', mods: [{ stat: 'fireRate', mul: 1.15 }], hooks: {} },
      malus: { name: 'Soleil de plomb', desc: '-15 % PV max.', mods: [{ stat: 'maxHp', mul: 0.85 }], hooks: {} },
    },
    {
      bonus: {
        name: 'Prime de chasse',
        desc: '+50 % pièces, +10 % XP.',
        mods: [
          { stat: 'coinGain', mul: 1.5 },
          { stat: 'xpGain', mul: 1.1 },
        ],
        hooks: {},
      },
      malus: {
        name: 'Sable mouvant',
        desc: 'Pièges +50 % de dégâts, -8 % vitesse.',
        mods: [
          { stat: 'trapDamageMul', mul: 1.5 },
          { stat: 'speed', mul: 0.92 },
        ],
        hooks: {},
      },
    },
    {
      bonus: { name: 'Sang-froid', desc: '+15 % dégâts.', mods: [{ stat: 'damage', mul: 1.15 }], hooks: {} },
      malus: { name: 'Fièvre', desc: 'Invulnérabilité après un coup -0,2 s.', mods: [{ stat: 'invulnTime', add: -0.2 }], hooks: {} },
    },
  ],
  enemyPool: ['enemy_coyote', 'enemy_bandit', 'enemy_bison', 'enemy_baril', 'enemy_croquemort', 'enemy_scorpions', 'enemy_crotale'],
  trapPool: [
    'trap_sablier',
    'trap_loup',
    'trap_tonneaux',
    'trap_fil',
    'trap_aiguillage',
    'trap_cloche',

    'trap_moulin',
    'trap_wagonnet',
    'trap_embuscade',
    'trap_poudre',
    'trap_ours',
    'trap_dynamite',
    'trap_barbeles',
    'trap_gatling',
    'trap_revolver',
    'trap_detente',
  ],
  miniboss: 'boss_marshal',
  difficulty: { hpMul: 1.45, damageMul: 1.28, speedMul: 1.1 },
  unlockAfter: 'biome_2',
});

CONTENT.enemies.push(
  {
    id: 'enemy_coyote',
    name: 'Coyote',
    archetype: 'rusher',
    desc: 'Chasse en meute, ruée courte et rapide. En tombant il laisse un piège à loup, qui mord le premier qui marche dessus.',
    hp: 52,
    speed: 235,
    damage: 12,
    radius: 14,
    xp: 7,
    coins: 2,
    color: '#d8a25a',
    sprite: 'enemy_rusher3',
    behavior: {
      variant: 'piege',
      drop: 'trap_loup',
      lungeRange: 120,
      lungeWindup: 0.28,
      lungeSpeed: 640,
      lungeDuration: 0.28,
      lungeCooldown: 1.1,
    },
    telegraph: { time: 0.28, color: '#ffd9a0' },
  },
  {
    id: 'enemy_bandit',
    name: 'Bandit',
    archetype: 'shooter',
    desc: 'Tire deux balles rapides puis court se mettre derrière l’obstacle le plus proche.',
    hp: 44,
    speed: 150,
    damage: 9,
    radius: 14,
    xp: 9,
    coins: 4,
    color: '#8a5a3a',
    projColor: '#ffe08a',
    sprite: 'enemy_shooter3',
    behavior: {
      variant: 'replis',
      fireRate: 0.9,
      projSpeed: 420,
      projDamage: 10,
      projSize: 6,
      keepDistance: 340,
      aimTime: 0.4,
      burst: 2,
      spread: 0.15,
    },
    telegraph: { time: 0.4, color: '#ffe08a' },
  },
  {
    id: 'enemy_bison',
    name: 'Bison',
    archetype: 'tank',
    desc: 'Charge de loin, très lourd. Contre un mur il est sonné 1 s, mais le choc secoue le sol tout autour : reste à plus de trois tuiles.',
    hp: 300,
    speed: 90,
    damage: 18,
    radius: 28,
    xp: 22,
    coins: 6,
    color: '#6b4a2a',
    sprite: 'enemy_tank3',
    behavior: {
      variant: 'secousse',
      chargeRange: 380,
      chargeWindup: 0.7,
      chargeSpeed: 680,
      chargeDuration: 0.9,
      chargeCooldown: 2.6,
      stunOnWallHit: 1.0,
      chargeDamageMul: 1.6,
    },
    telegraph: { time: 0.7, color: '#ffd166' },
  },
  {
    id: 'enemy_baril',
    name: 'Baril de poudre',
    archetype: 'kamikaze',
    desc: 'Roule en ligne droite, rebondit sur ce qu’il heurte et éclate au contact. Explose aussi quand on le tue.',
    hp: 26,
    speed: 250,
    damage: 6,
    radius: 13,
    xp: 7,
    coins: 2,
    color: '#a8402e',
    sprite: 'enemy_kamikaze3',
    behavior: { variant: 'roule', fuse: 0.75, radius: 105, explosionDamage: 30, triggerRange: 70, explodeOnDeath: true },
    telegraph: { time: 0.75, color: '#ff9a3c' },
  },
  {
    id: 'enemy_croquemort',
    name: 'Croque-mort',
    archetype: 'summoner',
    desc: "Reste loin et lâche des scorpions par paquets de 3. Quand un ennemi tombe près de lui, il le relève à moitié de ses PV au lieu d'invoquer.",
    hp: 120,
    speed: 70,
    damage: 8,
    radius: 20,
    xp: 26,
    coins: 7,
    color: '#2a2a3a',
    sprite: 'enemy_summoner3',
    behavior: { variant: 'releve', summon: 'enemy_scorpions', every: 3.2, max: 6, count: 3, keepDistance: 380, summonWindup: 0.6 },
    telegraph: { time: 0.6, color: '#c9a3ff' },
  },
  {
    id: 'enemy_scorpions',
    name: 'Scorpions',
    archetype: 'swarm',
    desc: 'Nuée de 5, piqûre rapide : le venin engourdit, on marche à 65 % pendant 1,5 s.',
    hp: 11,
    speed: 310,
    damage: 6,
    radius: 8,
    xp: 3,
    coins: 1,
    color: '#3a2a1a',
    sprite: 'enemy_swarm3',
    behavior: { variant: 'venin', groupSize: 5, jitter: 50, biteWindup: 0.18, biteCooldown: 0.65 },
    telegraph: { time: 0.18, color: '#ffb347' },
  },
  {
    id: 'enemy_crotale',
    name: 'Crotale',
    archetype: 'dasher',
    desc: "Sonne, puis fond sur toi d'un coup — une fois sur deux il surgit de côté, pas d'où il visait. Longue pause après.",
    hp: 60,
    speed: 180,
    damage: 15,
    radius: 14,
    xp: 13,
    coins: 4,
    color: '#9a9a3a',
    sprite: 'enemy_dasher3',
    behavior: {
      variant: 'feinte',
      blinkRange: 320,
      blinkWindup: 0.45,
      blinkCooldown: 1.6,
      dashSpeed: 820,
      dashDuration: 0.3,
      postDashPause: 0.6,
    },
    telegraph: { time: 0.45, color: '#e8ff8a' },
  }
);

CONTENT.traps.push(
  {
    id: 'trap_moulin',
    name: 'Moulin',
    kind: 'laser_rotate',
    desc: '3 pales de bois de 5 tuiles tournent (1,3 rad/s). Pause de 1 s tous les 6 s.',
    damage: 14,
    telegraph: 1.0,
    period: 6.0,
    active: 5.0,
    color: '#d8b46a',
    params: { arms: 3, lengthTiles: 5, angularSpeed: 1.3, startAngle: 0, thickness: 0.45 },
  },
  {
    id: 'trap_wagonnet',
    name: 'Wagonnet fou',
    kind: 'saw_rail',
    desc: 'Wagonnet de mine qui fait des allers-retours sur 8 tuiles de rails à 6 tuiles/s.',
    damage: 22,
    telegraph: 0.4,
    period: 3.2,
    active: 3.2,
    color: '#9a8a6a',
    params: { axis: 'x', lengthTiles: 8, speedTiles: 6, pingpong: true, radiusTiles: 0.65, hitOnce: true },
  },
  {
    id: 'trap_embuscade',
    name: 'Tireur embusqué',
    kind: 'turret_fixed',
    desc: 'Depuis le mur : 0,7 s de visée puis une balle vers toi toutes les 2,2 s.',
    damage: 11,
    telegraph: 0.7,
    period: 2.2,
    active: 0.3,
    color: '#ffe08a',
    params: { mode: 'aim', angle: 0, projSpeed: 400, count: 1, spread: 0, projSize: 6 },
  },
  {
    id: 'trap_poudre',
    name: 'Nuage de poudre',
    kind: 'gas_zone',
    desc: 'Une bouche siffle 1,2 s puis libère un nuage de poussière de poudre 3 s : 10 dégâts/s et -30 % vitesse.',
    damage: 10,
    telegraph: 1.2,
    period: 7.0,
    active: 3.0,
    color: '#d9c39a',
    params: { radiusTiles: 2.5, tickRate: 4, slow: 0.3, dps: true },
  },
  {
    id: 'trap_ours',
    name: 'Pièges à ours',
    kind: 'spike_tiles',
    desc: 'Damier de mâchoires : les cases paires claquent 0,8 s, puis les impaires.',
    damage: 12,
    telegraph: 0.5,
    period: 2.6,
    active: 0.8,
    color: '#c9c0b0',
    params: { pattern: 'checker', groups: 2, hitOnce: true },
  },
  {
    id: 'trap_dynamite',
    name: 'Dynamite',
    kind: 'wall_fireball',
    desc: 'Un bâton de dynamite est lancé tout droit toutes les 2,5 s.',
    damage: 15,
    telegraph: 0.6,
    period: 2.5,
    active: 0.2,
    color: '#ff6b3c',
    params: { dir: 'down', projSpeed: 330, size: 12, count: 1, lifetime: 3.0 },
  },
  {
    id: 'trap_gatling',
    name: 'Gatling',
    kind: 'emitter',
    desc: "Canon à barillet : 3 bras de balles qui pivotent d'un huitième de tour à chaque salve.",
    damage: 11,
    telegraph: 0.6,
    period: 2.0,
    active: 0.3,
    color: '#ffe08a',
    params: { pattern: 'spiral', count: 3, arc: 6.2832, spin: 0.7854, speed: 250, size: 6, lifetime: 5 },
  },
  {
    id: 'trap_revolver',
    name: 'Revolver',
    kind: 'emitter',
    desc: 'Trois coups dans ta direction, tirés coup sur coup en une demi-mesure.',
    damage: 9,
    telegraph: 0.7,
    period: 3.0,
    active: 0.3,
    color: '#ffd166',
    params: { pattern: 'aimed', count: 1, arc: 0.5, burst: 3, burstGap: 0.25, speed: 420, size: 5, lifetime: 4 },
  },
  {
    id: 'trap_detente',
    name: 'Fil de détente',
    kind: 'laser_beam',
    desc: 'Un fil tendu en travers de la salle, qui claque en rythme. On passe entre deux.',
    damage: 15,
    telegraph: 0.6,
    period: 3.0,
    active: 1.0,
    color: '#b0774a',
    params: { angle: 0, length: 26, thickness: 0.35 },
  },
  {
    id: 'trap_barbeles',
    name: 'Barbelés',
    kind: 'laser_grid',
    desc: 'Fils barbelés tendus tous les 4 tuiles, alternés. 1 s tendu, 2 s au sol.',
    damage: 12,
    telegraph: 0.5,
    period: 3.0,
    active: 1.0,
    color: '#b0774a',
    params: { spacingTiles: 4, alternate: true, thickness: 0.3 },
  }
);

CONTENT.bosses.push({
  id: 'boss_marshal',
  name: 'Étalon 19, dit « le Marshal »',
  subtitle: 'Il a nettoyé la concession. Il ne reste que toi.',
  desc: 'Le gardien de la mine. Six coups dans le barillet, une charge de bête et de la dynamite plein les poches. Quand il recharge, il est à toi.',
  hp: 3000,
  speed: 135,
  radius: 36,
  damage: 22,
  xp: 220,
  coins: 80,
  color: '#e0b060',
  sprite: 'boss3',
  crest: 'hat',
  phases: [
    {
      hpBelow: 1,
      patterns: [
        {
          kind: 'fan',
          telegraph: 0.6,
          duration: 0.5,
          cooldown: 2.4,
          count: 6,
          spread: 0.9,
          projSpeed: 380,
          projDamage: 16,
          projSize: 7,
          color: '#ffe08a',
          label: 'BARILLET',
        },
        { kind: 'charge', telegraph: 0.8, duration: 0.8, cooldown: 4.5, speed: 720, damage: 26, stunTime: 1.2, label: 'TACLE' },
        {
          kind: 'mines',
          telegraph: 0.9,
          duration: 0.5,
          cooldown: 5.5,
          count: 4,
          spread: 150,
          radius: 70,
          fuse: 1.6,
          damage: 26,
          color: '#ff6b3c',
          label: 'DYNAMITE',
        },
        { kind: 'summon', telegraph: 0.8, duration: 0.5, cooldown: 8, enemy: 'enemy_coyote', count: 2, label: 'MEUTE' },
      ],
    },
    {
      hpBelow: 0.55,
      patterns: [
        {
          kind: 'ring',
          telegraph: 0.6,
          duration: 0.3,
          cooldown: 3,
          count: 12,
          projSpeed: 300,
          projDamage: 15,
          projSize: 8,
          color: '#ffe08a',
          label: 'TIR EN ROND',
        },
        {
          kind: 'duel',
          telegraph: 1.4,
          duration: 1.6,
          cooldown: 6.5,
          projSpeed: 1000,
          projDamage: 30,
          projSize: 5,
          reload: 1.2,
          color: '#ffe08a',
          label: 'DUEL',
        },
        { kind: 'charge', telegraph: 0.6, duration: 0.8, cooldown: 4, speed: 800, damage: 28, stunTime: 1.2, label: 'TACLE' },
        {
          kind: 'fan',
          telegraph: 0.5,
          duration: 0.5,
          cooldown: 2.2,
          count: 8,
          spread: 1.3,
          projSpeed: 400,
          projDamage: 15,
          projSize: 7,
          color: '#ffe08a',
          label: 'BARILLET',
        },
        { kind: 'summon', telegraph: 0.8, duration: 0.5, cooldown: 9, enemy: 'enemy_baril', count: 2, label: 'POUDRE' },
        {
          kind: 'mines',
          telegraph: 0.7,
          duration: 0.5,
          cooldown: 4.5,
          count: 6,
          spread: 190,
          radius: 74,
          fuse: 1.4,
          damage: 28,
          color: '#ff6b3c',
          label: 'DYNAMITE',
        },
      ],
    },
  ],
  weakness: { desc: 'Après chaque attaque il recharge : dégâts ×1,8 pendant 1 s.', rule: 'during_reload', damageMul: 1.8, window: 1.0 },
  revenge: {
    hpMul: 1.35,
    window: 0.7,
    name: 'Étalon 19 / rév. B',
    phaseText: 'DONNÉES CHARGÉES',
    mimic: true,
    /* chantier 9 : ses propres phases — le duel d'abord, les mines et la spirale ensuite */
    phases: [
      {
        hpBelow: 1,
        patterns: [
          {
            kind: 'duel',
            telegraph: 1.3,
            duration: 1.6,
            cooldown: 6.0,
            projSpeed: 1000,
            projDamage: 30,
            projSize: 5,
            reload: 1.1,
            color: '#ffe08a',
            label: 'DUEL',
          },
          {
            kind: 'ring',
            telegraph: 0.6,
            duration: 0.3,
            cooldown: 3.0,
            count: 12,
            projSpeed: 300,
            projDamage: 16,
            projSize: 8,
            color: '#ffe08a',
          },
          { kind: 'charge', telegraph: 0.8, duration: 0.8, cooldown: 4.2, speed: 700, damage: 28, stopOnWall: true, stunTime: 1.3 },
        ],
      },
      {
        hpBelow: 0.55,
        patterns: [
          {
            kind: 'mines',
            telegraph: 0.9,
            duration: 0.5,
            cooldown: 5.0,
            count: 5,
            spread: 170,
            radius: 70,
            fuse: 1.5,
            damage: 26,
            color: '#ff6b3c',
          },
          {
            kind: 'spiral',
            telegraph: 0.6,
            duration: 2.6,
            cooldown: 4.8,
            arms: 3,
            rate: 13,
            angularSpeed: 2.2,
            projSpeed: 250,
            projDamage: 15,
            projSize: 7,
            color: '#ffe08a',
          },
          {
            kind: 'fan',
            telegraph: 0.5,
            duration: 0.5,
            cooldown: 2.0,
            count: 8,
            spread: 1.3,
            projSpeed: 320,
            projDamage: 18,
            projSize: 8,
            color: '#ffe08a',
          },
          {
            kind: 'quake',
            telegraph: 0.9,
            duration: 2.0,
            cooldown: 5.5,
            speed: 640,
            damage: 24,
            range: 900,
            color: '#ffe08a',
            label: 'RUÉE',
          },
        ],
      },
    ],
    extraPhases: [
      {
        hpBelow: 0.3,
        patterns: [
          {
            kind: 'spiral',
            telegraph: 0.6,
            duration: 3,
            cooldown: 5,
            arms: 3,
            rate: 14,
            angularSpeed: 2.6,
            projSpeed: 260,
            projDamage: 14,
            projSize: 7,
            color: '#ffe08a',
            label: 'MITRAILLE',
          },
          {
            kind: 'ring',
            telegraph: 0.5,
            duration: 1.2,
            cooldown: 2.5,
            count: 14,
            rate: 3,
            rotate: 0.35,
            projSpeed: 320,
            projDamage: 16,
            projSize: 8,
            color: '#ffe08a',
          },
          { kind: 'charge', telegraph: 0.45, duration: 0.7, cooldown: 3, speed: 900, damage: 32, stunTime: 0.8, label: 'TACLE' },
          {
            kind: 'duel',
            telegraph: 1.0,
            duration: 1.4,
            cooldown: 5,
            projSpeed: 1100,
            projDamage: 34,
            projSize: 5,
            reload: 0.9,
            color: '#ffe08a',
            label: 'DUEL',
          },
        ],
      },
    ],
    desc: 'Salle 9 : rév. B, PV ×1,35, recharge plus courte (0,7 s), phase 3 sous 30 %.',
  },
});

/* Salles du biome 3. Obstacles avec `kind` : cactus, rock, barrel, crate, wagon, cart, barrels, skull (dessinés par Sprites.drawBlock). */
CONTENT.rooms.push(
  {
    id: 'room_b3_1',
    biome: 'biome_3',
    index: 1,
    type: 'PREP_COMBAT',
    refTime: 60,
    obstacles: [
      { x: 5, y: 2, w: 1, h: 2, kind: 'saguaro' },
      { x: 18, y: 2, w: 1, h: 2, kind: 'saguaro' },
      { x: 5, y: 9, w: 1, h: 2, kind: 'saguaro' },
      { x: 18, y: 9, w: 1, h: 2, kind: 'saguaro' },
      { x: 11, y: 6, w: 2, h: 1, kind: 'wagon' },
    ],
    deco: [
      { x: 2, y: 11, kind: 'skull' },
      { x: 21, y: 1, kind: 'tumbleweed' },
      { x: 9, y: 1, kind: 'rails' },
      { x: 10, y: 1, kind: 'rails' },
      { x: 11, y: 1, kind: 'rails' },
      { x: 9, y: 5, kind: 'rails' },
      { x: 15, y: 5, kind: 'rails' },
      { x: 11, y: 10, kind: 'skull' },
      { x: 17, y: 6, kind: 'wanted' },
      { x: 15, y: 3, kind: 'tumbleweed' },
      { x: 10, y: 3, kind: 'tumbleweed', big: true },
      { x: 9, y: 12, kind: 'tumbleweed' },
      { x: 5, y: 6, kind: 'barrels' },
      { x: 19, y: 0, kind: 'tumbleweed' },
      { x: 12, y: 9, kind: 'wanted' },
      { x: 3, y: 5, kind: 'skullpile', big: true },
      { x: 7, y: 6, kind: 'barrels', big: true },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_coyote', count: 2, x: 20, y: 3 },
          { enemy: 'enemy_coyote', count: 2, x: 20, y: 9 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_coyote', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_bandit', count: 1, x: 21, y: 6 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_baril', count: 2, x: 21, y: 2 },
          { enemy: 'enemy_bandit', count: 2, x: 21, y: 10 },
          { enemy: 'enemy_coyote', count: 2, x: 2, y: 1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_coyote', count: 1, x: -1, y: -1, elite: true },
          { enemy: 'enemy_crotale', count: 1, x: 12, y: 1 },
          { enemy: 'enemy_coyote', count: 2, x: 2, y: 11 },
          { enemy: 'enemy_bandit', count: 1, x: 21, y: 6 },
        ],
      },
    ],
    traps: [],
    fragments: [],
    modular: [],
  },
  {
    id: 'room_b3_4',
    biome: 'biome_3',
    index: 4,
    type: 'COMBAT_CHALLENGE',
    refTime: 80,
    obstacles: [
      { x: 6, y: 4, w: 1, h: 1, kind: 'rock' },
      { x: 17, y: 4, w: 1, h: 1, kind: 'rock' },
      { x: 6, y: 8, w: 1, h: 1, kind: 'barrel' },
      { x: 17, y: 8, w: 1, h: 1, kind: 'barrel' },
    ],
    /* chantier 12 D : deux langues de sable mouvant */
    terrain: [
      '........................',
      '.......,,,,,............',
      '.......,,,,,............',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '...........,,,,,........',
      '...........,,,,,........',
      '........................',
    ],
    deco: [
      { x: 2, y: 4, kind: 'saloon', big: true },
      { x: 21, y: 1, kind: 'wanted' },
      { x: 12, y: 2, kind: 'skull' },
      { x: 3, y: 9, kind: 'tumbleweed' },
      { x: 13, y: 4, kind: 'skull' },
      { x: 20, y: 10, kind: 'wanted' },
      { x: 9, y: 9, kind: 'rails' },
      { x: 5, y: 12, kind: 'rails' },
      { x: 14, y: 1, kind: 'rails' },
      { x: 11, y: 6, kind: 'wanted' },
      { x: 3, y: 11, kind: 'skullpile' },
      { x: 6, y: 7, kind: 'rails' },
      { x: 8, y: 7, kind: 'rails' },
      { x: 6, y: 9, kind: 'rails' },
      { x: 16, y: 5, kind: 'skullpile' },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_coyote', count: 3, x: 20, y: 4 },
          { enemy: 'enemy_bandit', count: 1, x: 21, y: 8 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_baril', count: 2, x: 21, y: 2 },
          { enemy: 'enemy_coyote', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_crotale', count: 1, x: 2, y: 11 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_bandit', count: 2, x: 21, y: 6 },
          { enemy: 'enemy_coyote', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_scorpions', count: 1, x: 12, y: 1 },
        ],
      },
    ],
    traps: [
      /* chantier 13 C : le joueur décide */
      { trap: 'trap_cloche', x: 12, y: 2 },
      { trap: 'trap_revolver', x: 0, y: 3, phase: 0 },
      { trap: 'trap_revolver', x: 23, y: 9, phase: 1.5 },
    ],
    fragments: [],
    modular: [],
  },
  /* Plan « l'entonnoir » : deux masses rocheuses convergent en un col de 3 tuiles. Chambre large, goulot,
     chambre de sortie. Le col passe pour un bison (2 tuiles minimum), le combat change de nature en le franchissant. */
  {
    id: 'room_b3_3',
    biome: 'biome_3',
    index: 3,
    type: 'COMBAT_TRAP',
    chest: true, // coffre offert en fin de salle (chantier 9)
    refTime: 105,
    terrain: [
      '........#########.......',
      '.........#######........',
      '..........#####.........',
      '...........###..........',
      '............#...........',
      '........................',
      '........................',
      '........................',
      '............#...........',
      '...........###..........',
      '..........#####.........',
      '.........#######........',
      '........#########.......',
    ],
    obstacles: [
      { x: 4, y: 3, w: 2, h: 1, kind: 'crate' },
      { x: 4, y: 9, w: 2, h: 1, kind: 'crate' },
      { x: 18, y: 3, w: 1, h: 2, kind: 'cactus' },
      { x: 18, y: 8, w: 1, h: 2, kind: 'cactus' },
    ],
    deco: [
      { x: 1, y: 11, kind: 'skull' },
      { x: 22, y: 1, kind: 'tumbleweed' },
      { x: 6, y: 1, kind: 'skullpile' },
      { x: 8, y: 7, kind: 'skullpile' },
      { x: 15, y: 7, kind: 'skullpile' },
      { x: 10, y: 4, kind: 'tumbleweed' },
      { x: 7, y: 11, kind: 'tumbleweed' },
      { x: 10, y: 8, kind: 'wanted' },
      { x: 18, y: 2, kind: 'skullpile' },
      { x: 6, y: 4, kind: 'rails' },
      { x: 6, y: 9, kind: 'skull' },
      { x: 11, y: 6, kind: 'tumbleweed' },
      { x: 20, y: 2, kind: 'tumbleweed', big: true },
      { x: 8, y: 4, kind: 'skullpile', big: true },
      { x: 9, y: 10, kind: 'skullpile' },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_coyote', count: 4, x: 20, y: 6 },
          { enemy: 'enemy_bandit', count: 2, x: 21, y: 2 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_bison', count: 1, x: 21, y: 6 },
          { enemy: 'enemy_coyote', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_baril', count: 2, x: 2, y: 11 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_baril', count: 3, x: 2, y: 1 },
          { enemy: 'enemy_bandit', count: 3, x: 21, y: 10 },
          { enemy: 'enemy_scorpions', count: 1, x: 21, y: 2 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_crotale', count: 2, x: 21, y: 6 },
          { enemy: 'enemy_coyote', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_bison', count: 1, x: 19, y: 11 },
        ],
      },
    ],
    traps: [
      /* chantier 13 D : ce qui bouge et ce qui reste */
      { trap: 'trap_sablier', x: 18, y: 2 },
      { trap: 'trap_moulin', x: 5, y: 6, params: { beats: { turn: 4, period: 8, active: 6, telegraph: 2, on: 0 } } },
      { trap: 'trap_ours', x: 1, y: 1, w: 3, h: 3, phase: 0 },
      { trap: 'trap_ours', x: 20, y: 9, w: 3, h: 3, phase: 1 },
      { trap: 'trap_embuscade', x: 7, y: 0, phase: 0 },
      { trap: 'trap_embuscade', x: 19, y: 12, phase: 1.2 },
      { trap: 'trap_poudre', x: 6, y: 6, phase: 2 },
    ],
    fragments: [],
    modular: [],
  },
  {
    id: 'room_b3_5',
    biome: 'biome_3',
    index: 5,
    type: 'MINIBOSS',
    refTime: 140,
    obstacles: [
      { x: 5, y: 3, w: 2, h: 2, kind: 'rock' },
      { x: 17, y: 3, w: 2, h: 2, kind: 'rock' },
      { x: 5, y: 8, w: 2, h: 2, kind: 'rock' },
      { x: 17, y: 8, w: 2, h: 2, kind: 'rock' },
      { x: 11, y: 6, w: 2, h: 1, kind: 'wagon' },
    ],
    deco: [
      { x: 2, y: 1, kind: 'wanted' },
      { x: 21, y: 11, kind: 'skull' },
      { x: 14, y: 7, kind: 'tumbleweed', big: true },
      { x: 15, y: 12, kind: 'skullpile' },
      { x: 20, y: 9, kind: 'wanted' },
      { x: 18, y: 0, kind: 'skullpile' },
      { x: 15, y: 5, kind: 'skull' },
      { x: 16, y: 8, kind: 'tumbleweed' },
      { x: 6, y: 2, kind: 'wanted' },
      { x: 10, y: 9, kind: 'skullpile' },
      { x: 13, y: 12, kind: 'tumbleweed' },
      { x: 20, y: 3, kind: 'wanted', big: true },
      { x: 10, y: 2, kind: 'skullpile' },
      { x: 7, y: 5, kind: 'wanted' },
    ],
    waves: [{ at: 'start', spawns: [{ enemy: 'boss_marshal', count: 1, x: 18, y: 6 }] }],
    traps: [
      { trap: 'trap_poudre', x: 3, y: 6, phase: 3 },
      { trap: 'trap_poudre', x: 20, y: 6, phase: 7 },
    ],
    fragments: [],
    modular: [],
  },
  {
    id: 'room_b3_7',
    biome: 'biome_3',
    index: 7,
    type: 'COMBAT_MODULAR',
    chest: true, // coffre offert en fin de salle (chantier 9)
    refTime: 95,
    obstacles: [{ x: 11, y: 5, w: 2, h: 3, kind: 'rock' }],
    anims: [
      {
        kind: 'spinner',
        x: 11,
        y: 0,
        w: 2,
        h: 1,
        params: { sprite: 'windmill', scale: 2.2 },
        beats: { bars: 1, hits: [0, 1, 2, 3], active: 0.5 },
      },
      {
        kind: 'mover',
        x: 12,
        y: 6,
        params: {
          sprite: 'vulture',
          scale: 0.9,
          path: [
            [3, 1],
            [12, 0],
            [20, 1],
            [21, 6],
            [20, 11],
            [12, 12],
            [3, 11],
            [2, 6],
          ],
        },
        beats: { bars: 1, hits: [0], active: 2 },
      },
    ],
    deco: [
      { x: 1, y: 1, kind: 'tumbleweed' },
      { x: 22, y: 11, kind: 'skull' },
      { x: 16, y: 3, kind: 'skull', big: true },
      { x: 16, y: 0, kind: 'skullpile' },
      { x: 14, y: 6, kind: 'rails' },
      { x: 8, y: 1, kind: 'skull' },
      { x: 8, y: 4, kind: 'skull' },
      { x: 14, y: 10, kind: 'barrels' },
      { x: 9, y: 8, kind: 'skull' },
      { x: 4, y: 8, kind: 'skull' },
      { x: 9, y: 11, kind: 'tumbleweed' },
      { x: 16, y: 9, kind: 'skullpile' },
      { x: 10, y: 7, kind: 'skullpile' },
      { x: 4, y: 3, kind: 'wanted', big: true },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_crotale', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_bandit', count: 3, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_croquemort', count: 1, x: 21, y: 6 },
          { enemy: 'enemy_coyote', count: 5, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_bison', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_baril', count: 4, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_crotale', count: 2, x: -1, y: -1, elite: true },
          { enemy: 'enemy_bandit', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_scorpions', count: 2, x: -1, y: -1 },
        ],
      },
    ],
    traps: [
      /* chantier 13 B : les pièges dormants posés */
      {
        trap: 'trap_aiguillage',
        x: 14,
        y: 0,
        w: 8,
        phase: 0,
        params: {
          box: { x: 13, y: 2 },
          routes: [
            [
              { x: 0, y: 0 },
              { x: 7, y: 0 },
            ],
            [
              { x: 0, y: 0 },
              { x: 0, y: 6 },
            ],
          ],
        },
      },
      { trap: 'trap_wagonnet', x: 2, y: 12, w: 8, phase: 1.6 },
      { trap: 'trap_embuscade', x: 0, y: 3, phase: 0 },
      { trap: 'trap_embuscade', x: 23, y: 9, phase: 1 },
    ],
    fragments: [],
    modular: [
      /* la Concession : trois barrières de corral qui coulissent, décalées, et un sol de planches qui se déplace */
      { kind: 'slide_wall', x: 6, y: 1, w: 1, h: 4, dx: 0, dy: 7, period: 7, phase: 0, look: 'cellar-barrels' },
      { kind: 'slide_wall', x: 12, y: 8, w: 1, h: 4, dx: 0, dy: -7, period: 7, phase: 2.3, look: 'cellar-barrels' },
      { kind: 'slide_wall', x: 18, y: 1, w: 1, h: 4, dx: 0, dy: 7, period: 7, phase: 4.6, look: 'cellar-barrels' },
      {
        kind: 'floor_cycle',
        period: 10,
        telegraph: 1.5,
        configs: [
          [
            { x: 3, y: 6, w: 2, h: 1 },
            { x: 20, y: 6, w: 2, h: 1 },
          ],
          [
            { x: 9, y: 3, w: 1, h: 1 },
            { x: 15, y: 9, w: 1, h: 1 },
            { x: 9, y: 9, w: 1, h: 1 },
            { x: 15, y: 3, w: 1, h: 1 },
          ],
        ],
      },
    ],
  },
  {
    id: 'room_b3_8',
    biome: 'biome_3',
    index: 8,
    type: 'COMBAT_TEMPO',
    refTime: 110,
    obstacles: [
      { x: 5, y: 3, w: 1, h: 1, kind: 'barrel' },
      { x: 18, y: 3, w: 1, h: 1, kind: 'barrel' },
      { x: 5, y: 9, w: 1, h: 1, kind: 'barrel' },
      { x: 18, y: 9, w: 1, h: 1, kind: 'barrel' },
    ],
    deco: [
      { x: 17, y: 0, kind: 'rails' },
      { x: 14, y: 7, kind: 'barrels' },
      { x: 12, y: 10, kind: 'barrels', big: true },
      { x: 9, y: 1, kind: 'skull' },
      { x: 15, y: 4, kind: 'skull' },
      { x: 7, y: 1, kind: 'skullpile' },
      { x: 8, y: 4, kind: 'skullpile' },
      { x: 16, y: 8, kind: 'rails' },
      { x: 15, y: 12, kind: 'rails' },
      { x: 13, y: 1, kind: 'skullpile' },
      { x: 13, y: 8, kind: 'rails' },
      { x: 16, y: 3, kind: 'barrels' },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_coyote', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_bandit', count: 2, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_baril', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_crotale', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_bandit', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_scorpions', count: 1, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_bandit', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_coyote', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_baril', count: 3, x: -1, y: -1 },
          { enemy: 'enemy_crotale', count: 1, x: -1, y: -1 },
          { enemy: 'enemy_bison', count: 1, x: 21, y: 6 },
        ],
      },
    ],
    traps: [
      /* chantier 13 C : le joueur décide */
      { trap: 'trap_fil', x: 0, y: 8, phase: 0 },
      { trap: 'trap_ours', x: 2, y: 2, w: 4, h: 3, params: { beats: { period: 4, active: 0.5, telegraph: 1, on: 0 } } },
      { trap: 'trap_ours', x: 18, y: 8, w: 4, h: 3, params: { beats: { period: 4, active: 0.5, telegraph: 1, on: 0 } } },
      { trap: 'trap_ours', x: 18, y: 2, w: 4, h: 3, params: { beats: { period: 4, active: 0.5, telegraph: 1, on: 2 } } },
      { trap: 'trap_ours', x: 2, y: 8, w: 4, h: 3, params: { beats: { period: 4, active: 0.5, telegraph: 1, on: 2 } } },
      { trap: 'trap_gatling', x: 11, y: 6, params: { beats: { every: 4, telegraph: 1, on: 0 } } },
      {
        trap: 'trap_dynamite',
        x: 11,
        y: 0,
        params: { link: 'dyn', dir: 'down', pattern: 'fan', count: 3, beats: { every: 8, telegraph: 1, on: 1 } },
      },
      {
        trap: 'trap_dynamite',
        x: 12,
        y: 12,
        params: { link: 'dyn', dir: 'up', pattern: 'fan', count: 3, beats: { every: 8, telegraph: 1, on: 5 } },
      },
      { trap: 'trap_poudre', x: 4, y: 6, params: { beats: { period: 8, active: 2, telegraph: 2, on: 4 } } },
      { trap: 'trap_poudre', x: 19, y: 6, params: { beats: { period: 8, active: 2, telegraph: 2, on: 0 } } },
      { trap: 'trap_embuscade', x: 0, y: 10, params: { beats: { every: 8, telegraph: 1, on: 3 } } },
      { trap: 'trap_embuscade', x: 23, y: 2, params: { beats: { every: 8, telegraph: 1, on: 7 } } },
    ],
    fragments: [],
    modular: [],
  },
  {
    id: 'room_b3_9',
    biome: 'biome_3',
    index: 9,
    type: 'BOSS_REVENGE',
    refTime: 170,
    obstacles: [
      { x: 5, y: 3, w: 2, h: 2, kind: 'deadtree' },
      { x: 17, y: 3, w: 2, h: 2, kind: 'rock' },
      { x: 5, y: 8, w: 2, h: 2, kind: 'rock' },
      { x: 17, y: 8, w: 2, h: 2, kind: 'deadtree' },
    ],
    deco: [
      { x: 2, y: 1, kind: 'wanted' },
      { x: 21, y: 11, kind: 'skull' },
      { x: 12, y: 1, kind: 'tumbleweed' },
      { x: 15, y: 5, kind: 'rails' },
      { x: 18, y: 0, kind: 'tumbleweed' },
      { x: 8, y: 3, kind: 'rails' },
      { x: 9, y: 12, kind: 'tumbleweed' },
      { x: 15, y: 8, kind: 'tumbleweed', big: true },
      { x: 13, y: 2, kind: 'tumbleweed' },
      { x: 10, y: 7, kind: 'tumbleweed' },
      { x: 18, y: 10, kind: 'skull' },
      { x: 12, y: 8, kind: 'skullpile' },
      { x: 14, y: 1, kind: 'tumbleweed' },
      { x: 9, y: 2, kind: 'wanted' },
      { x: 5, y: 6, kind: 'tumbleweed' },
    ],
    waves: [{ at: 'start', spawns: [{ enemy: 'boss_marshal', count: 1, x: 18, y: 6 }] }],
    traps: [
      { trap: 'trap_embuscade', x: 11, y: 0, phase: 0 },
      { trap: 'trap_embuscade', x: 12, y: 12, phase: 1.2 },
      { trap: 'trap_poudre', x: 3, y: 6, phase: 4 },
      { trap: 'trap_poudre', x: 20, y: 6, phase: 8 },
    ],
    fragments: [],
    modular: [],
  },
  // ---------- SALLE 2 : LE TRAIN (unique à la Concession) — trois wagons traversent la salle sans s'arrêter ----------
  {
    id: 'room_b3_2',
    biome: 'biome_3',
    index: 2,
    type: 'TRAIN',
    refTime: 75,
    obstacles: [
      { x: 6, y: 4, w: 1, h: 1, kind: 'crate' },
      { x: 17, y: 8, w: 1, h: 1, kind: 'barrel' },
      { x: 11, y: 1, w: 2, h: 1, kind: 'crate' },
      { x: 11, y: 11, w: 2, h: 1, kind: 'barrel' },
    ],
    deco: [
      { x: 2, y: 1, kind: 'wanted' },
      { x: 21, y: 11, kind: 'skull' },
      { x: 19, y: 1, kind: 'tumbleweed' },
      { x: 15, y: 11, kind: 'tumbleweed' },
      { x: 6, y: 11, kind: 'skullpile' },
      { x: 19, y: 11, kind: 'skullpile', big: true },
      { x: 8, y: 1, kind: 'tumbleweed', big: true },
      { x: 5, y: 1, kind: 'wanted' },
      { x: 9, y: 11, kind: 'tumbleweed', big: true },
      { x: 7, y: 12, kind: 'skull' },
      { x: 11, y: 12, kind: 'skullpile', big: true },
      { x: 3, y: 11, kind: 'skullpile' },
      { x: 17, y: 11, kind: 'rails', big: true },
      { x: 12, y: 0, kind: 'tumbleweed' },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_coyote', count: 3, x: 20, y: 6 },
          { enemy: 'enemy_bandit', count: 1, x: 21, y: 3 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_baril', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_coyote', count: 3, x: 21, y: 9 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_bandit', count: 2, x: 21, y: 3 },
          { enemy: 'enemy_scorpions', count: 1, x: -1, y: -1 },
          { enemy: 'enemy_crotale', count: 1, x: 21, y: 6 },
        ],
      },
    ],
    traps: [],
    fragments: [],
    modular: [
      { kind: 'slide_wall', x: 2, y: 3, w: 3, h: 1, dx: 18, dy: 0, period: 6, phase: 0, loop: true, look: 'wagon' },
      { kind: 'slide_wall', x: 20, y: 9, w: 3, h: 1, dx: -18, dy: 0, period: 6, phase: 3, loop: true, look: 'wagon' },
      { kind: 'slide_wall', x: 2, y: 6, w: 2, h: 1, dx: 18, dy: 0, period: 9, phase: 4.5, loop: true, look: 'wagon' },
    ],
  },
  // ---------- SALLE 6 : COMBAT + PIÈGES + MODULAIRE ----------
  {
    id: 'room_b3_6',
    biome: 'biome_3',
    index: 6,
    type: 'COMBAT_TRAP_MODULAR',
    refTime: 90,
    obstacles: [
      { x: 2, y: 2, w: 1, h: 1, kind: 'barrels' },
      { x: 21, y: 2, w: 1, h: 1, kind: 'barrels' },
      { x: 2, y: 10, w: 1, h: 1, kind: 'barrels' },
      { x: 21, y: 10, w: 1, h: 1, kind: 'barrels' },
    ],
    deco: [
      { x: 12, y: 1, kind: 'skull' },
      { x: 12, y: 11, kind: 'tumbleweed' },
      { x: 2, y: 6, kind: 'skullpile' },
      { x: 17, y: 1, kind: 'skullpile' },
      { x: 19, y: 5, kind: 'tumbleweed' },
      { x: 6, y: 0, kind: 'wanted', big: true },
      { x: 4, y: 4, kind: 'barrels' },
      { x: 7, y: 12, kind: 'skullpile' },
      { x: 16, y: 8, kind: 'tumbleweed' },
      { x: 4, y: 7, kind: 'tumbleweed' },
      { x: 16, y: 5, kind: 'wanted' },
      { x: 14, y: 7, kind: 'skullpile' },
      { x: 14, y: 4, kind: 'wanted' },
      { x: 14, y: 9, kind: 'skullpile' },
      { x: 11, y: 12, kind: 'skullpile' },
    ],
    waves: [
      {
        at: 'start',
        spawns: [
          { enemy: 'enemy_bison', count: 1, x: 21, y: 6 },
          { enemy: 'enemy_bandit', count: 2, x: 20, y: 3 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_scorpions', count: 2, x: -1, y: -1 },
          { enemy: 'enemy_coyote', count: 3, x: 20, y: 9 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_croquemort', count: 1, x: 21, y: 6 },
          { enemy: 'enemy_crotale', count: 2, x: -1, y: -1 },
        ],
      },
      {
        at: 'clear',
        spawns: [
          { enemy: 'enemy_bandit', count: 2, x: 3, y: 2 },
          { enemy: 'enemy_coyote', count: 4, x: -1, y: -1 },
          { enemy: 'enemy_baril', count: 2, x: 20, y: 9 },
        ],
      },
    ],
    traps: [
      /* chantier 13 C : le joueur décide */
      { trap: 'trap_tonneaux', x: 3, y: 2 },
      { trap: 'trap_tonneaux', x: 5, y: 2 },
      { trap: 'trap_tonneaux', x: 7, y: 2 },
      { trap: 'trap_tonneaux', x: 9, y: 2 },
      { trap: 'trap_embuscade', x: 8, y: 0, phase: 0 },
      { trap: 'trap_embuscade', x: 15, y: 12, phase: 1.2 },
      { trap: 'trap_ours', x: 1, y: 9, w: 3, h: 3, phase: 0 },
      { trap: 'trap_ours', x: 20, y: 1, w: 3, h: 3, phase: 1 },
      { trap: 'trap_barbeles', x: 6, y: 3, w: 12, h: 7, phase: 0 },
      { trap: 'trap_detente', x: 0, y: 3, phase: 1 },
    ],
    fragments: [],
    modular: [
      {
        kind: 'floor_cycle',
        period: 9,
        telegraph: 1.5,
        configs: [
          [
            { x: 6, y: 3, w: 2, h: 1 },
            { x: 16, y: 9, w: 2, h: 1 },
            { x: 11, y: 6, w: 2, h: 1 },
          ],
          [
            { x: 6, y: 9, w: 2, h: 1 },
            { x: 16, y: 3, w: 2, h: 1 },
            { x: 11, y: 1, w: 2, h: 1 },
          ],
        ],
      },
    ],
  }
);

/* chantier 13 C — le joueur décide : des pièges qui se déclenchent à la plaque, à l'approche, au tir, en chaîne ;
   qui poussent, endorment, brûlent ; qu'on casse ou qu'on désamorce. Tous blessent les deux camps. */
CONTENT.traps.push(
  {
    id: 'trap_tonneaux',
    name: 'Tonneaux de poudre',
    desc: 'Un tir, ou l’explosion d’à côté, et la file part en chaîne, pour les deux camps.',
    kind: 'blast_prop',
    color: '#ff8c42',
    damage: 20,
    telegraph: 0.15,
    active: 0.1,
    hp: 1,
    params: { sprite: 'barrel', onShot: 'fire', once: true, radius: 100, link: 'poudre', linkRange: 2.5, linkDelay: 0.15 },
  },
  {
    id: 'trap_fil',
    name: 'Fil de détente armé',
    desc: 'Un fil tendu en travers ; qui le franchit — toi ou un ennemi — fait partir les dynamites qui y sont liées.',
    kind: 'wire_arm',
    color: '#b0774a',
    damage: 0,
    telegraph: 0.1,
    active: 0.2,
    params: { angle: 0, length: 26, thickness: 0.15, sensor: 'body', who: 'any', link: 'dyn', rearm: 3 },
  },
  {
    id: 'trap_aiguillage',
    name: 'Aiguillage',
    desc: 'Un wagonnet fou et son levier : un tir dessus et il change de voie au prochain passage. Choisis qui il écrase.',
    kind: 'saw_rail',
    color: '#9a8a6a',
    damage: 22,
    telegraph: 0.5,
    period: 3.2,
    active: 3.2,
    hp: 1,
    params: { speedTiles: 6, radiusTiles: 0.65, pingpong: true, onShot: 'toggle' },
  },
  {
    id: 'trap_cloche',
    name: 'Cloche du saloon',
    desc: 'Une plaque dorée : la sonner appelle quatre bandits, une bourse tombe à tes pieds et un coffre s’ouvre. Le trésor gardé.',
    kind: 'plate_call',
    color: '#ffd166',
    damage: 0,
    telegraph: 0.6,
    active: 0.2,
    params: { who: 'player', once: true, enemy: 'enemy_bandit', count: 4, purse: 60, chest: true, pattern: 'plain' },
  }
);

/* chantier 13 D — le piège porté : le coyote le laisse là où il tombe (behavior.drop), une seule morsure */
CONTENT.traps.push({
  id: 'trap_loup',
  name: 'Piège à loup',
  desc: 'Le coyote le laisse là où il tombe : une mâchoire qui mord une fois celui qui marche dessus, puis disparaît.',
  kind: 'tiles_press',
  color: '#cfd6e6',
  damage: 12,
  telegraph: 0.15,
  active: 0.3,
  params: { who: 'player', once: true, pattern: 'plain' },
});
