'use strict';
const CONTENT = {
  // =====================================================================
  // PERSONNAGES
  // =====================================================================
  characters: [],

  // =====================================================================
  // ARMES  (DPS théorique nu entre parenthèses dans desc)
  // =====================================================================
  weapons: [
    {
      id: 'weapon_blade',
      name: "Lame d'essai",
      desc: 'Lame rapide : un arc devant toi, 3,4 coups par seconde, bon recul. Sûre, mais au contact.',
      family: 'blade',
      type: 'melee',
      damage: 28,
      fireRate: 3.4,
      range: 70,
      projSpeed: 0,
      projectiles: 0,
      spread: 0,
      pierce: 0,
      bounce: 0,
      knockback: 1.5,
      size: 60,
      charge: null,
      special: { kind: 'sweep', arc: 2.18, hitAllInArc: true },
      unlocked: true,
      price: 0,
    },
    {
      id: 'weapon_hammer',
      name: 'Masse de pression',
      desc: 'Marteau lent : 75 dégâts en zone, 0,8 coup par seconde, recul énorme, étourdit 0,6 s.',
      family: 'hammer',
      type: 'area',
      damage: 75,
      fireRate: 0.8,
      range: 95,
      projSpeed: 0,
      projectiles: 0,
      spread: 0,
      pierce: 0,
      bounce: 0,
      knockback: 3.0,
      size: 85,
      charge: null,
      special: { kind: 'slam', stunTime: 0.6, windup: 0.25 },
      unlocked: false,
      price: 50,
    },
    {
      id: 'weapon_bow',
      name: 'Arc tendeur',
      desc: 'Tir rapide de 30 dégâts, ou charge 1 s pour tripler et transpercer.',
      family: 'bow',
      type: 'ranged',
      damage: 30,
      fireRate: 1.6,
      range: 720,
      projSpeed: 900,
      projectiles: 1,
      spread: 0,
      pierce: 1,
      bounce: 0,
      knockback: 1.2,
      size: 6,
      charge: { min: 0.25, max: 1.0, damageMul: 3.0 },
      special: { kind: null, chargedPierceBonus: 2, chargedProjSpeedMul: 1.4 },
      unlocked: false,
      price: 70,
    },
    {
      id: 'weapon_pistol',
      name: 'Pistolet à ricochet',
      desc: 'Balles rapides qui rebondissent deux fois sur les murs et cherchent une cible proche.',
      family: 'pistol',
      type: 'ranged',
      damage: 14,
      fireRate: 4.0,
      range: 620,
      projSpeed: 760,
      projectiles: 1,
      spread: 0.06,
      pierce: 0,
      bounce: 2,
      knockback: 0.8,
      size: 5,
      charge: null,
      special: { kind: 'ricochet', seekRadius: 220, seekOnBounce: true },
      unlocked: true,
      price: 0,
    },
    {
      id: 'weapon_boomerang',
      name: 'Boomerang de rappel',
      desc: 'Traverse tout et revient vers toi : deux passages par lancer, un lancer à la fois.',
      family: 'boomerang',
      type: 'ranged',
      damage: 22,
      fireRate: 1.4,
      range: 380,
      projSpeed: 620,
      projectiles: 1,
      spread: 0,
      pierce: 99,
      bounce: 0,
      knockback: 1.0,
      size: 12,
      charge: null,
      special: { kind: 'return', passes: 2, maxInFlight: 1, returnSpeedMul: 1.15 },
      unlocked: false,
      price: 70,
    },
    {
      id: 'weapon_orb',
      name: 'Orbe orbitale',
      desc: 'Deux orbes autour de toi, qui se resserrent quand tu tires : 4 coups de 12 par seconde.',
      family: 'orb',
      type: 'orbital',
      damage: 12,
      fireRate: 4.0,
      range: 65,
      projSpeed: 0,
      projectiles: 2,
      spread: 0,
      pierce: 99,
      bounce: 0,
      knockback: 0.6,
      size: 18,
      charge: null,
      special: { kind: 'orbit', radius: 65, angularSpeed: 5.8, tickRate: 4, blocksProjectiles: false },
      unlocked: false,
      price: 80,
    },
    {
      id: 'weapon_chain',
      name: 'Arc voltaïque',
      desc: 'Éclair instantané de 24 dégâts qui saute sur 2 ennemis proches à 60 %. Fort en groupe.',
      family: 'chain',
      type: 'ranged',
      damage: 24,
      fireRate: 2.0,
      range: 420,
      projSpeed: 1400,
      projectiles: 1,
      spread: 0,
      pierce: 0,
      bounce: 0,
      knockback: 0.5,
      size: 6,
      charge: null,
      special: { kind: 'chain', jumps: 2, radius: 160, damageMul: 0.6 },
      unlocked: false,
      price: 100,
    },
    {
      id: 'weapon_flame',
      name: 'Brûleur court',
      desc: 'Cône de flammes très court : 10 coups de 6 par seconde, plus une brûlure. Il faut coller.',
      family: 'flame',
      type: 'area',
      damage: 6,
      fireRate: 10.0,
      range: 170,
      projSpeed: 0,
      projectiles: 0,
      spread: 0.7,
      pierce: 99,
      bounce: 0,
      knockback: 0.3,
      size: 170,
      charge: null,
      special: { kind: 'cone', angle: 0.7, burnDps: 4, burnDuration: 2.0 },
      unlocked: false,
      price: 90,
    },
  ],

  // =====================================================================
  // COMPÉTENCES ACTIVES
  // =====================================================================
  skills: [
    {
      id: 'skill_dash',
      name: 'Ruée',
      desc: "Une ruée d'un bond, invulnérable pendant 0,22 s.",
      cooldown: 5,
      duration: 0.22,
      effect: { kind: 'dash', distance: 250, invulnerable: true },
      icon: 'dash',
    },
    {
      id: 'skill_shield',
      name: 'Bouclier',
      desc: 'Un bouclier de 45 PV pendant 5 s.',
      cooldown: 12,
      duration: 5,
      effect: { kind: 'shield', amount: 45 },
      icon: 'shield',
    },
    {
      id: 'skill_shockwave',
      name: 'Onde de choc',
      desc: 'Repousse, étourdit et inflige 50 dégâts à tout ce qui est de près.',
      cooldown: 9,
      duration: 0.3,
      effect: { kind: 'shockwave', radius: 210, damage: 50, knockback: 3 },
      icon: 'shockwave',
    },
    {
      id: 'skill_slowtime',
      name: 'Dilatation',
      desc: 'Le monde ralentit à 35 % pendant 3,5 s. Pas toi.',
      cooldown: 16,
      duration: 3.5,
      effect: { kind: 'slowtime', scale: 0.35, playerScale: 1.0 },
      icon: 'slowtime',
    },
    {
      id: 'skill_turret',
      name: 'Tourelle',
      desc: 'Une tourelle pendant 10 s : 14 dégâts trois fois par seconde, et elle tire loin.',
      cooldown: 14,
      duration: 10,
      effect: { kind: 'turret', damage: 14, fireRate: 3, range: 380, hp: 60 },
      icon: 'turret',
    },
    {
      id: 'skill_blink',
      name: 'Saut de phase',
      desc: 'Téléportation vers le curseur, à mi-salle au plus, 0,25 s invulnérable.',
      cooldown: 7,
      duration: 0,
      effect: { kind: 'blink', distance: 280, invulnerable: 0.25, ignoreObstacles: true },
      icon: 'blink',
    },
    {
      id: 'skill_magnet',
      name: 'Aimant',
      desc: 'Attire tout ce qui traîne dans la salle pendant 3 s.',
      cooldown: 10,
      duration: 3,
      effect: { kind: 'magnet', radius: 1400, pullSpeed: 900 },
      icon: 'magnet',
    },
    {
      id: 'skill_overdrive',
      name: 'Surrégime',
      desc: '+60 % de dégâts et de cadence pendant 6 s, mais tu perds 1,5 PV par seconde.',
      cooldown: 16,
      duration: 6,
      effect: { kind: 'overdrive', damageMul: 1.6, fireRateMul: 1.6, selfDamagePerSec: 1.5 },
      icon: 'overdrive',
    },
  ],

  // =====================================================================
  // AMÉLIORATIONS EN RUN  (50 : 20 communes, 15 rares, 10 épiques, 5 colossales)
  // =====================================================================
  upgrades: [
    // ---- COMMUNES (20) ----
    {
      id: 'upg_tranchant',
      name: 'Tranchant',
      desc: '+10 % dégâts.',
      rarity: 'common',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 5,
      mods: [{ stat: 'damage', mul: 1.1 }],
      hooks: {},
    },
    {
      id: 'upg_gachette',
      name: 'Gâchette',
      desc: "+8 % cadence d'attaque.",
      rarity: 'common',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 4,
      mods: [{ stat: 'fireRate', mul: 1.08 }],
      hooks: {},
    },
    {
      id: 'upg_oeil_vif',
      name: 'Œil vif',
      desc: '+6 % chance de critique.',
      rarity: 'common',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 5,
      mods: [{ stat: 'critChance', add: 0.06 }],
      hooks: {},
    },
    {
      id: 'upg_coup_critique',
      name: 'Coup critique',
      desc: '+40 % dégâts des critiques (×1,5 → ×1,9).',
      rarity: 'common',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 3,
      mods: [{ stat: 'critMult', add: 0.4 }],
      hooks: {},
    },
    {
      id: 'upg_longue_portee',
      name: 'Longue portée',
      desc: '+15 % portée, projectiles 15 % plus rapides.',
      rarity: 'common',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 3,
      mods: [
        { stat: 'range', mul: 1.15 },
        { stat: 'projSpeed', mul: 1.15 },
      ],
      hooks: {},
    },
    {
      id: 'upg_plaque',
      name: 'Plaque',
      desc: '+20 PV max.',
      rarity: 'common',
      category: 'defense',
      weaponFamily: null,
      maxStacks: 5,
      mods: [{ stat: 'maxHp', add: 20 }],
      hooks: {},
    },
    {
      id: 'upg_peau_dure',
      name: 'Peau dure',
      desc: '+1 armure (dégâts plats retirés par coup).',
      rarity: 'common',
      category: 'defense',
      weaponFamily: null,
      maxStacks: 4,
      mods: [{ stat: 'armor', add: 1 }],
      hooks: {},
    },
    {
      id: 'upg_cicatrisation',
      name: 'Cicatrisation',
      desc: '+0,8 PV/s de régénération.',
      rarity: 'common',
      category: 'defense',
      weaponFamily: null,
      maxStacks: 4,
      mods: [{ stat: 'regen', add: 0.8 }],
      hooks: {},
    },
    {
      id: 'upg_reflexes',
      name: 'Réflexes',
      desc: "+5 % d'esquive.",
      rarity: 'common',
      category: 'defense',
      weaponFamily: null,
      maxStacks: 4,
      mods: [{ stat: 'dodge', add: 0.05 }],
      hooks: {},
    },
    {
      id: 'upg_semelles',
      name: 'Semelles',
      desc: '+10 % vitesse de déplacement.',
      rarity: 'common',
      category: 'mobility',
      weaponFamily: null,
      maxStacks: 4,
      mods: [{ stat: 'speed', mul: 1.1 }],
      hooks: {},
    },
    {
      id: 'upg_recuperation',
      name: 'Récupération',
      desc: '−6 % de recharge de compétence.',
      rarity: 'common',
      category: 'mobility',
      weaponFamily: null,
      maxStacks: 4,
      mods: [{ stat: 'cooldownReduction', add: 0.06 }],
      hooks: {},
    },
    {
      id: 'upg_tirelire',
      name: 'Tirelire',
      desc: '+20 % de pièces, et tu ramasses un peu plus loin.',
      rarity: 'common',
      category: 'economy',
      weaponFamily: null,
      maxStacks: 4,
      mods: [
        { stat: 'coinGain', mul: 1.2 },
        { stat: 'pickupRadius', add: 30 },
      ],
      hooks: {},
    },
    {
      id: 'upg_apprentissage',
      name: 'Apprentissage',
      desc: '+15 % XP gagnée.',
      rarity: 'common',
      category: 'economy',
      weaponFamily: null,
      maxStacks: 4,
      mods: [{ stat: 'xpGain', mul: 1.15 }],
      hooks: {},
    },
    {
      id: 'upg_trefle',
      name: 'Trèfle',
      desc: '+2 chance (raretés décalées vers épique/colossal).',
      rarity: 'common',
      category: 'economy',
      weaponFamily: null,
      maxStacks: 4,
      mods: [{ stat: 'luck', add: 2 }],
      hooks: {},
    },
    {
      id: 'upg_butin',
      name: 'Butin',
      desc: "15 % de chance qu'un ennemi tué lâche une pièce en plus.",
      rarity: 'common',
      category: 'economy',
      weaponFamily: null,
      maxStacks: 3,
      mods: [],
      hooks: { onKill: [{ effect: 'coin_on_kill', chance: 0.15, amount: 1 }] },
    },
    {
      id: 'upg_etincelle',
      name: 'Étincelle',
      desc: '15 % de chance de brûler (5 dégâts/s, 2 s) — 30 % puis 45 % en la reprenant.',
      rarity: 'common',
      category: 'special',
      weaponFamily: null,
      maxStacks: 3,
      mods: [],
      hooks: { onHit: [{ effect: 'burn', chance: 0.15, dps: 5, duration: 2 }] },
    },
    {
      id: 'upg_givre',
      name: 'Givre',
      desc: '12 % de chance de geler : -50 % vitesse pendant 1,2 s.',
      rarity: 'common',
      category: 'special',
      weaponFamily: null,
      maxStacks: 3,
      mods: [],
      hooks: { onHit: [{ effect: 'freeze', chance: 0.12, duration: 1.2, slow: 0.5 }] },
    },
    {
      id: 'upg_toxine',
      name: 'Toxine',
      desc: "15 % de chance d'empoisonner : 3 dégâts/s, 4 s, cumulable ×3.",
      rarity: 'common',
      category: 'special',
      weaponFamily: null,
      maxStacks: 3,
      mods: [],
      hooks: { onHit: [{ effect: 'poison', chance: 0.15, dps: 3, duration: 4, stacks: 3 }] },
    },

    // ---- RARES (15) ----
    {
      id: 'upg_frappe_lourde',
      name: 'Frappe lourde',
      desc: '+22 % dégâts, +15 % zone, +20 % recul, -8 % cadence.',
      rarity: 'rare',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 3,
      mods: [
        { stat: 'damage', mul: 1.22 },
        { stat: 'fireRate', mul: 0.92 },
        { stat: 'areaSize', mul: 1.15 },
        { stat: 'knockback', mul: 1.2 },
      ],
      hooks: {},
    },
    {
      id: 'upg_perforation',
      name: 'Perforation',
      desc: '+1 ennemi traversé par les tirs.',
      rarity: 'rare',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 3,
      mods: [{ stat: 'pierce', add: 1 }],
      hooks: {},
    },
    {
      id: 'upg_rebond',
      name: 'Rebond',
      desc: '+1 rebond sur les murs.',
      rarity: 'rare',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 3,
      mods: [{ stat: 'bounce', add: 1 }],
      hooks: {},
    },
    {
      id: 'upg_vampirisme',
      name: 'Vampirisme',
      desc: '4 % des dégâts infligés rendus en PV.',
      rarity: 'rare',
      category: 'defense',
      weaponFamily: null,
      maxStacks: 3,
      mods: [{ stat: 'lifesteal', add: 0.04 }],
      hooks: {},
    },
    {
      id: 'upg_epines',
      name: 'Épines',
      desc: 'Renvoie 8 dégâts à tout ennemi qui te touche.',
      rarity: 'rare',
      category: 'defense',
      weaponFamily: null,
      maxStacks: 3,
      mods: [{ stat: 'thorns', add: 8 }],
      hooks: {},
    },
    {
      id: 'upg_isolant',
      name: 'Isolant',
      desc: '-40 % dégâts subis des pièges.',
      rarity: 'rare',
      category: 'defense',
      weaponFamily: null,
      maxStacks: 2,
      mods: [{ stat: 'trapDamageMul', mul: 0.6 }],
      hooks: {},
    },
    {
      id: 'upg_convalescence',
      name: 'Convalescence',
      desc: 'Au début de chaque salle : +20 % PV et 15 PV de bouclier.',
      rarity: 'rare',
      category: 'defense',
      weaponFamily: null,
      maxStacks: 2,
      mods: [],
      hooks: {
        onRoomStart: [
          { effect: 'heal_on_room', fraction: 0.2 },
          { effect: 'shield_on_room', amount: 15 },
        ],
      },
    },
    {
      id: 'upg_adrenaline',
      name: 'Adrénaline',
      desc: 'Chaque ennemi tué : +20 % de vitesse pendant 2 s.',
      rarity: 'rare',
      category: 'mobility',
      weaponFamily: null,
      maxStacks: 2,
      mods: [],
      hooks: { onKill: [{ effect: 'kill_speed', speedMul: 1.2, duration: 2 }] },
    },
    {
      id: 'upg_enchainement',
      name: 'Enchaînement',
      desc: 'Chaque ennemi tué : 20 % de chance de réduire la recharge restante de moitié.',
      rarity: 'rare',
      category: 'mobility',
      weaponFamily: null,
      maxStacks: 2,
      mods: [],
      hooks: { onKill: [{ effect: 'skill_reset_on_kill', chance: 0.2, fraction: 0.5 }] },
    },
    {
      id: 'upg_chaine_eclair',
      name: 'Chaîne éclair',
      desc: '20 % de chance de sauter sur 2 ennemis proches (50 %) ; 40 puis 60 % en la reprenant.',
      rarity: 'rare',
      category: 'special',
      weaponFamily: null,
      maxStacks: 3,
      mods: [],
      hooks: { onHit: [{ effect: 'chain', chance: 0.2, jumps: 2, radius: 150, damageMul: 0.5 }] },
    },
    {
      id: 'upg_detonation',
      name: 'Détonation',
      desc: 'Les ennemis tués explosent : 60 % de tes dégâts, à bout portant.',
      rarity: 'rare',
      category: 'special',
      weaponFamily: null,
      maxStacks: 2,
      mods: [],
      hooks: { onKill: [{ effect: 'explode', radius: 70, damageMul: 0.6 }] },
    },
    // synergies rares
    {
      id: 'upg_syn_lame_dansante',
      name: 'Lame dansante',
      desc: 'Lame : +25 % de cadence, et chaque ennemi tué te donne +15 % de vitesse 1,5 s.',
      rarity: 'rare',
      category: 'synergy',
      weaponFamily: 'blade',
      maxStacks: 2,
      mods: [{ stat: 'fireRate', mul: 1.25 }],
      hooks: { onKill: [{ effect: 'kill_speed', speedMul: 1.15, duration: 1.5 }] },
    },
    {
      id: 'upg_syn_balles_chercheuses',
      name: 'Balles chercheuses',
      desc: 'Pistolet : +2 rebonds, +10 % dégâts.',
      rarity: 'rare',
      category: 'synergy',
      weaponFamily: 'pistol',
      maxStacks: 2,
      mods: [
        { stat: 'bounce', add: 2 },
        { stat: 'damage', mul: 1.1 },
      ],
      hooks: {},
    },
    {
      id: 'upg_syn_corde_tendue',
      name: 'Corde tendue',
      desc: 'Arc : charge 40 % plus vite, +2 perforation, +30 % vitesse de flèche.',
      rarity: 'rare',
      category: 'synergy',
      weaponFamily: 'bow',
      maxStacks: 2,
      mods: [
        { stat: 'pierce', add: 2 },
        { stat: 'projSpeed', mul: 1.3 },
      ],
      hooks: { passive: [{ effect: 'charge_speed', mul: 1.4 }] },
    },

    // ---- ÉPIQUES (10) ----
    {
      id: 'upg_amplificateur',
      name: 'Amplificateur',
      desc: "+30 % d'effet des compétences, −10 % de recharge.",
      rarity: 'epic',
      category: 'mobility',
      weaponFamily: null,
      maxStacks: 2,
      mods: [
        { stat: 'skillPower', mul: 1.3 },
        { stat: 'cooldownReduction', add: 0.1 },
      ],
      hooks: {},
    },
    {
      id: 'upg_double_charge',
      name: 'Double charge',
      desc: 'Ta compétence a deux charges.',
      rarity: 'epic',
      category: 'mobility',
      weaponFamily: null,
      maxStacks: 1,
      mods: [],
      hooks: { passive: [{ effect: 'double_skill' }] },
    },
    {
      id: 'upg_crit_explosif',
      name: 'Crit explosif',
      desc: 'Les critiques explosent : 80 % des dégâts à bout portant. +5 % de critique.',
      rarity: 'epic',
      category: 'special',
      weaponFamily: null,
      maxStacks: 1,
      mods: [{ stat: 'critChance', add: 0.05 }],
      hooks: { onHit: [{ effect: 'crit_explode', radius: 60, damageMul: 0.8 }] },
    },
    {
      id: 'upg_orbes_gardiennes',
      name: 'Orbes gardiennes',
      desc: 'Deux orbes (10 dégâts) tournent autour de toi et bloquent les tirs ; 4 en la reprenant.',
      rarity: 'epic',
      category: 'defense',
      weaponFamily: null,
      maxStacks: 2,
      mods: [],
      hooks: { passive: [{ effect: 'orbit_shield', count: 2, damage: 10, radius: 70 }] },
    },
    {
      id: 'upg_attraction',
      name: 'Attraction',
      desc: 'Tout ce qui traîne vient à toi. Fragments doublés. +20 % XP.',
      rarity: 'epic',
      category: 'economy',
      weaponFamily: null,
      maxStacks: 1,
      mods: [{ stat: 'xpGain', mul: 1.2 }],
      hooks: { passive: [{ effect: 'xp_magnet' }, { effect: 'fragments_double' }] },
    },
    {
      id: 'upg_sang_froid',
      name: "Nerfs d'acier",
      desc: "Touché : ralenti 0,8 s à 40 % et +0,3 s d'invulnérabilité. +2 armure.",
      rarity: 'epic',
      category: 'defense',
      weaponFamily: null,
      maxStacks: 1,
      mods: [
        { stat: 'invulnTime', add: 0.3 },
        { stat: 'armor', add: 2 },
      ],
      hooks: { onDamaged: [{ effect: 'time_slow_on_damage', duration: 0.8, scale: 0.4 }] },
    },
    // synergies épiques
    {
      id: 'upg_syn_onde_tellurique',
      name: 'Onde tellurique',
      desc: 'Marteau : +35 % de zone, +20 % de dégâts, les ennemis tués explosent (80 %, de près).',
      rarity: 'epic',
      category: 'synergy',
      weaponFamily: 'hammer',
      maxStacks: 1,
      mods: [
        { stat: 'areaSize', mul: 1.35 },
        { stat: 'damage', mul: 1.2 },
      ],
      hooks: { onKill: [{ effect: 'explode', radius: 90, damageMul: 0.8 }] },
    },
    {
      id: 'upg_syn_constellation',
      name: 'Constellation',
      desc: "Orbe : +2 orbes, rayon d'orbite +20 %, +15 % dégâts.",
      rarity: 'epic',
      category: 'synergy',
      weaponFamily: 'orb',
      maxStacks: 1,
      mods: [
        { stat: 'projectiles', add: 2 },
        { stat: 'range', mul: 1.2 },
        { stat: 'damage', mul: 1.15 },
      ],
      hooks: {},
    },
    {
      id: 'upg_syn_surtension',
      name: 'Surtension',
      desc: 'Foudre : chaque coup saute sur 3 ennemis proches à 70 %.',
      rarity: 'epic',
      category: 'synergy',
      weaponFamily: 'chain',
      maxStacks: 1,
      mods: [],
      hooks: { onHit: [{ effect: 'chain', chance: 1.0, jumps: 3, radius: 200, damageMul: 0.7 }] },
    },
    {
      id: 'upg_syn_triple_rappel',
      name: 'Triple rappel',
      desc: 'Boomerang : +1 boomerang en vol, +15 % dégâts, +15 % cadence.',
      rarity: 'epic',
      category: 'synergy',
      weaponFamily: 'boomerang',
      maxStacks: 1,
      mods: [
        { stat: 'projectiles', add: 1 },
        { stat: 'damage', mul: 1.15 },
        { stat: 'fireRate', mul: 1.15 },
      ],
      hooks: {},
    },
    // synergie flamme (rare) placée ici pour lisibilité du bloc synergies
    {
      id: 'upg_syn_combustion',
      name: 'Combustion',
      desc: 'Flammes : brûlure garantie 8 dégâts/s 3 s, +20 % taille de cône.',
      rarity: 'rare',
      category: 'synergy',
      weaponFamily: 'flame',
      maxStacks: 2,
      mods: [{ stat: 'areaSize', mul: 1.2 }],
      hooks: { onHit: [{ effect: 'burn', chance: 1.0, dps: 8, duration: 3 }] },
    },

    // ---- COLOSSALES (5) ----
    /* --- Greffes offensives supplémentaires (retour joueur : plus de projectiles, d'orbes, de balles à effet) --- */
    {
      id: 'upg_second_canon',
      name: 'Double canon',
      desc: '+1 projectile par tir, -12 % dégâts.',
      rarity: 'rare',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 2,
      mods: [
        { stat: 'projectiles', add: 1 },
        { stat: 'damage', mul: 0.88 },
      ],
      hooks: {},
    },
    {
      id: 'upg_salve',
      name: 'Salve',
      desc: '+2 projectiles par tir, -30 % dégâts.',
      rarity: 'epic',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 1,
      mods: [
        { stat: 'projectiles', add: 2 },
        { stat: 'damage', mul: 0.7 },
      ],
      hooks: {},
    },
    {
      id: 'upg_tir_guide',
      name: 'Tir guidé',
      desc: "Tes projectiles se dirigent vers l'ennemi le plus proche.",
      rarity: 'epic',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 1,
      mods: [],
      hooks: { passive: [{ effect: 'homing', turn: 2.5 }] },
    },
    {
      id: 'upg_eclats',
      name: 'Éclats',
      desc: 'Chaque impact libère 2 éclats (40 % des dégâts).',
      rarity: 'epic',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 1,
      mods: [],
      hooks: { onHit: [{ effect: 'split_on_hit', chance: 1, count: 2, damageMul: 0.4 }] },
    },
    {
      id: 'upg_tir_arriere',
      name: 'Tir arrière',
      desc: 'Chaque tir envoie aussi un projectile derrière toi (50 %).',
      rarity: 'rare',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 1,
      mods: [],
      hooks: { passive: [{ effect: 'rear_shot', damageMul: 0.5 }] },
    },
    {
      id: 'upg_balles_explosives',
      name: 'Balles explosives',
      desc: "25 % de chance qu'un impact explose à bout portant (70 % des dégâts).",
      rarity: 'epic',
      category: 'special',
      weaponFamily: null,
      maxStacks: 1,
      mods: [],
      hooks: { onHit: [{ effect: 'hit_explode', chance: 0.25, radius: 60, damageMul: 0.7 }] },
    },
    {
      id: 'upg_foudre_ambiante',
      name: 'Foudre ambiante',
      desc: "Toutes les 3,5 s environ, la foudre frappe l'ennemi le plus proche (26 dégâts).",
      rarity: 'epic',
      category: 'special',
      weaponFamily: null,
      maxStacks: 2,
      mods: [],
      hooks: { passive: [{ effect: 'lightning_storm', every: 3.5, damage: 26, radius: 320 }] },
    },
    {
      id: 'upg_aura_brulante',
      name: 'Aura brûlante',
      desc: 'Les ennemis à bout portant brûlent : 8 dégâts par seconde.',
      rarity: 'rare',
      category: 'special',
      weaponFamily: null,
      maxStacks: 2,
      mods: [],
      hooks: { passive: [{ effect: 'burn_aura', radius: 90, dps: 8 }] },
    },
    {
      id: 'upg_drone',
      name: "Drone d'appoint",
      desc: 'Un drone te suit et tire deux fois par seconde (6 dégâts).',
      rarity: 'rare',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 2,
      mods: [],
      hooks: { passive: [{ effect: 'drone', count: 1, damage: 6, fireRate: 2, range: 340 }] },
    },
    {
      id: 'upg_execution',
      name: 'Exécution',
      desc: 'Les ennemis (hors boss) sous 15 % de PV meurent au prochain coup.',
      rarity: 'rare',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 1,
      mods: [],
      hooks: { passive: [{ effect: 'execute', threshold: 0.15 }] },
    },
    {
      id: 'upg_gel_profond',
      name: 'Gel profond',
      desc: 'Les ennemis gelés subissent +35 % de dégâts.',
      rarity: 'rare',
      category: 'special',
      weaponFamily: null,
      maxStacks: 1,
      mods: [],
      hooks: { passive: [{ effect: 'frost_bonus', mul: 1.35 }] },
    },
    {
      id: 'upg_rafale',
      name: 'Rafale',
      desc: 'Après une compétence : cadence +45 % pendant 3 s.',
      rarity: 'rare',
      category: 'mobility',
      weaponFamily: null,
      maxStacks: 1,
      mods: [],
      hooks: { onSkill: [{ effect: 'fire_frenzy', fireRateMul: 1.45, duration: 3 }] },
    },
    {
      id: 'upg_mitraille',
      name: 'Mitraille',
      desc: '+3 projectiles, tirs guidés, -20 % dégâts.',
      rarity: 'colossal',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 1,
      mods: [
        { stat: 'projectiles', add: 3 },
        { stat: 'damage', mul: 0.8 },
      ],
      hooks: { passive: [{ effect: 'homing', turn: 3 }] },
    },
    {
      id: 'upg_rappel',
      name: 'Rappel',
      desc: 'Tes projectiles reviennent vers toi : un second passage sur tout.',
      rarity: 'colossal',
      category: 'special',
      weaponFamily: null,
      maxStacks: 1,
      mods: [],
      hooks: { passive: [{ effect: 'projectiles_return' }] },
    },
    {
      id: 'upg_sillage',
      name: 'Sillage',
      desc: 'Chaque ruée laisse une traînée de feu 2,5 s (25 dégâts par seconde). +10 % de vitesse.',
      rarity: 'colossal',
      category: 'mobility',
      weaponFamily: null,
      maxStacks: 1,
      mods: [{ stat: 'speed', mul: 1.1 }],
      hooks: { onDash: [{ effect: 'fire_trail', duration: 2.5, dps: 25 }] },
    },
    {
      id: 'upg_symbiose',
      name: 'Symbiose',
      desc: 'Les pièges te soignent au lieu de te blesser.',
      rarity: 'colossal',
      category: 'defense',
      weaponFamily: null,
      maxStacks: 1,
      mods: [],
      hooks: { passive: [{ effect: 'traps_heal', fraction: 1.0 }] },
    },
    {
      id: 'upg_coeur_de_verre',
      name: 'Cœur de verre',
      desc: 'Dégâts ×2, PV max ×0,5.',
      rarity: 'colossal',
      category: 'offense',
      weaponFamily: null,
      maxStacks: 1,
      mods: [],
      hooks: { passive: [{ effect: 'glass_cannon', damageMul: 2.0, hpMul: 0.5 }] },
    },
    {
      id: 'upg_resonance',
      name: 'Résonance',
      desc: 'Chaque compétence : une onde de choc de 60 dégâts à mi-salle, et un ralenti de 1,5 s.',
      rarity: 'colossal',
      category: 'special',
      weaponFamily: null,
      maxStacks: 1,
      mods: [],
      hooks: {
        onSkill: [
          { effect: 'shockwave', radius: 200, damage: 60, knockback: 3 },
          { effect: 'bullet_time_skill', duration: 1.5, scale: 0.3 },
        ],
      },
    },
  ],

  // =====================================================================
  // PASSIFS MÉTA (hub)  — 16
  // =====================================================================
  metaPassives: [
    {
      id: 'meta_vitalite',
      name: 'Vitalité',
      desc: 'PV de départ.',
      tiers: [
        { price: 20, mods: [{ stat: 'maxHp', add: 10 }], hooks: {}, special: null },
        { price: 50, mods: [{ stat: 'maxHp', add: 10 }], hooks: {}, special: null },
        { price: 90, mods: [{ stat: 'maxHp', add: 15 }], hooks: {}, special: null },
        { price: 150, mods: [{ stat: 'maxHp', add: 15 }], hooks: {}, special: null },
      ],
    },
    {
      id: 'meta_puissance',
      name: 'Puissance',
      desc: 'Dégâts de base.',
      tiers: [
        { price: 30, mods: [{ stat: 'damage', mul: 1.04 }], hooks: {}, special: null },
        { price: 50, mods: [{ stat: 'damage', mul: 1.04 }], hooks: {}, special: null },
        { price: 90, mods: [{ stat: 'damage', mul: 1.04 }], hooks: {}, special: null },
        { price: 130, mods: [{ stat: 'damage', mul: 1.05 }], hooks: {}, special: null },
        { price: 200, mods: [{ stat: 'damage', mul: 1.05 }], hooks: {}, special: null },
      ],
    },
    {
      id: 'meta_chance',
      name: 'Chance',
      desc: 'Décale les raretés vers épique et colossal.',
      tiers: [
        { price: 20, mods: [{ stat: 'luck', add: 2 }], hooks: {}, special: null },
        { price: 40, mods: [{ stat: 'luck', add: 2 }], hooks: {}, special: null },
        { price: 80, mods: [{ stat: 'luck', add: 3 }], hooks: {}, special: null },
        { price: 130, mods: [{ stat: 'luck', add: 3 }], hooks: {}, special: null },
      ],
    },
    {
      id: 'meta_cupidite',
      name: 'Cupidité',
      desc: 'Argent gagné.',
      tiers: [
        { price: 20, mods: [{ stat: 'coinGain', mul: 1.1 }], hooks: {}, special: null },
        { price: 30, mods: [{ stat: 'coinGain', mul: 1.1 }], hooks: {}, special: null },
        { price: 70, mods: [{ stat: 'coinGain', mul: 1.1 }], hooks: {}, special: null },
        { price: 120, mods: [{ stat: 'coinGain', mul: 1.15 }], hooks: {}, special: null },
      ],
    },
    {
      id: 'meta_etude',
      name: 'Étude',
      desc: 'XP gagnée.',
      tiers: [
        { price: 20, mods: [{ stat: 'xpGain', mul: 1.08 }], hooks: {}, special: null },
        { price: 30, mods: [{ stat: 'xpGain', mul: 1.08 }], hooks: {}, special: null },
        { price: 70, mods: [{ stat: 'xpGain', mul: 1.08 }], hooks: {}, special: null },
        { price: 120, mods: [{ stat: 'xpGain', mul: 1.1 }], hooks: {}, special: null },
      ],
    },
    {
      id: 'meta_reactivite',
      name: 'Réactivité',
      desc: 'Tes compétences se rechargent plus vite.',
      tiers: [
        { price: 20, mods: [{ stat: 'cooldownReduction', add: 0.05 }], hooks: {}, special: null },
        { price: 50, mods: [{ stat: 'cooldownReduction', add: 0.05 }], hooks: {}, special: null },
        { price: 90, mods: [{ stat: 'cooldownReduction', add: 0.05 }], hooks: {}, special: null },
        { price: 150, mods: [{ stat: 'cooldownReduction', add: 0.05 }], hooks: {}, special: null },
      ],
    },
    {
      id: 'meta_resurrection',
      name: 'Résurrection',
      desc: 'Une seconde vie par partie.',
      tiers: [
        { price: 40, mods: [], hooks: { passive: [{ effect: 'second_chance', hpFraction: 0.25 }] }, special: 'resurrect' },
        { price: 100, mods: [], hooks: { passive: [{ effect: 'second_chance', hpFraction: 0.4 }] }, special: 'resurrect' },
        { price: 180, mods: [], hooks: { passive: [{ effect: 'second_chance', hpFraction: 0.6 }] }, special: 'resurrect' },
      ],
    },
    {
      id: 'meta_memoire_selective',
      name: 'Mémoire sélective',
      desc: 'Le coffre de la salle 8 ne compte que tes 3 meilleures salles.',
      tiers: [{ price: 30, mods: [], hooks: {}, special: 'selective_memory' }],
    },
    {
      id: 'meta_apercu_coffre',
      name: 'Aperçu du coffre',
      desc: "Dans les salles 1 à 3, le jeu te dit quelle qualité de coffre t'attend en salle 4.",
      tiers: [{ price: 30, mods: [], hooks: {}, special: 'chest_preview' }],
    },
    {
      id: 'meta_quatrieme_choix',
      name: 'Quatrième choix',
      desc: 'Un 4e choix à chaque montée de niveau et à chaque coffre.',
      tiers: [{ price: 40, mods: [], hooks: {}, special: 'fourth_choice' }],
    },
    {
      id: 'meta_reroll',
      name: 'Relance',
      desc: 'Relancer les choix de montée de niveau.',
      tiers: [
        { price: 30, mods: [], hooks: { onLevelUp: [{ effect: 'reroll_on_levelup', count: 1 }] }, special: 'reroll' },
        { price: 70, mods: [], hooks: { onLevelUp: [{ effect: 'reroll_on_levelup', count: 1 }] }, special: 'reroll' },
        { price: 140, mods: [], hooks: { onLevelUp: [{ effect: 'reroll_on_levelup', count: 1 }] }, special: 'reroll' },
      ],
    },
    {
      id: 'meta_celerite',
      name: 'Célérité',
      desc: 'Vitesse de déplacement.',
      tiers: [
        { price: 20, mods: [{ stat: 'speed', mul: 1.04 }], hooks: {}, special: null },
        { price: 50, mods: [{ stat: 'speed', mul: 1.04 }], hooks: {}, special: null },
        { price: 100, mods: [{ stat: 'speed', mul: 1.04 }], hooks: {}, special: null },
      ],
    },
    {
      id: 'meta_carapace',
      name: 'Carapace',
      desc: 'Armure de base.',
      tiers: [
        { price: 30, mods: [{ stat: 'armor', add: 1 }], hooks: {}, special: null },
        { price: 70, mods: [{ stat: 'armor', add: 1 }], hooks: {}, special: null },
        { price: 130, mods: [{ stat: 'armor', add: 1 }], hooks: {}, special: null },
      ],
    },
    {
      id: 'meta_isolation',
      name: 'Isolation',
      desc: 'Dégâts des pièges subis.',
      tiers: [
        { price: 20, mods: [{ stat: 'trapDamageMul', mul: 0.85 }], hooks: {}, special: null },
        { price: 60, mods: [{ stat: 'trapDamageMul', mul: 0.85 }], hooks: {}, special: null },
        { price: 110, mods: [{ stat: 'trapDamageMul', mul: 0.85 }], hooks: {}, special: null },
      ],
    },
    {
      id: 'meta_aimantation',
      name: 'Aimantation',
      desc: 'Rayon de ramassage.',
      tiers: [
        { price: 20, mods: [{ stat: 'pickupRadius', add: 30 }], hooks: {}, special: null },
        { price: 30, mods: [{ stat: 'pickupRadius', add: 30 }], hooks: {}, special: null },
        { price: 70, mods: [{ stat: 'pickupRadius', add: 40 }], hooks: {}, special: null },
      ],
    },
    {
      id: 'meta_precision',
      name: 'Précision',
      desc: 'Chance de critique de base.',
      tiers: [
        { price: 20, mods: [{ stat: 'critChance', add: 0.03 }], hooks: {}, special: null },
        { price: 50, mods: [{ stat: 'critChance', add: 0.03 }], hooks: {}, special: null },
        { price: 90, mods: [{ stat: 'critChance', add: 0.03 }], hooks: {}, special: null },
        { price: 150, mods: [{ stat: 'critChance', add: 0.03 }], hooks: {}, special: null },
      ],
    },
  ],

  // =====================================================================
  // BIOMES
  // =====================================================================
  biomes: [
    {
      id: 'biome_1',
      name: 'ADMISSION',
      order: 1,
      tagline: 'Un hôpital désaffecté : couloirs étroits, néons, pièges mécaniques. Le niveau pour apprendre.',
      /* chantier 12 : la palette de l'hôpital, dite plutôt que codée en dur (bleu froid, néons cyan et orange sodium) */
      palette: {
        tint: 'rgba(40,70,110,.22)',
        neon: ['#6ee7ff', '#ff9a3c'],
        wall: 'rgba(40,70,110,.3)',
        terrain: { ledge: { fill: '#2f3a46', edge: '#9fc3c8' }, water: { fill: '#1d3550', edge: '#7fd8ff' } },
      },
      desc: "Un ancien service d'accueil réaménagé en parcours : guichets devenus couverts, bancs devenus obstacles, rails de brancards devenus rails de pièges. Néons qui clignotent, sols humides. Le premier palier : on y apprend tout.",
      levelPassives: [
        {
          bonus: { name: 'Stimulant', desc: '+15 % vitesse de déplacement.', mods: [{ stat: 'speed', mul: 1.15 }], hooks: {} },
          malus: {
            name: 'Sol instable',
            desc: 'Les pièges infligent le double de dégâts.',
            mods: [{ stat: 'trapDamageMul', mul: 2.0 }],
            hooks: {},
          },
        },
        {
          bonus: { name: 'Surcharge', desc: '+25 % dégâts.', mods: [{ stat: 'damage', mul: 1.25 }], hooks: {} },
          malus: { name: 'Fragile', desc: '-25 % PV max.', mods: [{ stat: 'maxHp', mul: 0.75 }], hooks: {} },
        },
        {
          bonus: {
            name: "Prime d'essai",
            desc: '+30 % pièces, +20 % XP.',
            mods: [
              { stat: 'coinGain', mul: 1.3 },
              { stat: 'xpGain', mul: 1.2 },
            ],
            hooks: {},
          },
          malus: {
            name: 'Peau fine',
            desc: 'Invulnérabilité après un coup réduite de 0,6 s à 0,3 s.',
            mods: [{ stat: 'invulnTime', add: -0.3 }],
            hooks: {},
          },
        },
      ],
      enemyPool: ['enemy_rodeur', 'enemy_sentinelle', 'enemy_bloc', 'enemy_meche', 'enemy_incubateur', 'enemy_nuee', 'enemy_eclipse'],
      trapPool: [
        'trap_balayage',
        'trap_tourniquet',
        'trap_grille',
        'trap_bouche',
        'trap_dalles',
        'trap_nappe',
        'trap_rail',
        'trap_tourelle',
        'trap_diffuseur',
        'trap_gyrophare',
        'trap_rayon',
      ],
      miniboss: 'boss_etalon_07',
      /* Le premier palier apprend le jeu : PV et dégâts sous la référence, montée par salle plus douce (0,06 contre
         0,09 ailleurs). Mesuré avant : 0 victoire sur 32 parties de bot, mort en salle 3 ou 5. */
      difficulty: { hpMul: 0.85, damageMul: 0.75, speedMul: 1, rampPerRoom: 0.06 },
    },
  ],

  // =====================================================================
  // ENNEMIS — biome 1
  // =====================================================================
  enemies: [
    {
      id: 'enemy_rodeur',
      name: 'Rôdeur',
      archetype: 'rusher',
      desc: "Court vers toi ; de près, il se fige 0,35 s puis bondit. Le bond s'esquive de côté.",
      hp: 43,
      speed: 200,
      damage: 9,
      radius: 14,
      xp: 4,
      coins: 1,
      color: '#c0553f', // rouge sourd : le rouge vif est réservé à l'alerte (F-3)
      behavior: { lungeRange: 90, lungeWindup: 0.35, lungeSpeed: 520, lungeDuration: 0.25, lungeCooldown: 1.2 },
      telegraph: { time: 0.35, color: '#ffd166' },
    },
    {
      id: 'enemy_sentinelle',
      name: 'Sentinelle',
      archetype: 'shooter',
      desc: 'Garde ses distances, vise 0,5 s (ligne pointillée) puis tire une balle lente de 11 dégâts.',
      hp: 36,
      speed: 130,
      damage: 9,
      radius: 14,
      xp: 6,
      coins: 2,
      color: '#4fa3e0',
      behavior: { fireRate: 0.7, projSpeed: 320, projDamage: 11, projSize: 7, keepDistance: 300, aimTime: 0.5, burst: 1 },
      telegraph: { time: 0.5, color: '#7bd3ff' },
    },
    {
      id: 'enemy_bloc',
      name: 'Bloc',
      archetype: 'tank',
      desc: "Lent et massif. S'arrête, tremble 0,8 s, puis charge en ligne droite. S'il percute un mur : étourdi 1,2 s.",
      hp: 200,
      speed: 90,
      damage: 12,
      radius: 24,
      xp: 14,
      coins: 4,
      color: '#8c6d4f',
      behavior: { chargeWindup: 0.8, chargeSpeed: 560, chargeDuration: 0.7, chargeCooldown: 3.0, stunOnWallHit: 1.2, chargeDamageMul: 1.3 },
      telegraph: { time: 0.8, color: '#ff8c42' },
    },
    {
      id: 'enemy_meche',
      name: 'Mèche',
      archetype: 'kamikaze',
      desc: "Fonce sur toi ; de près, sa mèche s'allume (0,9 s, elle clignote) puis elle explose. Tue-la loin de toi.",
      hp: 25,
      speed: 240,
      damage: 6,
      radius: 12,
      xp: 5,
      coins: 1,
      color: '#d8613f',
      behavior: { fuse: 0.9, radius: 80, explosionDamage: 24, triggerRange: 60, explodeOnDeath: true },
      telegraph: { time: 0.9, color: '#ff3b3b' },
    },
    {
      id: 'enemy_incubateur',
      name: 'Incubateur',
      archetype: 'summoner',
      desc: 'Reste loin, gonfle 0,7 s puis libère une Nuée (toutes les 4 s, 4 vivantes au plus). À abattre en premier.',
      hp: 90,
      speed: 60,
      damage: 9,
      radius: 20,
      xp: 20,
      coins: 5,
      color: '#9b6fd6',
      behavior: { summon: 'enemy_nuee', every: 4.0, max: 4, keepDistance: 350, summonWindup: 0.7 },
      telegraph: { time: 0.7, color: '#b98cff' },
    },
    {
      id: 'enemy_nuee',
      name: 'Nuée',
      archetype: 'swarm',
      desc: 'Groupe de 5 petits organismes rapides et fragiles. Tremblent 0,2 s avant de mordre. Zone et chaîne les balaient.',
      hp: 11,
      speed: 300,
      damage: 5,
      radius: 8,
      xp: 3,
      coins: 1,
      color: '#7ed957',
      behavior: { groupSize: 5, jitter: 40, biteWindup: 0.2, biteCooldown: 0.8 },
      telegraph: { time: 0.2, color: '#9cff57' },
    },
    {
      id: 'enemy_eclipse',
      name: 'Éclipse',
      archetype: 'dasher',
      desc: 'Rôde à mi-salle, se dissipe 0,45 s (silhouette) puis réapparaît et fonce sur toi. Vulnérable 0,6 s après.',
      hp: 45,
      speed: 180,
      damage: 13,
      radius: 14,
      xp: 10,
      coins: 3,
      color: '#d64fbf',
      behavior: { blinkRange: 260, blinkWindup: 0.45, blinkCooldown: 2.2, dashSpeed: 700, dashDuration: 0.3, postDashPause: 0.6 },
      telegraph: { time: 0.45, color: '#ff6bd6' },
    },
  ],

  // =====================================================================
  // BOSS — mini-boss biome 1
  // =====================================================================
  bosses: [
    {
      id: 'boss_etalon_07',
      name: 'Étalon 07, dit « le Portier »',
      desc: "Le gardien d'ADMISSION, gardé comme mètre-étalon. Vérin hydraulique au bras droit, prise à nu dans le dos. Lourd, prévisible : il faut le faire pivoter.",
      hp: 2600, // 3300 avant : le premier boss du jeu durait trop, et chaque seconde de plus coûtait des PV
      speed: 120,
      radius: 36,
      damage: 22,
      xp: 120,
      coins: 40,
      crest: 'plate',
      phases: [
        {
          hpBelow: 1.0,
          patterns: [
            /* Premier boss du jeu : ses quatre attaques se chevauchaient (recharges 2,3 / 3,4 / 4 / 5,5 s) et
               chacune coûtait un quart des PV. Recharges +30 %, dégâts −20 % : il reste lourd et prévisible,
               il laisse le temps de le lire. Mesuré avant : 7 parties de bot sur 16 meurent ici. */
            { kind: 'ring', telegraph: 0.8, duration: 0.3, cooldown: 3.0, count: 12, projSpeed: 260, projDamage: 18, projSize: 8 },
            { kind: 'charge', telegraph: 0.9, duration: 0.8, cooldown: 4.4, speed: 620, damage: 28, stopOnWall: true, stunTime: 1.5 },
            { kind: 'slam', telegraph: 1.0, duration: 0.4, cooldown: 5.2, radius: 140, damage: 26, knockback: 3.0 },
            {
              kind: 'quake',
              telegraph: 1.1,
              duration: 2.0,
              cooldown: 7.0,
              speed: 580,
              damage: 22,
              range: 900,
              color: '#9fd8ff',
              label: 'ONDE DE CHOC',
            },
          ],
        },
        {
          hpBelow: 0.5,
          patterns: [
            {
              kind: 'fan',
              telegraph: 0.6,
              duration: 0.5,
              cooldown: 1.7,
              count: 7,
              spread: 1.2,
              projSpeed: 300,
              projDamage: 22,
              projSize: 8,
            },
            {
              kind: 'spiral',
              telegraph: 0.7,
              duration: 3.0,
              cooldown: 4.0,
              arms: 2,
              rate: 12,
              angularSpeed: 2.0,
              projSpeed: 220,
              projDamage: 19,
              projSize: 7,
            },
            { kind: 'summon', telegraph: 0.8, duration: 0.5, cooldown: 6.0, enemy: 'enemy_nuee', count: 4 },
            { kind: 'charge', telegraph: 0.7, duration: 0.8, cooldown: 3.4, speed: 700, damage: 36, stopOnWall: true, stunTime: 1.5 },
            {
              kind: 'quake',
              telegraph: 0.8,
              duration: 2.0,
              cooldown: 4.5,
              speed: 700,
              damage: 28,
              range: 900,
              color: '#9fd8ff',
              label: 'ONDE DE CHOC',
            },
          ],
        },
      ],
      weakness: {
        desc: 'Sa prise de calibration dorsale est à nu : tout coup porté dans un cône de 90° derrière lui fait ×1,6 et le "débranche" 0,6 s (étourdi, ne se retourne pas). Une charge finie dans un mur (1,5 s d\'étourdissement) est le moyen le plus sûr d\'atteindre son dos.',
        rule: 'back',
        damageMul: 1.6,
        window: 0.6,
        coneAngle: 1.57,
        stunCooldown: 4.0,
      },
      revenge: {
        hpMul: 0.9,
        plateHits: 5,
        window: 0.4,
        wallStun: 0.6,
        name: 'Étalon 07 / rév. B',
        phaseText: 'DONNÉES CHARGÉES',
        mimic: true,
        /* chantier 9 : la revanche ne rejoue pas la salle 5 — le Portier reconditionné balaie au laser, sème des charges
           et ne charge qu'en seconde phase */
        phases: [
          {
            hpBelow: 1.0,
            patterns: [
              { kind: 'laser_sweep', telegraph: 1.0, duration: 2.2, cooldown: 6.0, angularSpeed: 1.4, length: 700, damage: 16 },
              {
                kind: 'mines',
                telegraph: 0.9,
                duration: 0.5,
                cooldown: 5.0,
                count: 3,
                spread: 140,
                radius: 66,
                fuse: 1.5,
                damage: 22,
                color: '#9fd8ff',
                label: 'CHARGES',
              },
              { kind: 'ring', telegraph: 0.7, duration: 0.3, cooldown: 3.2, count: 14, projSpeed: 280, projDamage: 16, projSize: 8 },
            ],
          },
          {
            hpBelow: 0.55,
            patterns: [
              { kind: 'charge', telegraph: 0.7, duration: 0.8, cooldown: 3.6, speed: 720, damage: 30, stopOnWall: true, stunTime: 1.3 },
              {
                kind: 'quake',
                telegraph: 0.9,
                duration: 2.0,
                cooldown: 5.0,
                speed: 660,
                damage: 24,
                range: 900,
                color: '#9fd8ff',
                label: 'ONDE DE CHOC',
              },
              {
                kind: 'fan',
                telegraph: 0.6,
                duration: 0.5,
                cooldown: 2.0,
                count: 9,
                spread: 1.4,
                projSpeed: 300,
                projDamage: 18,
                projSize: 8,
              },
              { kind: 'summon', telegraph: 0.8, duration: 0.5, cooldown: 7.0, enemy: 'enemy_meche', count: 2 },
            ],
          },
        ],
        extraPhases: [
          {
            hpBelow: 0.3,
            patterns: [
              { kind: 'laser_sweep', telegraph: 1.0, duration: 2.5, cooldown: 7.0, angularSpeed: 1.6, length: 700, damage: 17 },
              { kind: 'ring', telegraph: 0.5, duration: 0.3, cooldown: 2.0, count: 16, projSpeed: 300, projDamage: 13, projSize: 8 },
              { kind: 'charge', telegraph: 0.5, duration: 0.6, cooldown: 3.0, speed: 800, damage: 24, stopOnWall: false, stunTime: 1.0 },
            ],
          },
        ],
        desc: "Salle 9 : ÉTALON 07 / rév. B, reconditionné entre les salles 5 et 9. 2970 PV de base (×0,9 ; la montée de difficulté de la salle 9, ×1,72, fait le reste). Une plaque de tôle vissée à la va-vite couvre la prise dorsale : la faiblesse est inactive jusqu'à 5 impacts dans le dos, puis la plaque saute et la faiblesse revient avec une fenêtre de 0,4 s au lieu de 0,6. Ses charges ne s'arrêtent plus dans les murs (1,0 s d'étourdissement). Il a chargé vos données de consignation : en phase 2 il reproduit votre compétence de salle 1 (dash → charge courte, tourelle → summon, onde → slam, blink → téléportation dans votre dos) et ses patterns sous 30 % PV s'inspirent des greffes refusées aux level-ups (implémenté : dash → charge courte, blink → téléportation dans le dos, tourelle → summon, onde → slam, bouclier → blindage, ralenti → brouillage, aimant → aspiration, surrégime → frénésie).",
      },
    },
  ],

  // =====================================================================
  // COMPAGNONS — un animal ramassé en run, qui joue son unique tour EN MESURE
  // =====================================================================
  /* Aucun compagnon livré : ils se créent dans l'atelier « Amis » (F2) à partir d'une photo, et s'exportent
     dans dev/content5.js. Les comportements disponibles sont listés dans PET_BEHAVIORS (31_pets.js). */
  pets: [],
  /* Paires connues : un personnage et l'animal qui est vraiment le sien. Les deux y gagnent — c'est ce qui
     transforme « quel compagnon est le meilleur » en « quelle équipe est la meilleure ». */
  pairs: [],
  petsExemples: [
    {
      id: 'pet_faucon',
      name: 'Faucon',
      sprite: 'falcon-moon',
      color: '#9fd8ff',
      tag: 'pique toutes les 2 mesures',
      desc: "Il pique sur l'ennemi le plus proche toutes les deux mesures, et rien ne l'arrête en vol.",
      behavior: 'strike',
      fly: true,
      damage: 26,
      every: 8,
      range: 360,
      speed: 300,
      diveSpeed: 660,
      knockback: 1.4,
      size: 32,
      price: 260,
    },
    {
      id: 'pet_chien',
      name: 'Chien de garde',
      sprite: 'sniffing-dog',
      color: '#d8b46a',
      tag: 'mord et attire les coups',
      desc: "Il court au contact et mord à chaque temps fort. Les ennemis proches s'en prennent à lui plutôt qu'à toi.",
      behavior: 'bite',
      damage: 14,
      every: 4,
      range: 280,
      speed: 320,
      knockback: 2,
      taunt: 230,
      hp: 90,
      revive: 6,
      size: 34,
      price: 240,
    },
    {
      id: 'pet_serpent',
      name: 'Serpent cracheur',
      sprite: 'snake',
      color: '#9ade6a',
      tag: 'crache sur chaque temps',
      desc: "Il reste dans tes jambes et crache une gerbe de venin sur chaque temps, sur l'ennemi le plus proche.",
      behavior: 'spit',
      damage: 9,
      every: 2,
      range: 340,
      speed: 250,
      projSpeed: 480,
      projSize: 5,
      size: 30,
      price: 220,
    },
    {
      id: 'pet_scarabee',
      name: 'Scarabée fouineur',
      sprite: 'scarab-beetle',
      color: '#c9a3ff',
      tag: 'va chercher ce qui traîne',
      desc: 'Tout ce qui traîne à portée vient à toi : crédits, cœurs, fragments. Il ne se bat pas.',
      behavior: 'collect',
      damage: 0,
      every: 4,
      radius: 260,
      speed: 280,
      size: 28,
      price: 120,
      unlocked: true,
    },
    {
      id: 'pet_tortue',
      name: 'Tortue bouclier',
      sprite: 'turtle',
      color: '#6ee7ff',
      tag: 'brise 2 tirs par temps',
      desc: "Elle tourne autour de toi et brise les projectiles ennemis qu'elle croise — deux par temps.",
      behavior: 'guard',
      damage: 0,
      every: 1,
      block: 2,
      dist: 56,
      spin: 1.7,
      size: 30,
      price: 280,
    },
    {
      id: 'pet_crapaud',
      name: 'Crapaud guérisseur',
      sprite: 'frog',
      color: '#7fff9a',
      tag: 'soigne sur le temps fort',
      desc: "Il souffle un peu de vie à chaque temps fort. Lent, mais il ne s'arrête jamais.",
      behavior: 'mend',
      damage: 0,
      every: 4,
      heal: 4,
      speed: 230,
      size: 30,
      price: 300,
    },
    {
      id: 'pet_tatou',
      name: 'Tatou blindé',
      sprite: 'armadillo',
      color: '#b0a08a',
      tag: 'traverse la salle sur le temps fort',
      desc: 'Il se met en boule et traverse la salle en ligne droite à chaque temps fort, bousculant tout sur son passage.',
      behavior: 'charge',
      damage: 18,
      every: 4,
      range: 420,
      speed: 240,
      rollSpeed: 560,
      rollTime: 0.8,
      knockback: 3,
      size: 32,
      price: 260,
    },
    {
      id: 'pet_chouette',
      name: 'Chouette guetteuse',
      sprite: 'owl',
      color: '#d8c9a0',
      tag: 'désigne une cible à chaque mesure',
      desc: "Elle désigne un ennemi à chaque mesure : il encaisse 30 % de dégâts en plus tant qu'il est marqué.",
      behavior: 'mark',
      fly: true,
      damage: 0,
      every: 4,
      range: 420,
      markTime: 4,
      markMul: 1.3,
      speed: 280,
      size: 30,
      price: 320,
    },
    {
      id: 'pet_abeille',
      name: 'Abeille',
      sprite: 'bee',
      color: '#ffd166',
      tag: 'pique sur chaque temps',
      desc: "Elle tourne autour de l'ennemi le plus proche et pique sans relâche. Peu de dégâts, mais jamais de pause.",
      behavior: 'sting',
      fly: true,
      damage: 5,
      every: 1,
      range: 320,
      speed: 440,
      orbit: 26,
      spin: 5,
      size: 24,
      price: 200,
    },
  ],
  friendsNote: "petsExemples n'est pas chargé : ce sont des gabarits, pas du contenu.",

  // =====================================================================
  // PIÈGES — biome 1 (8 kinds)
  // =====================================================================
  traps: [
    {
      id: 'trap_balayage',
      name: 'Balayage laser',
      color: '#6ee7ff',
      kind: 'laser_sweep',
      desc: 'Un rayon vertical parcourt la zone de gauche à droite en 1,6 s, puis revient au cycle suivant.',
      damage: 15,
      telegraph: 0.8,
      period: 5.0,
      active: 1.6,
      params: { orientation: 'vertical', pingpong: true, thickness: 0.5, hitOnce: true },
    },
    {
      id: 'trap_tourniquet',
      name: 'Tourniquet',
      color: '#9fd8ff',
      kind: 'laser_rotate',
      desc: '2 bras laser de 5 tuiles tournent (1,2 rad/s). Pause de 1 s tous les 6 s : la fenêtre pour traverser.',
      damage: 13,
      telegraph: 1.0,
      period: 6.0,
      active: 5.0,
      params: { arms: 2, lengthTiles: 5, angularSpeed: 1.2, startAngle: 0, thickness: 0.4 },
    },
    {
      id: 'trap_grille',
      name: 'Grille',
      color: '#6ee7ff',
      kind: 'laser_grid',
      desc: 'Lignes laser espacées de 4 tuiles. Cycles alternés : verticales puis horizontales. 1 s allumé, 2 s éteint.',
      damage: 11,
      telegraph: 0.5,
      period: 3.0,
      active: 1.0,
      params: { spacingTiles: 4, alternate: true, thickness: 0.3 },
    },
    {
      id: 'trap_bouche',
      name: 'Bouche de feu',
      color: '#ff9a3c',
      kind: 'wall_fireball',
      desc: 'Une bouche murale crache une boule de feu droite toutes les 2,5 s. Se décale avec phase.',
      damage: 13,
      telegraph: 0.6,
      period: 2.5,
      active: 0.2,
      params: { dir: 'down', projSpeed: 320, size: 12, count: 1, lifetime: 3.0 },
    },
    {
      id: 'trap_dalles',
      name: 'Dalles à pointes',
      color: '#aab4c8',
      kind: 'spike_tiles',
      desc: 'Damier : les cases paires sortent leurs pointes 0,8 s, puis les impaires. Toujours une case sûre à côté.',
      damage: 11,
      telegraph: 0.5,
      period: 2.6,
      active: 0.8,
      params: { pattern: 'checker', groups: 2, hitOnce: true },
    },
    {
      id: 'trap_nappe',
      name: 'Nappe de gaz',
      color: '#9fe0b0',
      kind: 'gas_zone',
      desc: 'Une bouche siffle 1,2 s puis libère un nuage de 2,5 tuiles pendant 3 s : 9 dégâts/s et -30 % vitesse.',
      damage: 9,
      telegraph: 1.2,
      period: 7.0,
      active: 3.0,
      params: { radiusTiles: 2.5, tickRate: 4, slow: 0.3, dps: true },
    },
    {
      id: 'trap_rail',
      name: 'Scie sur rail',
      color: '#c8d0e0',
      kind: 'saw_rail',
      desc: 'Scie circulaire qui fait des allers-retours sur un rail de 8 tuiles à 6 tuiles/s. Jamais de pause.',
      damage: 20,
      telegraph: 0.4,
      period: 3.2,
      active: 3.2,
      params: { axis: 'x', lengthTiles: 8, speedTiles: 6, pingpong: true, radiusTiles: 0.6, hitOnce: true },
    },
    {
      id: 'trap_diffuseur',
      name: 'Diffuseur',
      kind: 'emitter',
      desc: 'Bouche circulaire : une couronne de 8 billes part dans toutes les directions à chaque coup.',
      damage: 11,
      telegraph: 0.7,
      period: 3.0,
      active: 0.3,
      color: '#6ee7ff',
      params: { pattern: 'ring', count: 8, arc: 6.2832, speed: 210, size: 7, lifetime: 4 },
    },
    {
      id: 'trap_gyrophare',
      name: 'Gyrophare',
      kind: 'emitter',
      desc: "Canon rotatif : 3 bras de billes qui tournent d'un huitième de tour à chaque coup — une spirale se dessine.",
      damage: 10,
      telegraph: 0.6,
      period: 2.0,
      active: 0.3,
      color: '#c9a3ff',
      params: { pattern: 'spiral', count: 3, arc: 6.2832, spin: 0.7854, speed: 230, size: 6, lifetime: 5 },
    },
    {
      id: 'trap_rayon',
      name: 'Rayon mural',
      kind: 'laser_beam',
      desc: "Un rayon fixe traverse la salle depuis le mur. Il s'allume et s'éteint franchement : on passe entre deux.",
      damage: 16,
      telegraph: 0.6,
      period: 3.0,
      active: 1.0,
      color: '#ff5e7a',
      params: { angle: 0, length: 26, thickness: 0.4 },
    },
    {
      id: 'trap_tourelle',
      name: 'Tourelle fixe',
      color: '#ff9a3c',
      kind: 'turret_fixed',
      desc: 'Tourelle murale : 0,7 s de visée (rayon rouge) puis 1 balle vers le joueur toutes les 2,4 s. Destructible ? Non.',
      damage: 10,
      telegraph: 0.7,
      period: 2.4,
      active: 0.3,
      params: { mode: 'aim', angle: 0, projSpeed: 380, count: 1, spread: 0, projSize: 6 },
    },
  ],

  // =====================================================================
  // SALLES — biome 1 (grille 24×13, x 0..23, y 0..12 ; entrée à gauche x=0 y=6, sortie à droite x=23 y=6)
  // =====================================================================
  rooms: [
    // ---------- SALLE 1 : PRÉPARATION + COMBAT ----------
    {
      id: 'room_b1_1',
      biome: 'biome_1',
      index: 1,
      type: 'PREP_COMBAT',
      refTime: 45,
      obstacles: [
        { x: 6, y: 3, w: 1, h: 1, kind: 'locker' },
        { x: 6, y: 9, w: 1, h: 1, kind: 'machine' },
        { x: 17, y: 3, w: 1, h: 1, kind: 'locker' },
        { x: 17, y: 9, w: 1, h: 1, kind: 'machine' },
        { x: 11, y: 6, w: 2, h: 1, kind: 'bin' },
      ],
      /* chantier 12 D : deux guichets en travers — on ne les enjambe pas (sauf en ruée), les balles passent */
      /* chantier 12 D : quatre bancs de salle d’attente, on tourne autour */
      /* chantier 12 D : des flaques qui brillent dans le noir, où l’on ralentit */
      terrain: [
        '........................',
        '........................',
        '........................',
        '........nnnnnn..........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '..........nnnnnn........',
        '........................',
        '........................',
        '........................',
      ],
      deco: [
        { x: 3, y: 2, kind: 'cross' },
        { x: 20, y: 10, kind: 'hazard' },
        { x: 2, y: 10, kind: 'pack' },
        { x: 8, y: 2, kind: 'stool' },
        { x: 15, y: 10, kind: 'stool' },
        { x: 7, y: 0, kind: 'stool' },
        { x: 17, y: 6, kind: 'bin' },
        { x: 10, y: 2, kind: 'battery' },
        { x: 18, y: 0, kind: 'tubes' },
        { x: 14, y: 12, kind: 'fan', big: true },
        { x: 9, y: 12, kind: 'valve' },
        { x: 16, y: 12, kind: 'pack' },
        { x: 10, y: 11, kind: 'bin' },
        { x: 12, y: 2, kind: 'battery', big: true },
        { x: 19, y: 7, kind: 'tubes' },
      ],
      waves: [
        {
          at: 'start',
          spawns: [
            { enemy: 'enemy_rodeur', count: 2, x: 20, y: 3 },
            { enemy: 'enemy_rodeur', count: 1, x: 20, y: 9 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_rodeur', count: 3, x: -1, y: -1 },
            { enemy: 'enemy_sentinelle', count: 1, x: 21, y: 6 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_nuee', count: 1, x: 21, y: 2 },
            { enemy: 'enemy_sentinelle', count: 2, x: 21, y: 10 },
            { enemy: 'enemy_rodeur', count: 2, x: 2, y: 1 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_rodeur', count: 3, x: -1, y: -1 },
            { enemy: 'enemy_nuee', count: 1, x: 2, y: 11 },
            { enemy: 'enemy_sentinelle', count: 1, x: 21, y: 6 },
            { enemy: 'enemy_eclipse', count: 1, x: 12, y: 1 },
          ],
        },
      ],
      traps: [],
      fragments: [],
      /* salle cadencée (chantier 9) : le carrelage de l'accueil s'allume en damier sur chaque temps, les néons battent sur le temps fort */
      anims: [
        {
          kind: 'tile_color',
          x: 9,
          y: 4,
          w: 6,
          h: 5,
          params: { mode: 'checker', color: '#6ee7ff', color2: '#ff9a3c' },
          beats: { bars: 1, hits: [0, 1, 2, 3], active: 0.6 },
        },
        {
          kind: 'light',
          x: 1,
          y: 1,
          w: 2,
          h: 2,
          params: { radius: 2.5, base: 0.4, gain: 0.25, color: '#6ee7ff' },
          beats: { bars: 1, hits: [0], active: 2 },
        },
        {
          kind: 'light',
          x: 20,
          y: 1,
          w: 2,
          h: 2,
          params: { radius: 2.5, base: 0.4, gain: 0.25, color: '#ff9a3c' },
          beats: { bars: 1, hits: [2], active: 2 },
        },
        {
          kind: 'light',
          x: 1,
          y: 9,
          w: 2,
          h: 2,
          params: { radius: 2.5, base: 0.4, gain: 0.25, color: '#ff9a3c' },
          beats: { bars: 1, hits: [2], active: 2 },
        },
        {
          kind: 'light',
          x: 20,
          y: 9,
          w: 2,
          h: 2,
          params: { radius: 2.5, base: 0.4, gain: 0.25, color: '#6ee7ff' },
          beats: { bars: 1, hits: [0], active: 2 },
        },
      ],
      modular: [],
    },

    // ---------- SALLE 2 : PIÈGES + FRAGMENTS D'ÉNERGIE ----------
    {
      id: 'room_b1_2',
      biome: 'biome_1',
      index: 2,
      type: 'COMBAT_CHALLENGE',
      refTime: 70,
      obstacles: [
        { x: 6, y: 4, w: 1, h: 1, kind: 'counter' },
        { x: 17, y: 4, w: 1, h: 1, kind: 'counter' },
        { x: 6, y: 8, w: 1, h: 1, kind: 'counter' },
        { x: 17, y: 8, w: 1, h: 1, kind: 'counter' },
      ],
      terrain: [
        '........................',
        '........................',
        '........................',
        '....nnnn........nnnn....',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '....nnnn........nnnn....',
        '........................',
        '........................',
        '........................',
      ],
      deco: [
        { x: 20, y: 3, kind: 'cross' },
        { x: 3, y: 6, kind: 'pack' },
        { x: 12, y: 10, kind: 'hazard' },
        { x: 9, y: 3, kind: 'stool' },
        { x: 14, y: 9, kind: 'stool' },
        { x: 9, y: 5, kind: 'hazard', big: true },
        { x: 18, y: 6, kind: 'cog' },
        { x: 13, y: 7, kind: 'bin' },
        { x: 5, y: 2, kind: 'fan' },
        { x: 18, y: 0, kind: 'pack' },
        { x: 10, y: 2, kind: 'bin' },
        { x: 14, y: 4, kind: 'fan' },
        { x: 18, y: 12, kind: 'battery', big: true },
        { x: 19, y: 7, kind: 'hazard', big: true },
        { x: 17, y: 7, kind: 'tubes' },
        { x: 6, y: 11, kind: 'battery' },
        { x: 5, y: 0, kind: 'battery' },
      ],
      waves: [
        {
          at: 'start',
          spawns: [
            { enemy: 'enemy_rodeur', count: 3, x: 20, y: 4 },
            { enemy: 'enemy_sentinelle', count: 1, x: 21, y: 8 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_nuee', count: 1, x: 21, y: 2 },
            { enemy: 'enemy_rodeur', count: 2, x: -1, y: -1 },
            { enemy: 'enemy_meche', count: 1, x: 2, y: 11 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_sentinelle', count: 2, x: 21, y: 6 },
            { enemy: 'enemy_rodeur', count: 3, x: -1, y: -1 },
            { enemy: 'enemy_eclipse', count: 1, x: 12, y: 1 },
          ],
        },
      ],
      traps: [],
      fragments: [],
      /* salle cadencée : une onde part du centre sur le temps fort, une couronne de dalles se soulève un temps sur deux */
      anims: [
        { kind: 'ring', x: 11, y: 6, w: 2, h: 1, params: { radius: 6, color: '#6ee7ff' }, beats: { bars: 1, hits: [0], active: 1.5 } },
        {
          kind: 'tile_lift',
          x: 0,
          y: 0,
          params: {
            mode: 'checker',
            amp: 6,
            color: '#8a94b0',
            cells: [
              [8, 3],
              [9, 3],
              [14, 3],
              [15, 3],
              [8, 9],
              [9, 9],
              [14, 9],
              [15, 9],
              [6, 6],
              [17, 6],
            ],
          },
          beats: { bars: 1, hits: [0, 2], active: 1 },
        },
        {
          kind: 'light',
          x: 11,
          y: 0,
          w: 2,
          h: 2,
          params: { radius: 3, base: 0.35, gain: 0.25, color: '#6ee7ff' },
          beats: { bars: 1, hits: [0], active: 2 },
        },
        {
          kind: 'light',
          x: 11,
          y: 11,
          w: 2,
          h: 2,
          params: { radius: 3, base: 0.35, gain: 0.25, color: '#ff9a3c' },
          beats: { bars: 1, hits: [2], active: 2 },
        },
      ],
      modular: [],
    },

    // ---------- SALLE 3 : COMBAT + PIÈGES ----------
    {
      id: 'room_b1_3',
      biome: 'biome_1',
      index: 3,
      type: 'COMBAT_TRAP',
      chest: true, // coffre offert en fin de salle (chantier 9)
      refTime: 75,
      obstacles: [
        { x: 4, y: 2, w: 2, h: 1, kind: 'drip' },
        { x: 4, y: 10, w: 2, h: 1, kind: 'tank' },
        { x: 18, y: 2, w: 2, h: 1, kind: 'drip' },
        { x: 18, y: 10, w: 2, h: 1, kind: 'tank' },
      ],
      deco: [
        { x: 2, y: 6, kind: 'tubes' },
        { x: 21, y: 8, kind: 'battery' },
        { x: 9, y: 12, kind: 'battery', big: true },
        { x: 17, y: 8, kind: 'valve' },
        { x: 7, y: 0, kind: 'pack' },
        { x: 16, y: 3, kind: 'battery' },
        { x: 14, y: 11, kind: 'cross' },
        { x: 3, y: 11, kind: 'pack', big: true },
        { x: 19, y: 12, kind: 'tubes' },
        { x: 19, y: 8, kind: 'hazard', big: true },
        { x: 17, y: 10, kind: 'battery' },
        { x: 16, y: 9, kind: 'battery', big: true },
        { x: 18, y: 9, kind: 'tubes', big: true },
        { x: 3, y: 9, kind: 'cog' },
      ],
      waves: [
        {
          at: 'start',
          spawns: [
            { enemy: 'enemy_rodeur', count: 3, x: 20, y: 6 },
            { enemy: 'enemy_sentinelle', count: 2, x: 21, y: 2 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_bloc', count: 1, x: 21, y: 6 },
            { enemy: 'enemy_rodeur', count: 4, x: -1, y: -1 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_meche', count: 2, x: 2, y: 1 },
            { enemy: 'enemy_sentinelle', count: 2, x: 21, y: 10 },
            { enemy: 'enemy_nuee', count: 1, x: 21, y: 2 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_eclipse', count: 1, x: 21, y: 6 },
            { enemy: 'enemy_rodeur', count: 3, x: -1, y: -1 },
            { enemy: 'enemy_sentinelle', count: 1, x: 12, y: 11 },
          ],
        },
      ],
      traps: [
        { trap: 'trap_tourniquet', x: 11, y: 6, params: { beats: { turn: 4, period: 8, active: 6, telegraph: 2, on: 0 } } },
        { trap: 'trap_dalles', x: 1, y: 1, w: 3, h: 3, phase: 0 },
        { trap: 'trap_rail', x: 7, y: 3, w: 8, phase: 0 },
        { trap: 'trap_rail', x: 7, y: 9, w: 8, phase: 1.6 },
        { trap: 'trap_tourelle', x: 11, y: 0, phase: 0 },
      ],
      fragments: [],
      /* salle cadencée : un balayage de dalles traverse la salle à chaque mesure, dans le sens du tourniquet ; les néons s'alternent */
      anims: [
        {
          kind: 'tile_color',
          x: 3,
          y: 5,
          w: 18,
          h: 3,
          params: { mode: 'sweep', color: '#ffd166', color2: '#6ee7ff' },
          beats: { bars: 2, hits: [0, 4], active: 3 },
        },
        {
          kind: 'light',
          x: 1,
          y: 5,
          w: 2,
          h: 2,
          params: { radius: 2.5, base: 0.4, gain: 0.25, color: '#ffd166' },
          beats: { bars: 1, hits: [0], active: 2 },
        },
        {
          kind: 'light',
          x: 20,
          y: 5,
          w: 2,
          h: 2,
          params: { radius: 2.5, base: 0.4, gain: 0.25, color: '#6ee7ff' },
          beats: { bars: 1, hits: [2], active: 2 },
        },
      ],
      modular: [],
    },

    // ---------- SALLE 5 : MINI-BOSS ----------
    {
      id: 'room_b1_5',
      biome: 'biome_1',
      index: 5,
      type: 'MINIBOSS',
      refTime: 120,
      obstacles: [
        { x: 5, y: 3, w: 2, h: 2, kind: 'boiler' },
        { x: 17, y: 3, w: 2, h: 2, kind: 'boiler' },
        { x: 5, y: 8, w: 2, h: 2, kind: 'boiler' },
        { x: 17, y: 8, w: 2, h: 2, kind: 'boiler' },
      ],
      deco: [
        { x: 11, y: 2, kind: 'hazard' },
        { x: 11, y: 10, kind: 'hazard' },
        { x: 13, y: 3, kind: 'stool' },
        { x: 4, y: 11, kind: 'fan' },
        { x: 4, y: 0, kind: 'stool' },
        { x: 3, y: 9, kind: 'battery' },
        { x: 15, y: 0, kind: 'bin', big: true },
        { x: 16, y: 5, kind: 'bin' },
        { x: 11, y: 7, kind: 'stool', big: true },
        { x: 14, y: 6, kind: 'pack' },
        { x: 19, y: 2, kind: 'pack' },
        { x: 8, y: 11, kind: 'valve' },
        { x: 7, y: 0, kind: 'cog', big: true },
        { x: 4, y: 6, kind: 'valve' },
      ],
      waves: [{ at: 'start', spawns: [{ enemy: 'boss_etalon_07', count: 1, x: 18, y: 6 }] }],
      traps: [],
      fragments: [],
      modular: [],
    },

    {
      id: 'room_b1_6',
      biome: 'biome_1',
      index: 6,
      type: 'COMBAT_MODULAR',
      refTime: 80,
      obstacles: [{ x: 11, y: 5, w: 2, h: 3, kind: 'fuel' }],
      deco: [
        { x: 7, y: 8, kind: 'bin', big: true },
        { x: 14, y: 12, kind: 'stool' },
        { x: 7, y: 5, kind: 'bin', big: true },
        { x: 17, y: 3, kind: 'fan' },
        { x: 7, y: 11, kind: 'cog' },
        { x: 10, y: 12, kind: 'hazard' },
        { x: 6, y: 7, kind: 'stool' },
        { x: 17, y: 10, kind: 'bin', big: true },
        { x: 7, y: 2, kind: 'fan' },
        { x: 6, y: 10, kind: 'stool', big: true },
        { x: 5, y: 8, kind: 'hazard', big: true },
        { x: 17, y: 7, kind: 'fan' },
      ],
      waves: [
        {
          at: 'start',
          spawns: [
            { enemy: 'enemy_eclipse', count: 2, x: -1, y: -1 },
            { enemy: 'enemy_sentinelle', count: 2, x: -1, y: -1 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_incubateur', count: 1, x: 21, y: 6 },
            { enemy: 'enemy_rodeur', count: 4, x: -1, y: -1 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_bloc', count: 2, x: -1, y: -1 },
            { enemy: 'enemy_meche', count: 3, x: -1, y: -1 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_eclipse', count: 2, x: -1, y: -1 },
            { enemy: 'enemy_sentinelle', count: 2, x: -1, y: -1 },
            { enemy: 'enemy_nuee', count: 2, x: -1, y: -1 },
          ],
        },
      ],
      traps: [],
      fragments: [],
      /* salle cadencée : quatre ventilateurs tournent d'un quart de tour à chaque temps, une valve saute sur les temps forts */
      anims: [
        {
          kind: 'spinner',
          x: 1,
          y: 0,
          params: { sprite: 'computer-fan', scale: 1.2 },
          beats: { bars: 1, hits: [0, 1, 2, 3], active: 0.5 },
        },
        {
          kind: 'spinner',
          x: 22,
          y: 0,
          params: { sprite: 'computer-fan', scale: 1.2, step: -1.5707963 },
          beats: { bars: 1, hits: [0, 1, 2, 3], active: 0.5 },
        },
        {
          kind: 'spinner',
          x: 1,
          y: 12,
          params: { sprite: 'computer-fan', scale: 1.2, step: -1.5707963 },
          beats: { bars: 1, hits: [0, 1, 2, 3], active: 0.5 },
        },
        {
          kind: 'spinner',
          x: 22,
          y: 12,
          params: { sprite: 'computer-fan', scale: 1.2 },
          beats: { bars: 1, hits: [0, 1, 2, 3], active: 0.5 },
        },
        { kind: 'bouncer', x: 11, y: 11, params: { sprite: 'valve', amp: 14 }, beats: { bars: 1, hits: [0, 2], active: 0.8 } },
        {
          kind: 'light',
          x: 11,
          y: 0,
          w: 2,
          h: 2,
          params: { radius: 3, base: 0.35, gain: 0.25, color: '#6ee7ff' },
          beats: { bars: 1, hits: [0], active: 2 },
        },
        {
          kind: 'light',
          x: 11,
          y: 11,
          w: 2,
          h: 2,
          params: { radius: 3, base: 0.35, gain: 0.25, color: '#ff9a3c' },
          beats: { bars: 1, hits: [2], active: 2 },
        },
      ],
      modular: [
        { kind: 'slide_wall', x: 3, y: 1, w: 1, h: 4, dx: 0, dy: 7, period: 8, phase: 0 },
        { kind: 'slide_wall', x: 20, y: 8, w: 1, h: 4, dx: 0, dy: -7, period: 8, phase: 4 },
        { kind: 'rotor', cx: 12, cy: 6.5, arms: 2, length: 4, angularSpeed: 0.55 },
        {
          kind: 'floor_cycle',
          period: 10,
          telegraph: 1.5,
          configs: [
            [
              { x: 7, y: 3, w: 1, h: 1 },
              { x: 16, y: 3, w: 1, h: 1 },
              { x: 7, y: 9, w: 1, h: 1 },
              { x: 16, y: 9, w: 1, h: 1 },
            ],
            [
              { x: 5, y: 6, w: 2, h: 1 },
              { x: 17, y: 6, w: 2, h: 1 },
              { x: 11, y: 1, w: 2, h: 1 },
              { x: 11, y: 11, w: 2, h: 1 },
            ],
          ],
        },
      ],
    },
    {
      id: 'room_b1_7',
      biome: 'biome_1',
      index: 7,
      type: 'COMBAT_TEMPO',
      chest: true, // coffre offert en fin de salle (chantier 9)
      refTime: 95,
      obstacles: [
        { x: 5, y: 3, w: 1, h: 1, kind: 'bin' },
        { x: 18, y: 3, w: 1, h: 1, kind: 'bin' },
        { x: 5, y: 9, w: 1, h: 1, kind: 'bin' },
        { x: 18, y: 9, w: 1, h: 1, kind: 'bin' },
      ],
      deco: [
        { x: 15, y: 10, kind: 'hazard' },
        { x: 13, y: 1, kind: 'cross' },
        { x: 9, y: 5, kind: 'valve' },
        { x: 8, y: 8, kind: 'cross' },
        { x: 13, y: 7, kind: 'cross' },
        { x: 16, y: 8, kind: 'bin' },
        { x: 13, y: 5, kind: 'hazard' },
        { x: 12, y: 8, kind: 'cog' },
        { x: 16, y: 0, kind: 'bin' },
        { x: 8, y: 6, kind: 'cog' },
        { x: 7, y: 4, kind: 'tubes' },
        { x: 5, y: 12, kind: 'tubes' },
      ],
      waves: [
        {
          at: 'start',
          spawns: [
            { enemy: 'enemy_rodeur', count: 3, x: -1, y: -1 },
            { enemy: 'enemy_sentinelle', count: 2, x: -1, y: -1 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_meche', count: 3, x: -1, y: -1 },
            { enemy: 'enemy_rodeur', count: 2, x: -1, y: -1 },
            { enemy: 'enemy_sentinelle', count: 2, x: -1, y: -1 },
            { enemy: 'enemy_eclipse', count: 1, x: -1, y: -1 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_sentinelle', count: 3, x: -1, y: -1 },
            { enemy: 'enemy_rodeur', count: 2, x: -1, y: -1 },
            { enemy: 'enemy_meche', count: 2, x: -1, y: -1 },
            { enemy: 'enemy_eclipse', count: 1, x: -1, y: -1 },
          ],
        },
      ],
      /* cadences en temps musicaux (4 temps par mesure) : on = temps du cycle où le piège frappe */
      traps: [
        { trap: 'trap_dalles', x: 2, y: 2, w: 4, h: 3, params: { beats: { period: 4, active: 0.5, telegraph: 1, on: 0 } } },
        { trap: 'trap_dalles', x: 18, y: 8, w: 4, h: 3, params: { beats: { period: 4, active: 0.5, telegraph: 1, on: 0 } } },
        { trap: 'trap_dalles', x: 18, y: 2, w: 4, h: 3, params: { beats: { period: 4, active: 0.5, telegraph: 1, on: 2 } } },
        { trap: 'trap_dalles', x: 2, y: 8, w: 4, h: 3, params: { beats: { period: 4, active: 0.5, telegraph: 1, on: 2 } } },
        { trap: 'trap_bouche', x: 11, y: 0, params: { dir: 'down', beats: { every: 8, telegraph: 1, on: 1 } } },
        { trap: 'trap_bouche', x: 12, y: 12, params: { dir: 'up', beats: { every: 8, telegraph: 1, on: 5 } } },
        { trap: 'trap_grille', x: 2, y: 1, w: 20, h: 11, params: { beats: { period: 16, active: 1, telegraph: 3, on: 0 } } },
        { trap: 'trap_diffuseur', x: 0, y: 2, params: { beats: { every: 8, telegraph: 1, on: 3 } } },
        { trap: 'trap_gyrophare', x: 11, y: 6, params: { beats: { every: 4, telegraph: 1, on: 0 } } },
        { trap: 'trap_tourelle', x: 23, y: 10, params: { beats: { every: 8, telegraph: 1, on: 7 } } },
      ],
      fragments: [],
      modular: [],
    },
    {
      id: 'room_b1_9',
      biome: 'biome_1',
      index: 9,
      type: 'BOSS_REVENGE',
      refTime: 150,
      obstacles: [
        { x: 5, y: 3, w: 2, h: 2, kind: 'boiler' },
        { x: 17, y: 3, w: 2, h: 2, kind: 'tank' },
        { x: 5, y: 8, w: 2, h: 2, kind: 'tank' },
        { x: 17, y: 8, w: 2, h: 2, kind: 'boiler' },
      ],
      anims: [
        {
          kind: 'light',
          x: 1,
          y: 1,
          w: 2,
          h: 2,
          params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#ff9a3c' },
          beats: { bars: 1, hits: [0], active: 2 },
        },
        {
          kind: 'light',
          x: 21,
          y: 1,
          w: 2,
          h: 2,
          params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#ff9a3c' },
          beats: { bars: 1, hits: [2], active: 2 },
        },
        {
          kind: 'light',
          x: 1,
          y: 10,
          w: 2,
          h: 2,
          params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#ff9a3c' },
          beats: { bars: 1, hits: [2], active: 2 },
        },
        {
          kind: 'light',
          x: 21,
          y: 10,
          w: 2,
          h: 2,
          params: { radius: 2.5, base: 0.3, gain: 0.3, color: '#ff9a3c' },
          beats: { bars: 1, hits: [0], active: 2 },
        },
      ],
      deco: [
        { x: 11, y: 2, kind: 'hazard' },
        { x: 2, y: 1, kind: 'cross' },
        { x: 21, y: 11, kind: 'pack' },
        { x: 18, y: 1, kind: 'stool' },
        { x: 12, y: 8, kind: 'tubes' },
        { x: 14, y: 5, kind: 'battery', big: true },
        { x: 7, y: 6, kind: 'tubes' },
        { x: 16, y: 6, kind: 'tubes' },
        { x: 19, y: 2, kind: 'pack' },
        { x: 15, y: 12, kind: 'battery' },
        { x: 12, y: 4, kind: 'pack', big: true },
        { x: 15, y: 3, kind: 'cross' },
        { x: 6, y: 1, kind: 'fan' },
        { x: 19, y: 10, kind: 'bin' },
        { x: 14, y: 2, kind: 'cross', big: true },
      ],
      waves: [{ at: 'start', spawns: [{ enemy: 'boss_etalon_07', count: 1, x: 18, y: 6 }] }],
      traps: [
        { trap: 'trap_tourelle', x: 11, y: 0, phase: 0 },
        { trap: 'trap_tourelle', x: 12, y: 12, phase: 1.2 },
      ],
      fragments: [],
      modular: [],
    },
    // ---------- SALLE 4 : LE SOUS-SOL (unique au biome 1) — piliers et conduites, lumières coupées ----------
    {
      id: 'room_b1_4',
      biome: 'biome_1',
      index: 4,
      type: 'SOUS_SOL',
      refTime: 80,
      obstacles: [
        { x: 4, y: 1, w: 1, h: 2, kind: 'tank' },
        { x: 8, y: 1, w: 1, h: 2, kind: 'tank' },
        { x: 12, y: 1, w: 1, h: 2, kind: 'tank' },
        { x: 16, y: 1, w: 1, h: 2, kind: 'tank' },
        { x: 20, y: 1, w: 1, h: 2, kind: 'tank' },
        { x: 4, y: 10, w: 1, h: 2, kind: 'tank' },
        { x: 8, y: 10, w: 1, h: 2, kind: 'tank' },
        { x: 12, y: 10, w: 1, h: 2, kind: 'tank' },
        { x: 16, y: 10, w: 1, h: 2, kind: 'tank' },
        { x: 20, y: 10, w: 1, h: 2, kind: 'tank' },
        { x: 7, y: 5, w: 2, h: 3, kind: 'fuel' },
        { x: 15, y: 5, w: 2, h: 3, kind: 'fuel' },
      ],
      terrain: [
        '........................',
        '........................',
        '........................',
        '........................',
        '.....~~...........~~....',
        '.....~~...........~~....',
        '............~~~.........',
        '............~~~.........',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
      ],
      deco: [
        { x: 2, y: 6, kind: 'valve' },
        { x: 11, y: 3, kind: 'cog' },
        { x: 11, y: 9, kind: 'battery' },
        { x: 18, y: 0, kind: 'cross', big: true },
        { x: 11, y: 5, kind: 'pack' },
        { x: 7, y: 0, kind: 'fan' },
        { x: 19, y: 8, kind: 'fan', big: true },
        { x: 5, y: 7, kind: 'stool' },
        { x: 13, y: 11, kind: 'tubes', big: true },
        { x: 13, y: 4, kind: 'cog' },
        { x: 14, y: 0, kind: 'bin', big: true },
        { x: 6, y: 11, kind: 'cog', big: true },
      ],
      waves: [
        {
          at: 'start',
          spawns: [
            { enemy: 'enemy_rodeur', count: 2, x: 20, y: 6 },
            { enemy: 'enemy_eclipse', count: 1, x: 21, y: 3 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_nuee', count: 2, x: -1, y: -1 },
            { enemy: 'enemy_rodeur', count: 3, x: 21, y: 9 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_eclipse', count: 2, x: -1, y: -1 },
            { enemy: 'enemy_sentinelle', count: 2, x: 21, y: 3 },
            { enemy: 'enemy_meche', count: 2, x: 2, y: 10 },
          ],
        },
      ],
      traps: [],
      fragments: [],
      modular: [],
    },
    // ---------- SALLE 8 : COMBAT + PIÈGES + MODULAIRE ----------
    {
      id: 'room_b1_8',
      biome: 'biome_1',
      index: 8,
      type: 'COMBAT_TRAP_MODULAR',
      refTime: 90,
      obstacles: [
        { x: 2, y: 2, w: 1, h: 1, kind: 'machine' },
        { x: 21, y: 2, w: 1, h: 1, kind: 'machine' },
        { x: 2, y: 10, w: 1, h: 1, kind: 'machine' },
        { x: 21, y: 10, w: 1, h: 1, kind: 'machine' },
      ],
      deco: [
        { x: 17, y: 1, kind: 'valve' },
        { x: 5, y: 7, kind: 'valve' },
        { x: 6, y: 9, kind: 'tubes' },
        { x: 18, y: 3, kind: 'valve', big: true },
        { x: 14, y: 2, kind: 'pack' },
        { x: 11, y: 0, kind: 'hazard' },
        { x: 17, y: 6, kind: 'cog', big: true },
        { x: 3, y: 12, kind: 'bin', big: true },
        { x: 10, y: 10, kind: 'fan' },
        { x: 18, y: 0, kind: 'cog', big: true },
        { x: 3, y: 4, kind: 'valve', big: true },
        { x: 7, y: 4, kind: 'valve' },
      ],
      waves: [
        {
          at: 'start',
          spawns: [
            { enemy: 'enemy_bloc', count: 1, x: 21, y: 6 },
            { enemy: 'enemy_sentinelle', count: 2, x: 21, y: 3 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_meche', count: 3, x: -1, y: -1 },
            { enemy: 'enemy_rodeur', count: 3, x: 21, y: 9 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_incubateur', count: 1, x: 21, y: 6 },
            { enemy: 'enemy_eclipse', count: 2, x: -1, y: -1 },
          ],
        },
        {
          at: 'clear',
          spawns: [
            { enemy: 'enemy_sentinelle', count: 2, x: 3, y: 3 },
            { enemy: 'enemy_rodeur', count: 4, x: -1, y: -1 },
            { enemy: 'enemy_nuee', count: 1, x: 21, y: 9 },
          ],
        },
      ],
      traps: [
        { trap: 'trap_tourelle', x: 6, y: 0, phase: 0 },
        { trap: 'trap_tourelle', x: 17, y: 12, phase: 1.5 },
        { trap: 'trap_rail', x: 4, y: 2, w: 8, phase: 0 },
        { trap: 'trap_rail', x: 12, y: 10, w: 8, phase: 1.6 },
      ],
      fragments: [],
      modular: [
        { kind: 'rotor', cx: 12, cy: 6.5, arms: 3, length: 3, angularSpeed: 0.7 },
        {
          kind: 'floor_cycle',
          period: 9,
          telegraph: 1.5,
          configs: [
            [
              { x: 5, y: 4, w: 2, h: 1 },
              { x: 17, y: 8, w: 2, h: 1 },
            ],
            [
              { x: 5, y: 8, w: 2, h: 1 },
              { x: 17, y: 4, w: 2, h: 1 },
            ],
          ],
        },
      ],
    },
  ],
};
